Fix command for installing lts version
open-telemetry/opentelemetry.io pull request #1066
Opened 2022-01-20 23:12 UTC by mic-max

nvm install --lts
Unrecognized version: "--lts"

2022-01-20 23:25 UTC, chalin commented
Would you mind copy-pasting the exact command invocation, the output and it's version?

According to the `nvm` command help, `--lts` _is_ a valid flag:

```console
$ nvm version
v16.13.0
$ nvm | grep 'latest LTS version'
  nvm install --lts                     Install the latest LTS version
  nvm use --lts                         Use the latest LTS version
```

2022-01-20 23:27 UTC, chalin requested changes

2022-01-20 23:27 UTC, chalin commented on CONTRIBUTING.md
> -  $ nvm install --lts
The original command invocation is correct according to the `nvm` help info and docs.

2022-01-20 23:27 UTC, chalin commented on CONTRIBUTING.md
> +  $ nvm use lts
You don't need to run `use` after ` install` as far as I recall.

2022-01-22 15:21 UTC, chalin commented
Hi @mic-max. I'm going to close this for now. If you still feel that there's something wrong with the command invocation, feel free to reopen the PR.

2022-01-22 15:21 UTC, closed without merging

2022-01-22 16:36 UTC, mic-max commented
Hey @chalin so I was running `nvm` on Windows, but I guess the instructions here are all for Linux, that explains the difference

2022-01-22 16:45 UTC, chalin commented
Thanks for the feedback @mic-max. It's unfortunate that the `nvm` command for Windows accepts different arguments. I'll see how we can capture that in the instructions.

2022-01-22 16:46 UTC, chalin commented
I'll follow up via #1071. Thanks again for letting us know about this.