blog post: TroubleShooting NodeJS Tracing Issues
open-telemetry/opentelemetry.io pull request #1166
Opened 2022-02-23 15:45 UTC by blumamir

2022-02-24 20:33 UTC, austinlparker commented
Hey @blumamir we chatted about this in the comms meeting and our decision is that we don't want to host blogs that are summaries + links to another piece. If you would like to submit the full content of the post (with specific vendor calls-to-action stripped out) then we would be happy to host it and give a canonical link back to your blog.

2022-02-24 20:34 UTC, austinlparker requested changes
See earlier post in PR thread.

2022-02-27 12:53 UTC, blumamir commented
> Hey @blumamir we chatted about this in the comms meeting and our decision is that we don't want to host blogs that are summaries + links to another piece. If you would like to submit the full content of the post (with specific vendor calls-to-action stripped out) then we would be happy to host it and give a canonical link back to your blog.

Thanks @austinlparker
I'll try to find some time soon to update the PR accordingly. In the meantime converting to draft

2022-03-06 13:35 UTC, blumamir commented
> Hey @blumamir we chatted about this in the comms meeting and our decision is that we don't want to host blogs that are summaries + links to another piece. If you would like to submit the full content of the post (with specific vendor calls-to-action stripped out) then we would be happy to host it and give a canonical link back to your blog.

@austinlparker  Updated the PR

2022-03-08 16:42 UTC, austinlparker approved these changes
Some tweaks to the title but otherwise lgtm

2022-03-08 16:42 UTC, austinlparker commented on content/en/blog/2022/troubleshooting-nodejs.md
> +title: Checklist for TroubleShooting OpenTelemetry NodeJS Tracing Issues
```suggestion
title: Checklist for Troubleshooting OpenTelemetry Node.JS Tracing Issues
```

2022-03-09 16:54 UTC, chalin commented on content/en/blog/2022/troubleshooting-nodejs.md
> +[original post][].
Move this to the end of the post and, ideally turn it into a (short) sentence.

2022-03-09 16:55 UTC, chalin commented on content/en/blog/2022/troubleshooting-nodejs.md
> +Examples:
-> Examples include:

2022-03-09 18:54 UTC, austinlparker commented
Content seems fine.

2022-03-09 18:54 UTC, merged

2022-03-09 18:55 UTC, chalin commented
Merged. I'll make a pass over it after. (I hadn't seen @austinlparker's LGTM from earlier until I confirmed with him just now.)