add img alt
open-telemetry/opentelemetry.io pull request #1718
Opened 2022-09-06 15:23 UTC by Petrie

2022-09-07 07:12 UTC, svrnm commented
Thanks for your contribution @Petrie. One change request: those images are not really logos just icons/pictograms representing those languages, can you remove the word "logo" from all `alt` tags, e.g.:

```html
  <img width="35"
  src="https://raw.github.com/open-telemetry/opentelemetry.io/main/iconography/32x32/C++_SDK.svg"
  alt="C++"></img>
```

2022-09-07 07:18 UTC, Petrie commented
@svrnm Got that!

2022-09-07 14:58 UTC, Kielek commented on content/en/docs/instrumentation/net/_index.md
> +  alt="NET"></img>
```suggestion
  alt=".NET"></img>
```
or dotnet.

2022-09-07 15:29 UTC, lalitb approved these changes
Looks good for C++.

2022-09-07 15:42 UTC, Kielek approved these changes

2022-09-07 15:51 UTC, svrnm requested changes

2022-09-07 15:51 UTC, svrnm commented on content/en/docs/instrumentation/js/_index.md
> +  alt="JS"></img>
JS -> JavaScript

2022-09-07 16:06 UTC, reyang approved these changes

2022-09-07 16:23 UTC, tsloughter commented on content/en/docs/instrumentation/erlang/_index.md
> +  alt="Erlang"></img>
```suggestion
  alt="Erlang/Elixir"></img>
```

2022-09-07 17:59 UTC, nrcventura approved these changes

2022-09-07 18:23 UTC, pjanotti approved these changes
.NET looks good.

2022-09-07 18:25 UTC, srikanthccv approved these changes

2022-09-07 18:27 UTC, svrnm commented on content/en/docs/instrumentation/erlang/_index.md
> +  src="https://raw.github.com/open-telemetry/opentelemetry.io/main/iconography/32x32/Elixir_SDK.svg"
can you use the Erlang logo here? (should just be s/Elixir/Erlang) cc: @tsloughter

2022-09-08 08:17 UTC, svrnm approved these changes

2022-09-08 08:20 UTC, svrnm commented
I think this looks good overall, thank you @Petrie

2022-09-08 08:20 UTC, merged