Announcement blog for new EUDG
open-telemetry/opentelemetry.io pull request #2066
Opened 2022-12-01 23:12 UTC by reese-lee

This blog post has the following goals:

1. To announce the **new** End User Discussion Groups for the APAC region, starting January 2023
2. To promote the upcoming EMEA and AMER sessions
3. To raise awareness and increase attendance of these sessions, particularly to newer members of the community

2022-12-02 10:44 UTC, svrnm requested changes

2022-12-02 10:44 UTC, svrnm commented on content/en/blog/2022/end-user-discussion-group-apac/index.md
> +[Monthly Discussion Groups](https://opentelemetry.io/community/end-user/discussion-group/)
```suggestion
[Monthly Discussion Groups](/community/end-user/discussion-group/) 
```
Use relative URLs otherwise the netlify build breaks

2022-12-02 10:44 UTC, svrnm commented on content/en/blog/2022/end-user-discussion-group-apac/index.md
> +any collected user feedback* with the appropriate project maintainers to help
you might need to escapte that star and the one below otherwise markdown might start to print everything bold from here on (or trip otherwise)

2022-12-02 10:44 UTC, svrnm commented on content/en/blog/2022/end-user-discussion-group-apac/index.md
> +  * January 19, 2023 9AM PST
For IST you give a GMT relative time, for CET and PST not, could be helpful there as well.

2022-12-02 17:40 UTC, cartermp approved these changes
I dig it! And also exciting to see.

2022-12-05 10:09 UTC, svrnm approved these changes

2022-12-05 18:26 UTC, mtwo approved these changes

2022-12-05 18:27 UTC, mtwo commented
@reese-lee let me know when you'd like this merged!

2022-12-05 21:17 UTC, reese-lee commented
@mtwo If possible, today would be great! since the AMER session is next Thursday.

2022-12-05 21:19 UTC, merged

2022-12-05 21:19 UTC, mtwo commented
Merged!