Add semantic conventions to the concepts TOC in docs
open-telemetry/opentelemetry.io pull request #2153
Opened 2023-01-10 20:47 UTC by cartermp

Adds it so you can navigate to this very important concept easily.

It should have more commentary and all that, but for now let's surface it more.

2023-01-10 20:53 UTC, svrnm requested changes

2023-01-10 20:53 UTC, svrnm commented on content/en/docs/concepts/semantic-conventions.md
> +Currently, Semantic Conventions are split by signal:
ppl might get confused that there is a "Resource Semantic Convention" then, maybe

```suggestion
Currently, Semantic Conventions are available for traces, metrics and resources:
```

2023-01-10 21:45 UTC, chalin reviewed
Wouldn't it make the most sense to have such a page under `/docs/reference/specification`?

2023-01-10 22:37 UTC, cartermp commented
I don't think so, no. Eventually this page should have commentary and link out to the reference as needed. I don't want to start adding docs-like things that summarize and rephrase concepts to the spec. Additionally, I think we lose discovery by making it part of the spec. In general I've found a deep reluctance to dive into the spec when talking to end users.

2023-01-11 08:25 UTC, svrnm approved these changes

2023-01-11 08:25 UTC, merged