OpenTelemetry PHP Beta Blog Post
open-telemetry/opentelemetry.io pull request #2200
Opened 2023-01-25 14:04 UTC by bobstrecansky

Creating an OpenTelemetry PHP Beta Announcement Blog Post

2023-01-25 14:22 UTC, svrnm requested changes
Exciting :-)

2023-01-25 14:22 UTC, svrnm commented on content/en/blog/2023/opentelemetry-php-beta-release/index.md
> +title: {{ Opentelemetry-php Beta Release }}
```suggestion
title: OpenTelemetry PHP Beta Release
```

2023-01-25 14:22 UTC, svrnm commented on content/en/blog/2023/opentelemetry-php-beta-release/index.md
> +linkTitle: PHP Beta Release # Mandatory, make sure that your short title.
```suggestion
linkTitle: PHP Beta Release
```

2023-01-25 14:22 UTC, svrnm commented on content/en/blog/2023/opentelemetry-php-beta-release/index.md
> +draft: true
```suggestion
```

2023-01-25 14:22 UTC, svrnm commented on content/en/blog/2023/opentelemetry-php-beta-release/index.md
> +OpenTelemetry PHP Beta Release Blog Post
```suggestion
```

The title will be set via the `title` above.

2023-01-25 14:22 UTC, svrnm commented on content/en/blog/2023/opentelemetry-php-beta-release/index.md
> +We are actively soliciting feedback from the development community for this library.  Please check out the repo, instrument your PHP app with the product, and open an issue if you’d like to see a bug
```suggestion
We are actively soliciting feedback from the development community for this library. Please check out the repo, instrument your PHP app with the product, and open an issue if you’d like to see a bug squashed or a new feature added.
```

2023-01-25 14:22 UTC, svrnm commented on content/en/blog/2023/opentelemetry-php-beta-release/index.md
> +We have lots of [examples](https://github.com/open-telemetry/opentelemetry-php/tree/main/examples) in the repo to get you started, or you can check out the [quote service](https://github.com/open-tel
```suggestion
We have lots of [examples](/docs/instrumentation/php/examples/) in the repo to get you started, or you can check out the [quote service](https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/services/quoteservice.md), a demo application built in PHP to showcase the library.
```

Pointing to the examples link here in the doc. Also do you want to call out the Getting Started in the docs here?

2023-01-25 14:22 UTC, svrnm commented on content/en/blog/2023/opentelemetry-php-beta-release/index.md
> +Questions?  Feel free to reach out to us in the CNCF [#otel-php](https://cloud-native.slack.com/archives/C01NFPCV44V) slack channel, or come to our SIG meeting (which you can find on the [otel public
```suggestion
Questions? Feel free to reach out to us in the CNCF [#otel-php](https://cloud-native.slack.com/archives/C01NFPCV44V) slack channel, or come to our SIG meeting, which you can find on the [otel public calendar](https://calendar.google.com/calendar/embed?src=google.com_b79e3e90j7bbsa2n2p5an5lf60%40group.calendar.google.com)
```

2023-01-25 14:31 UTC, svrnm commented
@chalin @cartermp since the banner announcing the APAC End User Group is up there for a while now, maybe we want to replace it with an PHP Beta announcement?

2023-01-25 15:35 UTC, cartermp commented
Yes, absolutely. This is a real banger IMO, deserves a banner!

2023-01-25 15:45 UTC, cartermp commented on content/en/blog/2023/opentelemetry-php-beta-release/index.md
> +We are actively soliciting feedback from the development community for this library.  Please check out the repo, instrument your PHP app with the product, and open an issue if you’d like to see a bug
Link to repo would be great

2023-01-25 21:09 UTC, chalin commented
Was hoping to see a preview, but I guess that the PR isn't building yet... ?

2023-01-25 21:10 UTC, chalin commented
I'll make a pass once the PR builds.

2023-01-26 13:53 UTC, bobstrecansky commented
@svrnm - I think I addressed all your changes.  Please let me know if there are additional things you'd like me to change.

2023-01-26 16:03 UTC, cartermp approved these changes
Thanks! Excited to see this go 🚀

2023-01-26 16:16 UTC, chalin requested changes
Rename:

- From `content/en/blog/2023/opentelemetry-php-beta-release/index.md`
- To `content/en/blog/2023/php-beta-release.md`

There's something wrong with this PR because it doesn't build.

@bobstrecansky - I'd suggest closing and reopening it again after you pull the latest changes and rename the file as suggested above.

2023-01-26 16:24 UTC, chalin approved these changes
Actually, it builds for me locally, so I'm ok with merging this once @svrnm and @cartermp are happy. (Btw, I made a few copyedits.)

2023-01-27 13:46 UTC, svrnm approved these changes

2023-01-27 13:49 UTC, svrnm commented
Ah... @bobstrecansky:


> [bobstrecansky](https://github.com/bobstrecansky) wants to merge 7 commits into [open-telemetry:opentelemetry_php_beta_blog_post](https://github.com/open-telemetry/opentelemetry.io/tree/opentelemetry_php_beta_blog_post) from [bobstrecansky:opentelemetry_php_beta_blog_post](https://github.com/bobstrecansky/opentelemetry.io/tree/opentelemetry_php_beta_blog_post)

Can you raise the PR against main? TY

2023-01-27 14:57 UTC, bobstrecansky commented
Sorry about that, what a bonehead mistake 🤦🏼 
https://github.com/open-telemetry/opentelemetry.io/pull/2219

2023-01-27 14:57 UTC, closed without merging