Add HTTP semantic convention stability blog post
open-telemetry/opentelemetry.io pull request #2212
Opened 2023-01-26 21:34 UTC by trask

(for reference, see https://github.com/open-telemetry/opentelemetry-specification/issues/3112)

2023-01-26 21:54 UTC, cartermp commented
Be still, my heart! 😍

2023-01-26 22:05 UTC, cartermp approved these changes
Minor copy-edits. Very happy to announce this.

2023-01-26 22:05 UTC, cartermp commented on content/en/blog/2023/http-conventions-stability/index.md
> +This group will be submitting spec PRs for any changes that need to be made
```suggestion
This group will submit spec PRs for any changes that need to be made
```

2023-01-26 22:05 UTC, cartermp commented on content/en/blog/2023/http-conventions-stability/index.md
> +the HTTP semantic convention stability working group will be meeting three times
```suggestion
the HTTP semantic convention stability working group will meet three times
```

2023-01-27 13:52 UTC, svrnm requested changes
love it, some minor suggestions

2023-01-27 13:52 UTC, svrnm commented on content/en/blog/2023/http-conventions-stability/index.md
> +* Fri 9:30-10
keep the info for each of them that it is in Pacific Time

2023-01-27 13:52 UTC, svrnm commented on content/en/blog/2023/http-conventions-stability/index.md
> +The OpenTelemetry community is beginning the final push to declare HTTP semantic
Link to the HTTP semantic conventions in the spec?

2023-01-27 14:42 UTC, chalin approved these changes
✨

2023-01-27 21:29 UTC, svrnm approved these changes

2023-01-27 21:29 UTC, austinlparker approved these changes

2023-01-30 08:19 UTC, svrnm commented
I will merge this one in before the PHP one, because it is time sensitive (the 30th is today!)

2023-01-30 08:19 UTC, merged