Fix x509 error about vendor link
open-telemetry/opentelemetry.io pull request #2350
Opened 2023-02-16 03:01 UTC by windsonsea

Hi @chalin , as you suggested in #2128, the `https` certificate was updated months ago.  

Now change the url to `Insight` that is an observability product and integrates with many OTel features. 

<img width="471" alt="image" src="https://user-images.githubusercontent.com/79828097/219256052-e0a02f85-4c3d-4381-b107-36b34cf930c6.png">

2023-02-16 03:08 UTC, chalin requested changes
I'm still see an invalid certificate (notice the expiry date):

> <img width="536" alt="image" src="https://user-images.githubusercontent.com/4140793/219258006-1cfff8bf-1d91-41fa-be1d-e8e17dd34d29.png">

2023-02-16 03:08 UTC, chalin commented on content/en/ecosystem/vendors.md
> +| DaoCloud                   | Yes               | Yes         | [docs.daocloud.io/...](https://docs.daocloud.io/en/insight/03ProductBrief/WhatisInsight/)
As @cartermp mentioned elsewhere, we prefer links into the OTel docs, so the original link was better.

2023-02-16 03:35 UTC, windsonsea commented
ok, well noted. I'm asking IT staff why. This PR can be closed because nothing need to be changed currently.

The certificate looks different in and out of China -_! 

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/79828097/219261804-e7c99f4d-a9b4-41e3-b066-257bad3de7c8.png">

2023-02-16 03:35 UTC, closed without merging

2023-02-16 13:15 UTC, chalin commented
> The certificate looks different in and out of China -_!

That is what I was beginning to suspect.

2023-02-17 01:19 UTC, windsonsea commented
Finally, the SSL certificate works now. It is effective after 24:00 last night while it was updated 8 hours ago.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/79828097/219524925-a1914ab9-6ded-4b9c-a6f8-96d23db7bc28.png">

Verified it at: https://www.sslchecker.com/sslchecker

2023-02-19 14:45 UTC, chalin commented
Thanks for the confirmation. I've removed the link-checker ignore rule for daocloud.io in #2362, see https://github.com/open-telemetry/opentelemetry.io/pull/2362/files#diff-9ad64044531d7d8c033064f11141586478b535147312374c24f8d2d997722889L19-L20.