Fixing CLI command for docker-compose in docker deployment Docs
open-telemetry/opentelemetry.io pull request #2693
Opened 2023-05-10 19:26 UTC by CoryBarney

The shell command for docker-compose on linux / windows is one word with a hyphen tweaking the example to work without modifications

Not sure if there is a particular branch or tag to give for documentation updates but it is a 2 character fix so I don't want to overthink it.

2023-05-10 23:38 UTC, chalin approved these changes

2023-05-11 05:03 UTC, mviitane requested changes
docker-compose is the old, deprecated command. I think the demo docs are up-to-date around this.
See:
https://docs.docker.com/compose/migrate/

2023-05-11 05:33 UTC, julianocosta89 reviewed
Exactly what @mviitane have said.
`docker compose` not hyphenated is the newest version and the one that should be used to run the demo.

I think we can close this PR.

2023-05-11 07:35 UTC, svrnm commented
Wondering if we should add a call out about that to the document? just add a small sentence after the requirement of docker compose 2+?

2023-05-11 08:25 UTC, julianocosta89 commented
@svrnm it is already there: https://opentelemetry.io/docs/demo/docker-deployment/#prerequisites

2023-05-11 08:32 UTC, svrnm commented
> @svrnm it is already there: https://opentelemetry.io/docs/demo/docker-deployment/#prerequisites

What I meant was something like

```
## Prerequisites

- Docker
- [Docker Compose](https://docs.docker.com/compose/install/#install-compose)
  v2.0.0+ (Note: if you are using `docker-compose` you still use v1 and need to upgrade)
- 4 GB of RAM for the application
```

2023-05-11 08:37 UTC, julianocosta89 commented
Ah I see. Yeah, I don't think that would hurt 😅

2023-05-11 11:21 UTC, chalin commented
@svrnm et al.: Might it make sense to uniformly use `docker compose` throughout the docs? Doing a quick search, this is how it currently looks:

```console
# opentelemetry.io
$ find . -type f -name "*.md" -path "./content/*" -exec grep -nH -e 'docker-compose ' {} +        
./content/en/docs/collector/getting-started.md:21:  docker-compose up -d
./content/en/blog/2022/apisix/index.md:194:The following uses docker-compose as an example. For other deployments, see
./content/en/blog/2022/apisix/index.md:202:docker-compose up -d
./content/en/blog/2022/debug-otel-with-otel/index.md:140:Spin up that environment by running `docker-compose up` and send some requests
./content/en/blog/2022/debug-otel-with-otel/index.md:202:Once again we ran `docker-compose up` to bring up our sample app and we send
./content/en/blog/2022/instrument-apache-httpd-server/index.md:30:docker-compose --profile centos7 build
./content/en/blog/2022/instrument-apache-httpd-server/index.md:42:docker-compose --profile centos7 up -d
./content/en/blog/2022/instrument-apache-httpd-server/index.md:158:  docker-compose --profile centos7 build
./content/en/blog/2022/instrument-nginx/index.md:171:$ docker-compose up
./content/en/blog/2022/instrument-nginx/index.md:335:$ docker-compose up
./content/en/blog/2023/end-user-q-and-a-02.md:249:example, for a Ruby developer, clone X repo, run `docker-compose up`, and
$ find . -type f -name "*.md" -path "./content/*" -exec grep -nH -e 'docker-compose ' {} + | wc -l
      11
$ find . -type f -name "*.md" -path "./content/*" -exec grep -nH -e 'docker.compose ' {} + | wc -l
      19
```

2023-05-11 16:43 UTC, CoryBarney commented
Also ill need to double check which version of docker that gets introduced on, I was running it on Debian 11 with whatever the latest docker package in the the standard repository is so fair game if it needs to be the community edition and I am just behind the times, I should rtfm and put that version that was in the docs on.

If it is just me being a dolt, fair game

2023-05-15 08:35 UTC, svrnm commented
I created #2717 to solve this consistently. Tbh, I don't have a good answer for it yet.

Thank you for bringing this to our attention @CoryBarney

2023-05-16 17:43 UTC, CoryBarney commented
Golden, thanks for putting up my shenanigans.

I'll close this PR if there is no need for it then

2023-05-16 17:45 UTC, svrnm commented
> Golden, thanks for putting up my shenanigans.

Thank you for bringing this to our attention, even if we can not provide a good solution right now ;-) 
 
> I'll close this PR if there is no need for it then

Yes, let's close it for now

2023-05-17 11:23 UTC, closed without merging