Update lambda-auto-instrument.md
open-telemetry/opentelemetry.io pull request #2945
Opened 2023-06-29 15:25 UTC by tylerbenson

Instructions were missing the step to configure `AWS_LAMBDA_EXEC_WRAPPER`.  Also fixed the java supported versions.

2023-06-29 19:09 UTC, chalin commented on content/en/docs/faas/lambda-auto-instrument.md
> +`AWS_LAMBDA_EXEC_WRAPPER=/opt/otel-instrument` for python.  These wrapper scripts will invoke your lambda application
```suggestion
Change the entry point of your application by setting `AWS_LAMBDA_EXEC_WRAPPER=/opt/otel-handler` for Node.js or Java, and
`AWS_LAMBDA_EXEC_WRAPPER=/opt/otel-instrument` for Python.  These wrapper scripts will invoke your Lambda application
```

2023-06-29 19:32 UTC, chalin requested changes
Some of the text is misformatted (see inline comments for fixes) as can be seen from this screenshot:

> <img width="701" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/dc56c356-6bd9-4971-b581-ae2c39db9106">

2023-06-29 19:32 UTC, chalin commented on content/en/docs/faas/lambda-auto-instrument.md
>      ```bash
Unindent this code block.

2023-06-29 19:32 UTC, chalin commented on content/en/docs/faas/lambda-auto-instrument.md
>      ```bash
Also the list items at lines 51 and 52 above need to be unindented. 

Would you mind fixing them? Thanks!

2023-06-29 21:17 UTC, chalin commented on content/en/docs/faas/lambda-auto-instrument.md
>      ```bash
Thanks!

2023-06-29 21:19 UTC, chalin approved these changes
LGTM

Will let others validate content.

2023-06-30 09:03 UTC, svrnm approved these changes

2023-06-30 09:03 UTC, merged