Add initial Java documentation
open-telemetry/opentelemetry.io pull request #304
Opened 2020-11-07 04:18 UTC by flands

Addresses #283 This will supersede documentation currently captured in README. Separate
PRs will address this.

TODOs in future PRs:
- Exporters
- Sampling

2020-11-08 19:44 UTC, snyder114 requested changes

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +title: "Manual Instrumentation"
```suggestion
Title: "Manual Instrumentation"
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +weight: 3
```suggestion
Weight: 3
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +or application to be monitored.
```suggestion
In order to instrument, you must acquire a `Tracer`. A `Tracer` is responsible for
creating spans and interacting with the [`Context`](#context-propagation). To acquire a
`Tracer` use the [OpenTelemetry Tracing
API](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md)
and specify the name and version of the [library
instrumenting](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/glossary.md#instrumentation-library)
the [instrumented
library](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/glossary.md#instrumented-library)
or application to be monitored.
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +For more details how to share context between remote processes, see [Context
```suggestion
For more information about how to share context between remote processes, see [Context
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +The OpenTelemetry API offers also an automated way to propagate the parentSpan:
```suggestion
The OpenTelemetry API also offers an automated way to propagate the parentSpan:
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +such as results or operation properties.
```suggestion
In OpenTelemetry, you can create spans freely. It's up to the implementor to
annotate spans with attributes specific to the represented operation. Attributes
provide additional context on a span about the specific operation it tracks,
such as results or operation properties.
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +HTTP or database calls. For these, OpenTelemetry requires specific attributes
```suggestion
HTTP or database calls. For these operations, OpenTelemetry requires specific attributes
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +processed in the batch.
```suggestion
You can link a span to zero or more other spans that are causally related.
Use links to represent batched operations where a span was initiated by
multiple initiating spans, each representing a single incoming item being
processed in the batch.
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +For more details how to read context from remote processes, see [Context
```suggestion
For more information about how to read context from remote processes, see [Context
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +`HttpURLConnection`.
```suggestion
The following example shows an outgoing HTTP request using
`HttpURLConnection`:
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +[HttpExchange](https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/HttpExchange.html).
```suggestion
Similarly, you can use the text-based approach to read the W3C Trace Context
from incoming requests. The following example demonstrates processing an
incoming HTTP request using
[HttpExchange](https://docs.oracle.com/javase/8/docs/jre/api/net/httpserver/spec/com/sun/net/httpserver/HttpExchange.html):
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +This span processor exports span immediately after they are ended.
```suggestion
This span processor exports spans immediately after they end.
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +A varitey of configuration parameters can also be specified:
```suggestion
You can also specify a variety of configuration parameters:
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +A MultiSpanProcessor accepts a list of Span Processors.
```suggestion
A MultiSpanProcessor accepts a list of span processors.
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/manual_instrumentation.md
> +describe what subdivision of the measurements the metric represents.
```suggestion
OpenTelemetry provides support for metrics, a time series of numbers that might
express things such as CPU utilization, request count for an HTTP server, or a
business metric such as transactions.

All metrics can be annotated with labels. Labels are additional qualifiers that help
describe what subdivision of the measurements the metric represents.
```

2020-11-08 19:44 UTC, snyder114 commented on content/en/docs/java/getting_started.md
> +- Start the client
```suggestion
To get started, perform the following steps::

1. Clone the repository
2. Change into the example directory
3. Compile the code
4. Start the server
5. Start the client
```

2020-11-08 21:17 UTC, flands commented
@snyder114 thanks for the feedback! I noticed you recently merged an updated README to the Java repo. FYI, it will be removed once this PR is merged and then https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1581 is merged. Would love to get the changes added here as well.

2020-11-09 13:20 UTC, austinlparker approved these changes
lgtm - could you fix the broken links?

2020-11-09 14:18 UTC, flands commented on content/en/docs/java/getting_started.md
> +For additional information, see the [Automatic Instrumentation documentation](/docs/java/automatic-instrumentation/#traces).
```suggestion
For additional information, see the [Automatic Instrumentation documentation](/docs/java/automatic_instrumentation).
```

2020-11-09 14:18 UTC, flands commented on content/en/docs/java/getting_started.md
> +For more detailed information, see the [Manual Instrumentation documentation](/docs/java/manual-instrumentation/#traces).
```suggestion
For more detailed information, see the [Manual Instrumentation documentation](/docs/java/manual_instrumentation/#traces).
```

2020-11-09 14:19 UTC, flands commented on content/en/docs/java/getting_started.md
> +For more detailed information, see the [Manual Instrumentation documentation](/docs/java/manual-instrumentation/#metrics).
```suggestion
For more detailed information, see the [Manual Instrumentation documentation](/docs/java/manual_instrumentation/#metrics).
```

2020-11-09 14:21 UTC, flands commented on content/en/docs/java/automatic_instrumentation.md
> +See the [Manual Instrumentation documentation](/docs/java/manual-instrumentation/#spans)
```suggestion
See the [Manual Instrumentation documentation](/docs/java/manual_instrumentation/#instantiate-tracer)
```

2020-11-09 14:22 UTC, flands commented on content/en/docs/java/manual_instrumentation.md
> +to the [`Tracer`](#instantiate-a-tracer).
```suggestion
to the [`Tracer`](#instantiate-tracer).
```

2020-11-09 14:23 UTC, flands commented on content/en/docs/java/manual_instrumentation.md
> +Attributes](#span-attributes), each of which is itself a name/value map paired
```suggestion
Attributes](#attributes), each of which is itself a name/value map paired
```

2020-11-09 14:29 UTC, merged