Enhanced Accessibility with Alt Attributes
open-telemetry/opentelemetry.io pull request #3226
Opened 2023-09-05 03:18 UTC by ydFu

1. We have improved the accessibility of our documentation by adding descriptive 'alt' attributes to image tags.
    By providing meaningful 'alt' attributes for these images, we enhance the usability of our documentation for individuals who rely on screen readers or have other accessibility needs.
2. Rename 'Load_Balancer.svg' to 'Connectors.svg' for improved maintainability.

2023-09-05 13:03 UTC, svrnm commented on iconography/32x32/Connectors.svg
This image is used as load balancer at other places as well. I used it here because we have no real connector image, so we can not rename it that way.

2023-09-05 13:06 UTC, svrnm commented
Thanks for raising this PR, I agree with you that `alt` tags should be used where possible, so I am happy to add them.

In the case of these images, I would argue the `alt` should be set to `""` as those images are not key part of the content and purely decorative, so a non-visual browser can skip them (otherwise it would read all words twice)

For reference:

> Setting this attribute to an empty string (alt="") indicates that this image is not a key part of the content (it's decoration or a tracking pixel), and that non-visual browsers may omit it from [rendering](https://developer.mozilla.org/en-US/docs/Glossary/Rendering_engine). Visual browsers will also hide the broken image icon if the alt is empty and the image failed to display.

(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attributes)

2023-09-05 13:08 UTC, svrnm requested changes

2023-09-05 13:08 UTC, svrnm commented on content/en/docs/collector/configuration.md
> +  <img width="32" class="img-initial" src="/img/logos/32x32/Receivers.svg" alt="Receivers">
```suggestion
  <img width="32" class="img-initial" src="/img/logos/32x32/Receivers.svg" alt="">
```

2023-09-05 13:08 UTC, svrnm commented on content/en/docs/collector/configuration.md
> +  <img width="32" class="img-initial" src="/img/logos/32x32/Processors.svg" alt="Processors">
```suggestion
  <img width="32" class="img-initial" src="/img/logos/32x32/Processors.svg" alt="">
```

2023-09-05 13:08 UTC, svrnm commented on content/en/docs/collector/configuration.md
> +  <img width="32" class="img-initial" src="/img/logos/32x32/Exporters.svg" alt="Exporters">
```suggestion
  <img width="32" class="img-initial" src="/img/logos/32x32/Exporters.svg" alt="">
```

2023-09-05 13:08 UTC, svrnm commented on content/en/docs/collector/configuration.md
> +  <img width="32" class="img-initial" src="/img/logos/32x32/Connectors.svg" alt="Connectors">
```suggestion
  <img width="32" class="img-initial" src="/img/logos/32x32/Load_Balancer.svg" alt="">
```

2023-09-05 13:09 UTC, svrnm commented on content/en/docs/collector/configuration.md
> +## Receivers <img width="32" class="img-initial" src="/img/logos/32x32/Receivers.svg" alt="Receivers"> {#receivers}
```suggestion
## Receivers <img width="32" class="img-initial" src="/img/logos/32x32/Receivers.svg" alt=""> {#receivers}
```

2023-09-05 13:09 UTC, svrnm commented on content/en/docs/collector/configuration.md
> +## Processors <img width="32" class="img-initial" src="/img/logos/32x32/Processors.svg" alt="Processors"> {#processors}
```suggestion
## Processors <img width="32" class="img-initial" src="/img/logos/32x32/Processors.svg" alt=""> {#processors}
```

2023-09-05 13:09 UTC, svrnm commented on content/en/docs/collector/configuration.md
> +## Exporters <img width="32" class="img-initial" src="/img/logos/32x32/Exporters.svg" alt="Exporters"> {#exporters}
```suggestion
## Exporters <img width="32" class="img-initial" src="/img/logos/32x32/Exporters.svg" alt=""> {#exporters}
```

2023-09-05 13:09 UTC, svrnm commented on content/en/docs/collector/configuration.md
> +## Connectors <img width="32" class="img-initial" src="/img/logos/32x32/Connectors.svg" alt="Connectors"> {#connectors}
```suggestion
## Connectors <img width="32" class="img-initial" src="/img/logos/32x32/Load_Balancer.svg" alt=""> {#connectors}
```

2023-09-06 01:39 UTC, ydFu commented on iconography/32x32/Connectors.svg
Thanks,I understand the underlying reasons for this choice.

2023-09-06 01:44 UTC, ydFu commented
> 

In the context of these images, my revised recommendation is to set the 'alt' attribute to an empty string ('') since these images do not constitute a critical part of the content.

2023-09-06 01:46 UTC, ydFu commented on content/en/docs/collector/configuration.md
> +  <img width="32" class="img-initial" src="/img/logos/32x32/Receivers.svg" alt="Receivers">
done,thanks

2023-09-06 01:46 UTC, ydFu commented on content/en/docs/collector/configuration.md
> +  <img width="32" class="img-initial" src="/img/logos/32x32/Processors.svg" alt="Processors">
done,thanks

2023-09-06 01:46 UTC, ydFu commented on content/en/docs/collector/configuration.md
> +  <img width="32" class="img-initial" src="/img/logos/32x32/Exporters.svg" alt="Exporters">
done,thanks

2023-09-06 01:46 UTC, ydFu commented on content/en/docs/collector/configuration.md
> +  <img width="32" class="img-initial" src="/img/logos/32x32/Connectors.svg" alt="Connectors">
done,thanks

2023-09-06 01:46 UTC, ydFu commented on content/en/docs/collector/configuration.md
> +## Receivers <img width="32" class="img-initial" src="/img/logos/32x32/Receivers.svg" alt="Receivers"> {#receivers}
done,thanks

2023-09-06 01:47 UTC, ydFu commented on content/en/docs/collector/configuration.md
> +## Processors <img width="32" class="img-initial" src="/img/logos/32x32/Processors.svg" alt="Processors"> {#processors}
done,thanks

2023-09-06 01:47 UTC, ydFu commented on content/en/docs/collector/configuration.md
> +## Exporters <img width="32" class="img-initial" src="/img/logos/32x32/Exporters.svg" alt="Exporters"> {#exporters}
done,thanks

2023-09-06 01:47 UTC, ydFu commented on content/en/docs/collector/configuration.md
> +## Connectors <img width="32" class="img-initial" src="/img/logos/32x32/Connectors.svg" alt="Connectors"> {#connectors}
done,thanks

2023-09-06 08:42 UTC, svrnm approved these changes

2023-09-06 08:42 UTC, svrnm commented
thank you @ydFu !

2023-09-06 17:24 UTC, merged

2023-09-07 14:17 UTC, cartermp commented
Sorry @ydFu this apparently broke `main` and I had to revert in https://github.com/open-telemetry/opentelemetry.io/pull/3231

For some reason, our checks didn't pick it up. The site wouldn't build with these changes. I'm honestly not sure why, but I can investigate.