New blog post on how to contribute to OTel
open-telemetry/opentelemetry.io pull request #3238
Opened 2023-09-08 15:07 UTC by avillela

Blog post on how to contribute to OTel.

2023-09-11 08:10 UTC, svrnm requested changes

2023-09-11 08:10 UTC, svrnm commented on content/en/blog/2023/contributing-to-otel/index.md
> +### **Contribute to the OpenTelemetry Demo**
```suggestion
### Contribute to the OpenTelemetry Demo
```

2023-09-11 08:10 UTC, svrnm commented on content/en/blog/2023/contributing-to-otel/index.md
> +
again, add your [own contributions](https://github.com/open-telemetry/opentelemetry-demo/pull/432), so people have something tangible, especially this one ticket shows that contributing is a little bit of work, but you get feedback and over some time it gets merged

2023-09-11 08:10 UTC, svrnm commented on content/en/blog/2023/contributing-to-otel/index.md
> +### **Join a Special Interest Group**
```suggestion
### Join a Special Interest Group
```

2023-09-11 08:10 UTC, svrnm commented on content/en/blog/2023/contributing-to-otel/index.md
> +### **Final thoughts**
```suggestion
### Final thoughts
```

2023-09-11 08:10 UTC, svrnm commented on content/en/blog/2023/contributing-to-otel/turks-sunset.jpg
Can you scale this image down, with ~840KB it is fairly big and even on a large screen it is scaled down significantly on the page itself

2023-09-13 07:21 UTC, svrnm requested changes
looks good to me overall, 2 more comments

2023-09-13 07:21 UTC, svrnm commented on content/en/blog/2023/contributing-to-otel/index.md
> +### **Contribute to the OTel Docs**
```suggestion
###Contribute to the OTel Docs
```

2023-09-13 07:21 UTC, svrnm commented on content/en/blog/2023/contributing-to-otel/index.md
> +contributing to the OTel Demo, or joining a SIG. Anything helps!
It's maybe worth to emphasis that there are also contributions like "giving talks about OpenTelemetry", "telling your friends and family (and co-workers) how awesome OpenTelemetry is", so also things outside the repositories and official infrastructure (slack, zooms, cncf thingies) is highly helpful

2023-09-13 15:25 UTC, svrnm approved these changes
looks good to me now!

@open-telemetry/docs-approvers any more comments? PTAL before merge!:)

2023-09-13 15:25 UTC, svrnm commented on content/en/blog/2023/contributing-to-otel/index.md
> +date: 2023-09-08
Let's maybe have this blog post on Monday, since we had the PHP one just today

```suggestion
date: 2023-09-18
```

2023-09-14 00:26 UTC, cartermp approved these changes

2023-09-14 01:00 UTC, merged

2023-09-14 07:06 UTC, svrnm commented
@cartermp publication date is set to `date: 2023-09-18` so we have to make sure that something gets merged on Monday to make the blog show up