Golang Getting started - based on roll dice service and Automatic Ins…
open-telemetry/opentelemetry.io pull request #3244
Opened 2023-09-09 17:16 UTC by pegasas

try to add an roll dice example with golang, solving https://github.com/open-telemetry/opentelemetry.io/issues/2623

2023-09-10 15:00 UTC, MrAlias requested changes
This changes the substance of this documentation from manual instrumentation to automatic instrumentation. Automatic instrumentation deserves to live besides this not in-place of it.

2023-09-11 07:47 UTC, svrnm commented
thanks for raising this @pegasas. This still looks work-in-progress for me, so please put this into draft mode for now.

> This changes the substance of this documentation from manual instrumentation to automatic instrumentation. Automatic instrumentation deserves to live besides this not in-place of it.

Right now I don't see how the documentation has been changed from manual to automatic instrumentation, as it seems incomplete. To comment on that nevertheless, as we have a discussion on the same ongoing [over here](https://github.com/open-telemetry/opentelemetry.io/issues/3228): _ the assumption is that a Getting Started should give you something tangible as quick as possible in your preferred language_, so if the Golang SIG at some point comes to the conclustion that automatic instrumentation might be a better route to that, we can adopt it in the Getting Started, and have a similar structure as we have it for Java & JavaScript these days (Getting Started using mostly automation, have a "manual" and "automatic" documentation).

2023-09-11 09:05 UTC, pellared commented on content/en/docs/instrumentation/go/getting-started.md
> +This page will show you how to get started with OpenTelemetry in Golang.
The language is called "Go". Not "Golang" 😉

2023-09-11 09:05 UTC, pellared commented on content/en/docs/instrumentation/go/getting-started.md
> +frameworks as well, such as Goframe and Beego.
Can we simply use `net/http`? You can mention that it works for Gin, Gorilla/Mux, Echo etc.

2023-09-11 09:05 UTC, pellared commented on content/en/docs/instrumentation/go/getting-started.md
> +go mod vendor
Vendoring is not needed.

2023-09-11 09:06 UTC, pellared commented
> I will push out again when I resolve automatic instrumentation.

What do you mean? Right now, getting started should work with manual instrumentation.

2023-09-11 16:42 UTC, cartermp commented
So I think we should change this eventually to use autoinstrumentation first, but the main issue is that the Go autoinstrumentation agent is still quite early. I don't know if we should endorse it as the right way to get started today.

2023-09-12 07:12 UTC, pegasas commented
> So I think we should change this eventually to use autoinstrumentation first, but the main issue is that the Go autoinstrumentation agent is still quite early. I don't know if we should endorse it as the right way to get started today.

https://github.com/open-telemetry/opentelemetry-go-instrumentation
Indeed, 
It seems this project is progressing.
Is this the only project which adapted eBPF?

2023-09-12 23:22 UTC, cartermp commented
Yes, for now it is. There may be more in the future though, since the technique could also apply for Rust and C++. But I don't know if there's any motivation on those SIGs to start an autoinstrumentation project.

2023-09-13 06:10 UTC, pellared commented
> Is this the only project which adapted eBPF?

There is also https://github.com/open-telemetry/opentelemetry-ebpf

2023-10-05 18:45 UTC, svrnm commented
@pegasas there is now an updated getting started for go using _manual_ instrumentation. Do you still have interest in writing something about automatic instrumentation or can we close this PR?

2023-10-17 08:22 UTC, pegasas commented
sure. @svrnm .

I close this PR.
I am interested in other items in automatic instrumentation.
If there is any. feel free to assign to me.

2023-10-17 08:22 UTC, closed without merging

2023-10-17 12:42 UTC, svrnm commented
@pegasas my question was around having some section added to the go lang documentation around automatic instrumentation. #3345 is not about Go and not about Automatic instrumentation, can you provide more details?