adding a blog entry for PHP RC
open-telemetry/opentelemetry.io pull request #3259
Opened 2023-09-12 10:29 UTC by brettmc

2023-09-12 13:02 UTC, bobstrecansky approved these changes

2023-09-12 14:50 UTC, svrnm requested changes
this is awesome!

2023-09-12 17:08 UTC, svrnm commented on content/en/blog/2023/php-rc-release.md
> +  Strcansky](https://github.com/bobstrecansky) (Mailchimp)'
```suggestion
  Strecansky](https://github.com/bobstrecansky) (Mailchimp)'
```

2023-09-13 07:09 UTC, svrnm approved these changes

2023-09-13 07:09 UTC, merged