Describe java OTLP exporter options
open-telemetry/opentelemetry.io pull request #3272
Opened 2023-09-14 14:40 UTC by jack-berg

Resolves #3271.

2023-09-14 15:05 UTC, svrnm requested changes
lgtm overall, some minor points regarding cspell & text-lint that need to be fixed

2023-09-14 15:05 UTC, svrnm commented on content/en/docs/instrumentation/java/exporters.md
> +automatically used when it is detected on the classpath. The sender
add `classpath` to the ignore list in line 4

We can later consider to have it added to the global list as well.

2023-09-14 15:05 UTC, svrnm commented on content/en/docs/instrumentation/java/exporters.md
> +- `io.opentelemetry:opentelemetry-exporter-sender-okhttp` - The default sender,
Same here, add `okhttp` to line 4 to ignore it

2023-09-14 15:05 UTC, svrnm commented on content/en/docs/instrumentation/java/exporters.md
> +  requires zero additional dependencies, but requires java 11+. To use, include
```suggestion
  requires zero additional dependencies, but requires Java 11+. To use, include
```

2023-09-14 15:05 UTC, svrnm commented on content/en/docs/instrumentation/java/exporters.md
> +  [grpc transport implementations](https://github.com/grpc/grpc-java#transport).
```suggestion
  [gRPC transport implementations](https://github.com/grpc/grpc-java#transport).
```

2023-09-14 15:21 UTC, cartermp commented on content/en/docs/instrumentation/java/exporters.md
> +implementation, the same exporter classes are used. A sender implementations is
```suggestion
implementation, the same exporter classes are used. A sender implementation is
```

2023-09-14 15:21 UTC, cartermp commented on content/en/docs/instrumentation/java/exporters.md
> +
I think what's missing is an explanation of when I'd want to use a different sender implementation than the default.

2023-09-14 16:05 UTC, cartermp commented on content/en/docs/instrumentation/java/exporters.md
> +
Gotcha. I suppose most java developers who are in this situation will recognize when they need to swap a sender implementation.

2023-09-14 21:25 UTC, cartermp approved these changes

2023-09-15 07:00 UTC, mateuszrzeszutek approved these changes

2023-09-15 08:17 UTC, svrnm approved these changes

2023-09-15 09:36 UTC, merged

2023-09-15 09:36 UTC, svrnm commented
thanks @jack-berg :-)