Complete documentation for peer service mapping
open-telemetry/opentelemetry.io pull request #3428
Opened 2023-10-23 22:34 UTC by mmorel-35

After providing the possibility to override peer.service attribute by host, port and path. This add documentation.

2023-10-23 22:40 UTC, trask approved these changes
thx for following up on the doc!

2023-10-24 07:25 UTC, svrnm requested changes
some minor remarks.

2023-10-24 07:25 UTC, svrnm commented on content/en/docs/instrumentation/java/automatic/agent-config.md
> +Since javaagent version `1.31.0`, it is possible to provide a port and a path to
```suggestion
Since Java agent version `1.31.0`, it is possible to provide a port and a path to
```

2023-10-24 07:25 UTC, svrnm commented on content/en/docs/instrumentation/java/automatic/agent-config.md
> +For example
```suggestion
For example, if set to the following:
```

2023-10-24 07:25 UTC, svrnm commented on content/en/docs/instrumentation/java/automatic/agent-config.md
> +`dogs-api`.
```suggestion
Then, requests to `1.2.3.4` will have no override for `peer.service` attribute,
while `1.2.3.4:443` will have have `peer.service` of `cats-service` and requests
to `dogs-abcdef123.serverlessapis.com:80/api/v1` will have an attribute of
`dogs-api`.
```

2023-10-24 11:14 UTC, svrnm approved these changes

2023-10-25 09:34 UTC, merged