Fix munual instrumentation with Spring Boot app
open-telemetry/opentelemetry.io pull request #3656
Opened 2023-12-07 13:09 UTC by PerfectSlayer

Hi OpenTelemetry team 👋 

Following [a dependency management issue using Java Spring Boot app and Gradle build system](https://github.com/open-telemetry/opentelemetry.io/issues/3613), I updated the _Java Manual Instrumentation_ documentation page.

This PR proposes a fix to https://github.com/open-telemetry/opentelemetry.io/issues/3613 and the rationale for its content (using OTel BOM import rather than removing Spring dependency management pluging) is explained in my comment: https://github.com/open-telemetry/opentelemetry-java/issues/6018#issuecomment-1842561406.

It's my first contribution to this repository so feel free to provide guidance if I miss something. 
I have built the site locally and tested it using `npm run test`. It seemed fine 😇 

>[!NOTE]
> In addition, I updated the highlight sections, fix semconv versions and restore a missing semi-column.

2023-12-11 16:52 UTC, jeanbisutti commented
@PerfectSlayer There are [two ways](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#managing-dependencies) to manage a BOM with Gradle and Spring Boot. Could you please also document the way with the  Gradle’s native bom support (as I did on [this PR](https://github.com/open-telemetry/opentelemetry.io/pull/3672) for the Spring Boot page)?

2023-12-11 16:54 UTC, jeanbisutti commented
@PerfectSlayer Could you also please add documentation on how to configure the things with Maven (as I did on https://github.com/open-telemetry/opentelemetry.io/pull/3672 for the Spring Boot page)?

2023-12-12 08:59 UTC, svrnm requested changes

2023-12-12 08:59 UTC, svrnm commented on content/en/docs/instrumentation/java/manual.md
> +}
```suggestion
dependencyManagement {
    imports {
        mavenBom("io.opentelemetry:opentelemetry-bom:{{% param vers.otel %}}")
    }
}
```

2023-12-12 09:00 UTC, svrnm commented
@open-telemetry/java-approvers PTAL

2023-12-12 09:52 UTC, laurit approved these changes

2023-12-20 08:44 UTC, PerfectSlayer commented
@jeanbisutti Sure, I was waiting for #3672 to be reviewed first.

2023-12-20 10:34 UTC, PerfectSlayer commented
It pushed some changes to reflect BOM documentation from @jeanbisutti 
I also moved a paragraph (_throughout this documentation you will add dependencies.…_) from the Gradle tab below, to be accessible for Maven users too, and removed duplicated maven dependencies to stay consistent (only adding SDK on installing SDK chapter, like autoconfigure).

2023-12-20 12:54 UTC, jeanbisutti approved these changes

2023-12-20 12:54 UTC, jeanbisutti commented on content/en/docs/instrumentation/java/manual.md
> +managemnt plugin, install the OpenTelemetry BOM and API using Gradle depenencies
```suggestion
managemnt plugin, install the OpenTelemetry BOM and API using Gradle dependencies
```

2023-12-20 14:59 UTC, cartermp commented on content/en/docs/instrumentation/java/manual.md
> +managemnt plugin, install the OpenTelemetry BOM and API using Gradle dependencies
```suggestion
management plugin, install the OpenTelemetry BOM and API using Gradle dependencies
```

2023-12-20 15:01 UTC, cartermp commented
@PerfectSlayer if you run `npm run fix:format` then this should be good.

2023-12-20 15:41 UTC, PerfectSlayer commented
@cartermp I run it and amend the commit it fixed.

2023-12-20 16:22 UTC, cartermp commented
@open-telemetry/java-approvers please take a look!

2024-01-04 13:38 UTC, PerfectSlayer commented
Hey there! Happy New Year 🎉 

Coming to check up on things. Is there anything I can do on my side to get this PR progress?

2024-01-04 16:28 UTC, trask commented
we are good to go from the Java SIG side with @laurit and @jeanbisutti's approvals

2024-01-05 02:15 UTC, jack-berg reviewed
Left a handful of comments that aren't necessarily related to the changes @PerfectSlayer makes, but didn't seem right to let them continue to go unnoticed.

2024-01-05 02:15 UTC, jack-berg commented on content/en/docs/instrumentation/java/manual.md
> -artifact coordinates, see [releases]. For semantic convention releases, see
> Throughout this documentation you will add dependencies. For a full list of
artifact coordinates, see [releases].

I like this section near the top - maybe even the first line in the dependency management section. Starting with the bom feels strange without first establishing which artifacts the bom aligns.

2024-01-05 02:15 UTC, jack-berg commented on content/en/docs/instrumentation/java/manual.md
> +in addition to the dependencies for the OpenTelemetry API.
The phrasing here is odd. Your change is fine but I wonder if we should correct it. 

> If you instrument a Java app, install the dependencies for the OpenTelemetry SDK

That's a really poor introduction to the SDK. Maybe something like:

"The OpenTelemetry API provides a set of interfaces for collecting telemetry, but the data is dropped without an implementation. The OpenTelemetry SDK is the implementation of the OpenTelemetry API provided by OpenTelemetry. To use it, begin by installing dependencies:"

2024-01-05 02:15 UTC, jack-berg commented on content/en/docs/instrumentation/java/manual.md
> +    implementation("io.opentelemetry:opentelemetry-semconv:{{% param vers.semconv %}}-alpha");
```suggestion
    implementation("io.opentelemetry.semconv:opentelemetry-semconv:{{% param vers.semconv %}}-alpha");
```
As documented here: https://github.com/open-telemetry/semantic-conventions-java

2024-01-05 02:15 UTC, jack-berg commented on content/en/docs/instrumentation/java/manual.md
> +    implementation("io.opentelemetry:opentelemetry-sdk-metrics");
```suggestion
```
This dependency is redundant.

2024-01-05 02:15 UTC, jack-berg commented on content/en/docs/instrumentation/java/manual.md
>              <artifactId>opentelemetry-sdk</artifactId>
The `opentelemetry-sdk-metrics` dependency below is redundant.

2024-01-05 02:15 UTC, jack-berg commented on content/en/docs/instrumentation/java/manual.md
> +    implementation("io.opentelemetry:opentelemetry-api");
```suggestion
```
I believe your intent is to omit `opentelemetry-api` here since its included above.

2024-01-05 02:15 UTC, jack-berg commented on content/en/docs/instrumentation/java/manual.md
> +    implementation("io.opentelemetry:opentelemetry-sdk-metrics");
```suggestion
```
Redundant

2024-01-05 02:15 UTC, jack-berg commented on content/en/docs/instrumentation/java/manual.md
> +    implementation("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi");
```suggestion
    implementation("io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi");
```
Redundant

2024-01-18 10:05 UTC, svrnm commented
@PerfectSlayer can you take a look at the review comments?

2024-01-18 17:02 UTC, PerfectSlayer commented
Sure will do this tomorrow or next week 👍

2024-01-24 13:06 UTC, zeitlinger commented
> In addition, I updated the highlight sections

what is the intention of the highlights?

2024-01-29 22:34 UTC, chalin reviewed
See inline comment.

This will need to be rebased.

2024-01-29 22:34 UTC, chalin commented on content/en/docs/instrumentation/java/manual.md
> +	  }
Indentation / formatting looks off here.

2024-02-02 12:28 UTC, PerfectSlayer commented on content/en/docs/instrumentation/java/manual.md
> +	  }
Good catch!

2024-02-02 13:02 UTC, PerfectSlayer commented
I rebased the branch and should have taken all the review comments into account.

2024-02-02 13:17 UTC, jeanbisutti commented
LGTM

Thanks a lot @PerfectSlayer!

It would remain the comment from Gregor: https://github.com/open-telemetry/opentelemetry.io/pull/3656#issuecomment-1908086538 @zeitlinger, could you please elaborate a bit your question?

2024-02-05 07:44 UTC, svrnm approved these changes

2024-02-05 07:44 UTC, svrnm commented
@PerfectSlayer can you resolve the conflict?

2024-02-05 07:58 UTC, PerfectSlayer commented
@svrnm I just did using GH Web UI.

2024-02-05 12:42 UTC, svrnm approved these changes

2024-02-05 13:21 UTC, merged