add security incident response process
open-telemetry/opentelemetry.io pull request #3675
Opened 2023-12-11 20:02 UTC by cartersocha

add security incident response process to website - copying over from sig-security

2023-12-11 20:16 UTC, cartersocha commented
@svrnm I can remove the javascript files. That formatter did those changes automatically

2023-12-11 21:09 UTC, chalin requested changes
> @svrnm I can remove the javascript files. That formatter did those changes automatically

@cartersocha - hmm, you must have a custom setup or custom config for Pettier, or maybe you're not using the right version? Maybe try running `npm install` to ensure that you're using the expected version of Prettier. But yes, all other changes should be removed -- otherwise FILE FORMAT will continue to fail.

2023-12-12 08:21 UTC, svrnm requested changes
thanks @cartersocha, I focused on the final that needs the review. Let me know if you need any help to get the unintended changes fixed.

2023-12-12 08:21 UTC, svrnm commented on content/en/docs/security/security-response.md
> +The OpenTelemetry Technical Committee (OTel TC) and relevant repository
```suggestion
The [OpenTelemetry Technical Committee (OTel TC)](https://github.com/open-telemetry/community/blob/main/tech-committee-charter.md) and relevant repository
```

2023-12-12 08:21 UTC, svrnm commented on content/en/docs/security/security-response.md
> +maintainers, supported by tooling provided by the SIG-Security, are responsible
```suggestion
maintainers, supported by tooling provided by the [SIG Security](https://github.com/open-telemetry/sig-security), are responsible
```

2023-12-12 08:21 UTC, svrnm commented on content/en/docs/security/security-response.md
> +processes. SIG-Security in conjunction with the TC can advise in case
```suggestion
processes. SIG Security in conjunction with the TC can advise in case
```

2023-12-12 08:21 UTC, svrnm commented on content/en/docs/security/security-response.md
> +TBD
```suggestion
```

If this is TBD remove it, or provide details

2023-12-13 23:45 UTC, cartersocha commented
Fix everything. Thanks for the feedback and suggestions @svrnm @chalin. Should be ready to go

2023-12-14 07:58 UTC, svrnm commented
> Fix everything. Thanks for the feedback and suggestions @svrnm @chalin. Should be ready to go

Thanks!

Can a second person from @open-telemetry/sig-security-maintainers approve the PR as well? Then we can merge it.

2023-12-14 07:58 UTC, svrnm approved these changes

2023-12-14 09:37 UTC, jpkrohling approved these changes
Just a small suggestion to make it explicit which team to ping.

2023-12-14 09:37 UTC, jpkrohling commented on content/en/docs/security/security-response.md
> +[cncf-opentelemetry-tc@lists.cncf.io](mailto:cncf-opentelemetry-tc@lists.cncf.io)
I wonder if we should have a periodic drill. We could pick one or more random repositories, excluding non-coding ones (oteps, community, semantic-conventions). Something like:

```
gh repo list open-telemetry -l 80 --json name --jq '.[].name' | shuf | head -n 5
opentelemetry-python-contrib
opentelemetry-collector
opentelemetry-rust
opentelemetry-java-examples
opentelemetry-helm-charts
```

2023-12-14 09:37 UTC, jpkrohling commented on content/en/docs/security/security-response.md
> +  [CVSS Calculator](https://www.first.org/cvss/calculator/3.1) and ping the TC
TC GitHub team -> [@open-telemetry/technical-committee](https://github.com/orgs/open-telemetry/teams/technical-committee)

2023-12-14 09:37 UTC, jpkrohling commented on content/en/docs/security/security-response.md
> +- The Fix Team will ping the TC GitHub team to alert them that work on the fix
```suggestion
- The Fix Team will ping [@open-telemetry/technical-committee](https://github.com/orgs/open-telemetry/teams/technical-committee) to alert them that work on the fix
```

2023-12-16 15:44 UTC, cartermp commented
@cartersocha this looks good overall. If you can address the bits from @jpkrohling then I think we can merge this.

2023-12-16 20:27 UTC, cartersocha commented
done @cartermp

2023-12-16 23:29 UTC, merged