feat: add outreachy blog in otel blogs
open-telemetry/opentelemetry.io pull request #3710
Opened 2023-12-24 08:35 UTC by sakshi-1505

Outreachy blog inspired from https://sakshipatle.substack.com/p/outreachy-how-when-and-why

2023-12-24 08:36 UTC, sakshi-1505 commented
@svrnm I will make draft:false once the PR gets approved

2024-01-08 09:27 UTC, svrnm requested changes
Adding the slack thread for context: https://cloud-native.slack.com/archives/C05A85QC281/p1702464743038639?thread_ts=1702464110.897059&cid=C05A85QC281

Thank you @sakshi-1505, I did a first run of reviews, please take a look

2024-01-08 09:27 UTC, svrnm commented on content/en/blog/2023/outreachy-how-why-sakshi.md
> +student at RGPV in the heart of India. My journey into the tech universe has
```suggestion
student at RGPV in the heart of India. My journey into the tech universe has
```

What does RGPV stand for? Write it out and then put the abbreviation in (...)

2024-01-08 09:27 UTC, svrnm commented on content/en/blog/2023/outreachy-how-why-sakshi.md
> +# canonical_url: http://somewhere.else/ # TODO: if this blog post has been posted somewhere else already, uncomment & provide the canonical URL here.
you can add a pointer to your medium post here.

2024-01-08 09:27 UTC, svrnm commented on content/en/blog/2023/outreachy-how-why-sakshi.md
> +draft: true # TODO: remove this line once your post is ready to be published
```suggestion
```

2024-01-08 09:27 UTC, svrnm commented on content/en/blog/2023/outreachy-how-why-sakshi.md
> +linkTitle: Introduction to Outreachy 2023 # Mandatory, make sure that your short title.
```suggestion
linkTitle: Introduction to Outreachy 2023 # Mandatory, make sure that your short title.
```

The linkTitle should be short and only a few words, like "Outreachy Internship" or "Outreachy Report", etc.

2024-01-08 09:27 UTC, svrnm commented on content/en/blog/2023/outreachy-how-why-sakshi.md
> +Outreachy for me was not just a program; it represented the intersection of my
```suggestion
[Outreachy](https://www.outreachy.org/) for me was not just a program; it represented the intersection of my
```

2024-01-08 09:27 UTC, svrnm commented on content/en/blog/2023/outreachy-how-why-sakshi.md
> +are not just focused on but are thriving. As an intern with the SIG Security
```suggestion
are not just focused on but are thriving. As an intern with the [SIG Security](https://github.com/open-telemetry/sig-security)
```

2024-01-08 09:27 UTC, svrnm commented on content/en/blog/2023/outreachy-how-why-sakshi.md
> +governance policies and checks. This isn’t just about enforcing standards; it’s
```suggestion
team, I’ll be championing the implementation of organization-wide repository
governance policies and checks. This isn’t just about enforcing standards; it’s
```

is there a GitHub issue that you can link from here? Do you want to mention AllStar somewhere?

2024-01-08 09:27 UTC, svrnm commented on content/en/blog/2023/outreachy-how-why-sakshi.md
> +
TODO for me: As discussed I will add a leading paragraph

2024-01-11 14:29 UTC, svrnm commented
@sakshi-1505 I added some words as introduction and did some editing of the content, please take a look if everything is correct (e.g. I assumed that RGPV is Rajiv Gandhi Proudyogiki Vishwavidyalaya, please correct this if I am incorrect)

2024-01-17 10:35 UTC, svrnm approved these changes

2024-01-17 10:36 UTC, svrnm commented
Preview: https://deploy-preview-3710--opentelemetry.netlify.app/blog/2024/outreachy-how-why-sakshi/

@jpkrohling can you take a quick look as well, thx!

2024-01-17 10:47 UTC, jpkrohling approved these changes

2024-01-17 10:49 UTC, svrnm commented on content/en/blog/2024/outreachy-how-why-sakshi.md
> +date: 2024-01-12
```suggestion
date: 2024-01-17
```

2024-01-17 10:54 UTC, merged