add more examples link
open-telemetry/opentelemetry.io pull request #3712
Opened 2023-12-26 07:14 UTC by runtu666

2024-01-08 08:56 UTC, theletterf requested changes

2024-01-08 08:56 UTC, theletterf commented on content/en/docs/instrumentation/php/automatic.md
> +You can find more examples and documents here [PHP examples](https://github.com/open-telemetry/opentelemetry-php-contrib)
```suggestion
## Examples

You can find more examples in the [opentelemetry-php-contrib](https://github.com/open-telemetry/opentelemetry-php-contrib) repository.
```

2024-01-08 08:56 UTC, theletterf commented
Thanks! Made a suggestion.

2024-01-08 11:33 UTC, brettmc approved these changes

2024-01-08 13:50 UTC, svrnm commented
thanks @runtu666 , please fix the linter issues.

Run npx gulp lint-md and npm run fix:format for that

2024-01-08 23:24 UTC, chalin requested changes

2024-01-08 23:24 UTC, chalin commented on content/en/docs/instrumentation/php/automatic.md
> +You can find more examples in the [opentelemetry-php-contrib](https://github.com/open-telemetry/opentelemetry-php-contrib) repository.
Hmm, it doesn't make sense to have a section head after "Next steps" IMHO, how about just adding the sentence to the existing last section, something like this:

```suggestion

For more examples, see
[opentelemetry-php-contrib/examples](https://github.com/open-telemetry/opentelemetry-php-contrib/tree/main/examples).
```

2024-01-10 08:42 UTC, runtu666 commented
> thanks @runtu666 , please fix the linter issues.
> 
> Run npx gulp lint-md and npm run fix:format for that

done @svrnm

2024-01-11 00:09 UTC, chalin approved these changes
👍🏻

2024-01-11 08:47 UTC, svrnm commented
@theletterf please re-review if your changes have been applied and you're satisfied now

2024-01-11 09:42 UTC, theletterf approved these changes

2024-01-11 09:52 UTC, merged