add openobserve
open-telemetry/opentelemetry.io pull request #3724
Opened 2024-01-05 04:58 UTC by prabhatsharma

## Docs PR Checklist

- [ x] This PR is for a documentation page whose authoritative copy is in the
      opentelemetry.io repository.

2024-01-05 06:51 UTC, svrnm requested changes

2024-01-05 06:51 UTC, svrnm commented on data/ecosystem/vendors.yaml
> +  contact: ''
Please provide a contact, we use this to get in touch in case of changes or issues. A GitHub handle to tag is ideal, email is also possible

2024-01-05 06:51 UTC, svrnm commented on data/ecosystem/vendors.yaml
> +  url: 'https://openobserve.ai'
Please link to your documentation where users can learn how they can use openobserve with OTLP

2024-01-08 09:36 UTC, svrnm approved these changes

2024-01-08 09:38 UTC, svrnm commented
/fix:refcache

2024-01-08 09:58 UTC, svrnm commented
@prabhatsharma unfortunately I can not fix the refcache issue since I can not push those changes to your fork, please run `npm run test-and-fix` locally and push the changes.

As a general advice, please do not use organizational forks, as they come with restricted permissions for maintainers and are a headache for working on PRs.

2024-01-08 10:30 UTC, prabhatsharma commented
> @prabhatsharma unfortunately I can not fix the refcache issue since I can not push those changes to your fork, please run `npm run test-and-fix` locally and push the changes.

I tried running `npm run test-and-fix` but ran into errors around font-awesome. Let me close this PR and create another one from a non-org fork.

> As a general advice, please do not use organizational forks, as they come with restricted permissions for maintainers and are a headache for working on PRs.

Ah, got it. good to know.

2024-01-08 10:30 UTC, closed without merging