Clarify when to use the OTel starter
open-telemetry/opentelemetry.io pull request #3731
Opened 2024-01-08 11:34 UTC by jeanbisutti

cc @open-telemetry/java-instrumentation-approvers @zeitlinger

2024-01-08 11:43 UTC, theletterf requested changes

2024-01-08 11:43 UTC, theletterf commented on content/en/docs/instrumentation/java/automatic/spring-boot.md
> +## How to instrument a Spring Boot application
I feel the title here is redundant. You can eliminate it and use the doc title (or, better yet, rewrite the description).

2024-01-08 11:43 UTC, theletterf commented on content/en/docs/instrumentation/java/automatic/spring-boot.md
> +OpenTelemetry [Spring Boot starter] allows you to instrument your code.
```suggestion
The [OpenTelemetry Java agent](..) with byte code instrumentation can cover
most of your needs when instrumenting [Spring Boot](https://spring.io/projects/spring-boot)
applications.

You can't use the OpenTelemetry Java agent with Spring Boot Native image applications, but you
still can instrument your code using OpenTelemetry [Spring Boot starter].
```

2024-01-08 11:43 UTC, theletterf commented on content/en/docs/instrumentation/java/automatic/spring-boot.md
> +A third situation in which the OpenTelemetry starter can help you is when the start-up overhead of the OpenTelemetry Java agent is too important for you.
```suggestion
The
[opentelemetry-java-examples/spring-native](https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/spring-native)
repository contains an example of a Spring Boot Native image application instrumented using
the OpenTelemetry Spring Boot starter.

If your application already uses a Java agent, the OpenTelemetry Java agent might not work. In this case,
use the OpenTelemetry starter.

A third situation in which the OpenTelemetry starter can help you is when the startup overhead of the OpenTelemetry Java agent exceeds your requirements.
```

2024-01-08 11:51 UTC, theletterf approved these changes
Thanks!

2024-01-09 09:54 UTC, svrnm commented
@open-telemetry/java-approvers PTAL

2024-01-09 09:55 UTC, theletterf commented
/fix:format

2024-01-09 23:00 UTC, trask commented on content/en/docs/instrumentation/java/automatic/spring-boot.md
> +startup overhead of the OpenTelemetry Java agent exceeds your requirements.
(also I'd suggest bumping this up to reason 2)

```suggestion
A third situation in which the OpenTelemetry starter can help you is if the
startup overhead of the OpenTelemetry Java agent exceeds your requirements.
```

2024-01-10 16:05 UTC, trask commented on content/en/docs/instrumentation/java/automatic/spring-boot.md
> +might not work. In this case, use the OpenTelemetry starter.
what do you think of making these 3 bullets? I think it might give this section a bit of helpful structure for readers

2024-01-10 16:36 UTC, trask approved these changes

2024-01-10 16:37 UTC, jeanbisutti commented
/fix:format

2024-01-10 16:44 UTC, jeanbisutti commented
@theletterf @svrnm  Could you please have a look a the last version? It was approved by Trask "on behalf of https://github.com/orgs/open-telemetry/teams/java-approvers and https://github.com/orgs/open-telemetry/teams/java-instrumentation-approvers"

2024-01-11 11:03 UTC, merged