Collector quick start
open-telemetry/opentelemetry.io pull request #3787
Opened 2024-01-16 14:47 UTC by chalin

This is a proposal to rename & slightly rework/refactor the Collector "getting started":

- Renames the Collector **Getting started** to **Quick start**, since that is more what the page actually is.
- Clarifies prerequisites
- Slightly reorders commands
- Offers some way to filter output, because otherwise it can be difficult to, e.g., find Span output because the Collector output is very busy
- Renames the page appropriately and adds an alias to handle redirects

Thoughts @svrnm @theletterf et al.?

---

**Preview & redirect test**:

- https://deploy-preview-3784--opentelemetry.netlify.app/docs/collector/quick-start/
- https://deploy-preview-3784--opentelemetry.netlify.app/docs/collector/getting-started

2024-01-16 15:20 UTC, theletterf requested changes
Nice! I like the changes. Sent some suggestions to reword things in line with our style recommendations.

2024-01-16 15:20 UTC, theletterf commented on content/en/docs/collector/quick-start.md
> +preferred shell.
```suggestion
Make sure that your developer environment has the following. This page assumes that
you're using `bash`. Adapt configuration and commands as necessary for your
preferred shell.
```

2024-01-16 15:20 UTC, theletterf commented on content/en/docs/collector/quick-start.md
> +- [`GOBIN` environment variable][gobin] is set; if not initialize it
```suggestion
- [`GOBIN` environment variable][gobin] is set; if unset, initialize it
```

2024-01-16 15:20 UTC, theletterf commented on content/en/docs/collector/quick-start.md
> +## Set up
```suggestion
## Set up the environment
```

2024-01-16 15:20 UTC, theletterf commented on content/en/docs/collector/quick-start.md
> +   ingest activity similar to what is shown below:
```suggestion
   ingest activity similar to what is shown in the following example:
```

2024-01-16 15:20 UTC, theletterf commented on content/en/docs/collector/quick-start.md
> +7. Once you are done, shutdown the Collector container, for example, using
```suggestion
7. After you are done, shutdown the Collector container, for example, using
```

2024-01-16 15:20 UTC, theletterf commented on content/en/docs/collector/quick-start.md
> +In this page you'll learn how to do the following in less than five minutes:
```suggestion
You are going to learn to do the following in less than five minutes: 
```

2024-01-16 15:44 UTC, svrnm commented
works for me, if @theletterf is happy with the changes, I am happy to merge it

2024-01-16 19:16 UTC, chalin commented
Thanks all for the feedback, and for the careful review @theletterf. I've accepted all of your suggestions. Let me fix the formatting issues, etc. and then PTAL.

2024-01-17 07:27 UTC, theletterf approved these changes
Thanks so much! Approved!

2024-01-17 08:46 UTC, svrnm commented
@open-telemetry/collector-approvers PTAL!

2024-01-29 11:07 UTC, svrnm commented
@open-telemetry/collector-approvers PTAL!

2024-01-29 12:38 UTC, mx-psi approved these changes

2024-01-29 13:02 UTC, svrnm commented
/fix:refcache

2024-01-29 13:08 UTC, merged