Edits to follow up contribution guidelines work
open-telemetry/opentelemetry.io pull request #3846
Opened 2024-01-23 09:54 UTC by theletterf

This PR consolidates contribution docs further and erases the hidden `contribution-guidelines` doc, which was redundant.

- Fixes #3767 
- Fixes #897

2024-01-23 09:56 UTC, theletterf commented
@svrnm @chalin Did the mirrored documentation guidelines change / were removed? I don't think we've them in prod: https://github.com/open-telemetry/opentelemetry.io/commit/7c1dcce3344b33cf1f1877a3a08ae3e8f4ef3d0e

Can't trace when/where they were removed. I take they no longer apply, as we use a more generic language in our new contribution guide. As they were still linked from contribution-guidelines I was wondering.

2024-01-23 11:34 UTC, svrnm approved these changes
lgtm, but I'd like to also get @chalin's approval

2024-01-29 16:29 UTC, chalin approved these changes
One suggested tweak, otherwise LGTM overall :)

2024-01-29 16:29 UTC, chalin commented on .htmltest.yml
> +  - /docs/contribution-guidelines/
Ah, if you modify the community list shortcode, then you don't need to ignore the path anymore:

```suggestion
```

2024-01-29 16:44 UTC, chalin requested changes
Oh! We need to add an alias for the page that was removed.

2024-01-29 21:18 UTC, chalin commented
> @svrnm @chalin Did the mirrored documentation guidelines change / were removed? I don't think we've them in prod: [7c1dcce](https://github.com/open-telemetry/opentelemetry.io/commit/7c1dcce3344b33cf1f1877a3a08ae3e8f4ef3d0e)

Those guidelines no longer apply.

For context, see:

- #833
- #730

2024-01-29 21:19 UTC, chalin commented
> Also, do we want to promote the newly created https://github.com/open-telemetry/opentelemetry.io/discussions board? I'd wait a bit before doing so, perhaps...

I'm ok with waiting a bit too.

2024-01-30 09:48 UTC, theletterf commented
@chalin Changes applied, thanks!

The alias is already here I think? https://github.com/open-telemetry/opentelemetry.io/pull/3846/files#diff-a3d923889a7028820da3c39a743bd702eb33e7333b64009b1384d444c7a1561aL4

2024-01-30 10:06 UTC, chalin commented
> @chalin Changes applied, thanks!

👍 

> The alias is already here I think? https://github.com/open-telemetry/opentelemetry.io/pull/3846/files#diff-a3d923889a7028820da3c39a743bd702eb33e7333b64009b1384d444c7a1561aL4

Yes! 👍🏻

2024-01-30 10:07 UTC, chalin approved these changes
👍🏻

2024-01-30 11:02 UTC, merged