Replace or add loopback address in Collector OTLP examples
open-telemetry/opentelemetry.io pull request #3847
Opened 2024-01-23 10:42 UTC by theletterf

Fixes #3839 

To check:

- Do we want to add a comment to all YAML edits? What should it say?
- Do we need to change this in instrumentation settings examples?
- Do we need to change `localhost` to `0.0.0.0` elsewhere in Collector configs?

2024-01-23 11:19 UTC, svrnm commented on content/en/docs/collector/building/receiver.md
> +    endpoint: 0.0.0.0:14317
I think this only needs to be changed for receivers

2024-01-23 11:20 UTC, svrnm commented on content/en/docs/collector/building/receiver.md
> +    endpoint: 0.0.0.0:14317
same here, I think this only needs to be changed for receivers

2024-01-23 11:21 UTC, svrnm commented
If I understand the issue correctly this is _only_ for receivers

2024-01-23 11:27 UTC, mx-psi commented
This is only on servers exposed by the OpenTelemetry Collector (the vast majority of which are receivers, we also have a couple extensions that may be featured in the docs). The intent is to mitigate https://cwe.mitre.org/data/definitions/1327.html

2024-01-23 11:43 UTC, theletterf commented
@svrnm @mx-psi I reverted all changes applied to things that are not receivers. Other than OTLP addresses I couldn't find other instances of receiver listening on localhost in the Collector docs.

I'm also unsure about adding a long note at all. I think this change can be transparent until the new standard comes into effect.

2024-01-25 09:28 UTC, svrnm commented on content/en/docs/collector/configuration.md
> +            - targets: [0.0.0.0:8888]
I think this should be reverted as well since this is a scrapping info (pull, not push)

2024-01-25 09:28 UTC, svrnm commented on content/en/docs/collector/configuration.md
> +    issuer_url: http://0.0.0.0:8080/auth/realms/opentelemetry
this should also remain localhost,

2024-01-25 09:29 UTC, svrnm commented on content/en/docs/collector/configuration.md
> +    token_url: http://0.0.0.0:8080/auth/realms/opentelemetry/protocol/openid-connect/token
this one should remain localhost

2024-01-25 09:29 UTC, svrnm commented on content/en/docs/demo/architecture.md
> +            oc-http[/"OTLP Receiver<br/>listening on <br/>http://0.0.0.0:4318/<br/>https://0.0.0.0:4318/"/]
I am not sure if the demo is changing anything here? Keep it as is

2024-01-25 09:34 UTC, svrnm commented
> I'm also unsure about adding a long note at all. I think this change can be transparent until the new standard comes into effect.

My suggestion is that we have something like this:

```
  otlp:
    protocols:
      grpc:
        # This will tell the collector to listen on all interfaces & addresses, 
        # make sure that you set this configuration to the value that is appropriate for your environment
        endpoint: 0.0.0.0:4317
```

2024-01-25 15:25 UTC, theletterf commented
@svrnm I've reverted the changes you pointed out as wrong and added a compact note to the rest. PTAL

2024-01-26 11:31 UTC, svrnm reviewed
a few more things to fix, but overall LGTM

2024-01-26 11:31 UTC, svrnm commented on content/en/docs/faas/lambda-collector.md
>          endpoint: 'localhost:4318'
is this still localhost on purpose?

2024-01-26 11:31 UTC, svrnm commented on content/en/docs/faas/lambda-collector.md
>          endpoint: 'localhost:4318'
same question here

2024-01-26 11:31 UTC, svrnm commented on content/en/docs/kubernetes/helm/collector.md
> +        # appropriate value for your environment.
```suggestion
```

I don't think this is needed here

2024-01-26 11:31 UTC, svrnm commented on content/en/docs/kubernetes/helm/collector.md
> +        # appropriate value for your environment.
```suggestion
```

I don't think this is needed here

2024-01-26 14:58 UTC, mx-psi commented on content/en/docs/kubernetes/operator/_index.md
>            http:
I guess we should also add this endpoint

2024-01-30 09:33 UTC, theletterf commented on content/en/docs/faas/lambda-collector.md
>          endpoint: 'localhost:4318'
Fixed!

2024-01-30 09:33 UTC, theletterf commented on content/en/docs/faas/lambda-collector.md
>          endpoint: 'localhost:4318'
Fixed!

2024-01-30 09:35 UTC, theletterf commented
Comments addressed! PTAL

2024-01-30 14:48 UTC, chalin requested changes
Oh, mi shivers! Can we find a way to avoid the repetition and keep things DRYer? E.g., add an anchored notes somewhere in the docs and link to it from the YAML excerpts. WDYT?

2024-01-30 15:01 UTC, theletterf commented
@chalin You're right, it's ugly and un-DRY. I suggested that we don't add the note at all, since it adds cruft that might be hard to maintain later. If we end up adding a Security doc to the Collector, that could be a home for this kind of recommendation. Troubleshooting could also be a good home.

As of now, I'd rather remove the note altogether, as it doesn't really hint at the security issue brought up by @mx-psi nor provides more information on what's appropriate. @svrnm WDYT?

2024-01-30 15:27 UTC, mx-psi commented
I am okay with removing the note for now, I think the important part is that we set the endpoints explicitly so that fewer people face a breaking change when we do this

2024-01-30 20:19 UTC, theletterf commented
@chalin @svrnm @mx-psi I've eliminated the note. LMK if this one is good to go -- thanks!

2024-01-30 23:17 UTC, chalin commented on content/en/docs/collector/scaling.md
> +            endpoint: 0.0.0.0:4317
```suggestion
            endpoint: 0.0.0.0:4317
```

2024-01-30 23:31 UTC, chalin commented
@mx-psi @theletterf @svrnm - my suggestion is to at least **add at least one note** in the **Collector config page**, something like this:

> #### :warning: **Important**
> While it is generally preferable to bind endpoints to `localhost` when all
> clients are local, our example configurations use the "unspecified" address
> `0.0.0.0` as a convenience. The Collector currently defaults to `0.0.0.0`, but
> the default will be changed to `localhost` in the near future. For details
> concerning either of these choices as endpoint configuration value, see
> [Safeguards against denial of service attacks].
> 
> [Safeguards against denial of service attacks]:
>   https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

It might appear in the Collector config page just before the first endpoint config using `0.0.0.0`, like this:

> <img width="996" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/14e8efe5-ad68-48e3-ac33-943331ff8fc2">

WDYT?

If you agree (possibly modulo some prose tweaks), let me know and I'll push a commit to this PR with this addition.

2024-01-31 09:58 UTC, mx-psi commented
Makes sense to me :+1: As I said above, fine for me to leave this to a different PR, but also fine to keep it here if okay with others :)

2024-01-31 09:58 UTC, theletterf commented
@chalin I echo @mx-psi. If you'd add the note with that same wording, that'd work for me.

2024-01-31 10:18 UTC, chalin commented
> @chalin I echo @mx-psi. If you'd add the note with that same wording, that'd work for me.

Added, see https://deploy-preview-3847--opentelemetry.netlify.app/docs/collector/configuration/#endpoint-0.0.0.0-warning.

2024-01-31 10:19 UTC, chalin approved these changes
If y'all agree with the added note, then the rest LGTM ✨

2024-01-31 10:22 UTC, theletterf commented
@chalin LGTM! Let's roll!

2024-01-31 10:42 UTC, swiatekm-sumo approved these changes
:+1: on the operator examples.

2024-01-31 10:59 UTC, svrnm approved these changes

2024-01-31 10:59 UTC, svrnm commented
awesome, this looks really good now. @mx-psi if you are happy as well we can merge :-)

2024-01-31 11:26 UTC, mx-psi approved these changes
Looks good to me! :)

2024-01-31 15:04 UTC, merged