Move the Spring Auto-Configuration doc
open-telemetry/opentelemetry.io pull request #3900
Opened 2024-01-31 01:41 UTC by jaydeluca

(Continuation from #3758 after making a mistake rebasing)

Related to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10083

Move and adapt the documentation Readme: [main/instrumentation/spring/spring-boot-autoconfigure/README.md](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md)

--------

after rebasing I am now getting the following textlint errors:

```
  159:23  ✓ error  Incorrect usage of the term: “auto configuration”, use “autoconfiguration” instead    terminology
  172:6   ✓ error  Incorrect usage of the term: “auto-configuration”, use “autoconfiguration” instead    terminology
  238:1   ✓ error  Incorrect usage of the term: “Auto-configures”, use “Autoconfigures” instead          terminology
  251:17  ✓ error  Incorrect usage of the term: “Auto Configuration”, use “autoConfiguration” instead    terminology
  262:21  ✓ error  Incorrect usage of the term: “Auto Configuration”, use “autoConfiguration” instead    terminology
  273:21  ✓ error  Incorrect usage of the term: “Auto Configuration”, use “autoConfiguration” instead    terminology
  275:10  ✓ error  Incorrect usage of the term: “auto-configurations”, use “autoconfigurations” instead  terminology
  278:6   ✓ error  Incorrect usage of the term: “auto-configuration”, use “autoconfiguration” instead    terminology
  486:1   ✓ error  Incorrect usage of the term: “Auto-configuration”, use “Autoconfiguration” instead    terminology
  507:37  ✓ error  Incorrect usage of the term: “auto-configuration”, use “autoconfiguration” instead    terminology
```

"Auto-configuration" is how it is referred to in the [spring boot docs](https://docs.spring.io/spring-boot/docs/2.0.x/reference/html/using-boot-auto-configuration.html) so I am hesitant to just go and update everything to "autoconfiguration" without checking first. Do you know how I should proceed?

2024-01-31 04:55 UTC, trask commented
I think ok to go ahead and change them. We have similar linting in Microsoft docs that always gets me with auto-instrumentation --> autoinstrumentation.

2024-01-31 09:17 UTC, jeanbisutti commented
@jaydeluca I see #3903 that seems to fix the spelling issues.

2024-01-31 09:34 UTC, chalin commented
> @jaydeluca I see #3903 that seems to fix the spelling issues.

Actually, after #3903 lands, you'll be able to fix the spelling issue automatically using this command:

```console
$ npm run check:text -- --fix
```

(You can run that command already, but you'll need to tweak a few instances of the rewritten words.)

2024-01-31 10:02 UTC, chalin reviewed
We're getting closer! See inline for copyedits.

2024-01-31 10:11 UTC, chalin requested changes
Regarding the **organisation / structure of this page**. If you look at the TOC currently, it looks like this:

<img width="231" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/d18cf264-b64a-49b6-8a73-fc09a2cc32f9">

That doesn't make sense to me to have a single top-level heading with pretty much all of the page content under that single heading. As mentioned at the start of this page "this page documents the OpenTelemetry starter" so I think that we should:

- Change the page title to "Spring Boot Starter", to match the actual content of the page
- The heading "OpenTelemetry Spring starter" should be dropped
- All other headings should be promoted one level up.

2024-01-31 10:11 UTC, chalin commented on content/en/docs/languages/java/automatic/spring-boot.md
>  linkTitle: Spring Boot
Change the title to `Spring Boot Starter`, but keep the linkTitle as is.

2024-01-31 10:11 UTC, chalin commented on content/en/docs/languages/java/automatic/spring-boot.md
>  ## OpenTelemetry Spring starter
```suggestion
```

2024-01-31 10:11 UTC, chalin commented on content/en/docs/languages/java/automatic/spring-boot.md
> +### Dependency management
Promote all headings by one level in this page, e.g.:

```suggestion
## Dependency management
```

2024-01-31 10:44 UTC, jeanbisutti commented
> Regarding the **organisation / structure of this page**. If you look at the TOC currently, it looks like this:
> 
> <img alt="image" width="231" src="https://private-user-images.githubusercontent.com/4140793/301120892-d18cf264-b64a-49b6-8a73-fc09a2cc32f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTc0MzAsIm5iZiI6MTcwNjY5NzEzMCwicGF0aCI6Ii80MTQwNzkzLzMwMTEyMDg5Mi1kMThjZjI2NC1iNjRhLTQ5YjYtOGE3My1mYzA5YTJjYzMyZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTAzMjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDU0YTkyYzNjMDY4ZTZjZmZiOTgxMzc1NDEwNWM4MDYyMzQ1ZDA1MzA3MWQ5NWZhOTNiZjNmODAzMmE0YTM5OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ndU60rA6cO6TJXYmaJ_00OdMxr24xsfU-qUCryea-0c">
> That doesn't make sense to me to have a single top-level heading with pretty much all of the page content under that single heading. As mentioned at the start of this page "this page documents the OpenTelemetry starter" so I think that we should:
> 
> * Change the page title to "Spring Boot Starter", to match the actual content of the page
> * The heading "OpenTelemetry Spring starter" should be dropped
> * All other headings should be promoted one level up.

@chalin There is a mistake. Thanks for having pointed this. `Other configurations` should be a top level heading.

It may have another topic. The Spring Boot page should probably only contain this section explaining when to use the Java agent or the starter: 
![image](https://github.com/open-telemetry/opentelemetry.io/assets/14811066/96bbabb8-7e64-49bb-bfa3-c903d4c9d136)

The rest of the page could propably move to another one related to starters and autoconfigurations. Perhaps it could be done in another PR? I could take care of it.

2024-01-31 10:58 UTC, chalin commented
> The rest of the page could propably move to another one related to starters and autoconfigurations. Perhaps it could be done in another PR? I could take care of it.

SGTM, and I'm ok with approaching this incrementally. Please create an issue to track the required changes: you can simply create a new issue from https://github.com/open-telemetry/opentelemetry.io/pull/3900#issuecomment-1918850387.

I'll wait for my other comments to be addressed before making a (final) review pass. Thanks!

2024-01-31 15:31 UTC, jeanbisutti commented
> Please create an issue to track the required changes: you can simply create a new issue from [#3900 (comment)](https://github.com/open-telemetry/opentelemetry.io/pull/3900#issuecomment-1918850387).

Done: https://github.com/open-telemetry/opentelemetry.io/issues/3911

2024-01-31 23:02 UTC, jaydeluca commented
I really appreciate all the help from ya'll 🙏

2024-02-01 10:09 UTC, jeanbisutti approved these changes

2024-02-01 12:37 UTC, chalin approved these changes
❤️ 

So, @jeanbisutti, this actually closes #3911?

2024-02-01 12:40 UTC, chalin commented on content/en/docs/languages/java/automatic/spring-boot.md
> +cSpell:ignore: autoconfigurations autoconfigures Autoconfigures datasource logback springboot webflux webmvc
```suggestion
cSpell:ignore: autoconfigurations autoconfigures datasource logback springboot webflux webmvc
```

2024-02-01 12:49 UTC, jeanbisutti commented
> ❤️
> 
> So, @jeanbisutti, this actually closes #3911?

@chalin It does not close #3911. All the non-agent doc is still in the Spring Boot page.

2024-02-01 13:11 UTC, jeanbisutti commented
@open-telemetry/docs-approvers FYI, the Spring Boot page documents instrumentation features for Spring Boot and developed in the https://github.com/open-telemetry/opentelemetry-java-instrumentation repository.

2024-02-01 18:13 UTC, trask commented
> @open-telemetry/java-approvers PTAL

fyi @jeanbisutti is in @open-telemetry/java-instrumentation-approvers now

2024-02-01 20:55 UTC, cartermp commented
Aaaaand we're in!

2024-02-01 20:55 UTC, merged

2024-02-01 21:42 UTC, trask commented
thx @jaydeluca ❤️