Add Caution Note re Experimental SemConvs
open-telemetry/opentelemetry.io pull request #3995
Opened 2024-02-13 23:14 UTC by mattmccleary

Following up on Slack Chat:
https://cloud-native.slack.com/archives/C041APFBYQP/p1707760677044609

2024-02-13 23:54 UTC, chalin reviewed
@mattmccleary - FYI, I've added an `alert` closing tag so that this change will at least build.

2024-02-14 08:39 UTC, svrnm approved these changes

2024-02-14 08:40 UTC, svrnm commented
thanks @mattmccleary, this is an important call out. I think we will need to have it at a few other places as well for people to see and recognize it. But we can fix this as a follow up (we can turn your segment into a shortcode and put it at places where we think it is required)

2024-02-14 08:40 UTC, svrnm commented
/fix:format

2024-02-14 09:57 UTC, svrnm commented on content/en/docs/languages/_index.md
> +stable, changes to underlying [semantic conventions][SemConv] can interrupt your
```suggestion
stable, changes to underlying [semantic conventions][sem-conv] can interrupt your
```
Not sure why this is not rendering in hugo (see preview: https://deploy-preview-3995--opentelemetry.netlify.app/docs/languages/), maybe those tags have to be lower case, @chalin ?

2024-02-14 09:57 UTC, svrnm commented on content/en/docs/languages/_index.md
> +[SemConv]: /docs/concepts/semantic-conventions/
```suggestion
[sem-conv]: /docs/concepts/semantic-conventions/
```

2024-02-14 18:58 UTC, chalin commented
Wrapping something up, will get back to this PR soon -- I have some extra comments beyond the markdown link reference issue.

2024-02-15 00:00 UTC, jsuereth approved these changes

2024-02-15 09:17 UTC, svrnm commented
> Wrapping something up, will get back to this PR soon -- I have some extra comments beyond the markdown link reference issue.

Sure, then let's not merge this before you follow up!

2024-02-15 17:10 UTC, chalin requested changes
I've pushed a fix to the alert link-ref issue. The solution is to have the markdown link definition be placed inside the shortcode.

I've also moved the note to be before the table. It makes more sense to me that way.

All that being said, I'd like to suggest that we rework the note prose and/or the opening statement "The current status of the major functional components for OpenTelemetry is as follows", so that it is clear that we're talking about the same/related things.

That is, now I'm wondering what the status table is actually giving the status of. Can we make that clearer?

2024-02-15 19:02 UTC, mattmccleary commented
> I've pushed a fix to the alert link-ref issue. The solution is to have the markdown link definition be placed inside the shortcode.
> 
> I've also moved the note to be before the table. It makes more sense to me that way.
> 
> All that being said, I'd like to suggest that we rework the note prose and/or the opening statement "The current status of the major functional components for OpenTelemetry is as follows", so that it is clear that we're talking about the same/related things.
> 
> That is, now I'm wondering what the status table is actually giving the status of. Can we make that clearer?

I agree the table isn't clear, though the title of the page is "Language APIs & SDKs" so I inferred it's a composite of API and SDK. In the future, the table could be reworked to include semantic conventions but that would require some thought because it could quickly blow up the size. Since it's not clear to me how to improve the situation, I'm wondering if this could be a non-blocking follow-on item. I'm happy to think on it some more.

2024-02-16 00:19 UTC, chalin commented
I'd be generally in agreement with what you propose. I might want to tweak the text a bit though -- let me sleep on it :).

2024-02-16 08:57 UTC, svrnm commented
I agree that the table with the status per language needs to be improved, but this should not be a concern for this PR. I'll raise a follow up issue since I also have a few ideas here

2024-02-16 18:36 UTC, chalin reviewed
PTAL at the reworked note.

2024-02-16 18:36 UTC, chalin commented on content/en/docs/languages/_index.md
> +{{% /alert %}}
```suggestion
{{% alert title="Important" color="warning" %}}

Regardless of an API/SDK's status, if your instrumentation relies on [semantic
conventions] that are marked as [Experimental] in the [semantic conventions
specification], your data flow might be subject to **breaking changes**.

[semantic conventions]: /docs/concepts/semantic-conventions/
[Experimental]: /docs/specs/otel/document-status/
[semantic conventions specification]: /docs/specs/semconv/

{{% /alert %}}
```

2024-02-16 22:16 UTC, chalin approved these changes
👍🏻

2024-02-16 22:24 UTC, chalin commented
Merging. I'll let @svrnm followup with the issue / proposed rework he mentioned.

2024-02-16 22:24 UTC, merged