Include Timescale as adopter
open-telemetry/opentelemetry.io pull request #4121
Opened 2024-03-11 09:16 UTC by adolsalamanca

Just saw @jpkrohling LinkedIn post an decided to include us in the list,
as we have been using OpenTelemetry for a while already.

Thanks!

2024-03-11 11:49 UTC, theletterf commented
Hi! Could you sign the CLA?

2024-03-11 11:55 UTC, adolsalamanca commented
Hi @theletterf , I have tried to sign it already and it's awaiting for my employer authorization.
Thanks

2024-03-12 10:53 UTC, svrnm commented
> Thanks @jpkrohling , I believe it's in the appropriate section. Timescale is now just focused on offering the best cloud timeseries/vector/analytics database, built on PostgreSQL.

Your blog post indicates otherwise, it's not about how timescale uses OpenTelemetry internally to monitor their own infrastructure. Especally the last sentence indicates that this is better suited in the vendors list: "If you're looking for a time-series database to store your metrics, check out Timescale."

2024-03-12 11:13 UTC, adolsalamanca commented
> > Thanks @jpkrohling , I believe it's in the appropriate section. Timescale is now just focused on offering the best cloud timeseries/vector/analytics database, built on PostgreSQL.
> 
> Your blog post indicates otherwise, it's not about how timescale uses OpenTelemetry internally to monitor their own infrastructure. Especally the last sentence indicates that this is better suited in the vendors list: "If you're looking for a time-series database to store your metrics, check out Timescale."

Thanks for your response @svrnm , that's accurate. 
Maybe we should not include that blog post, as it's from times when we were actively promoting [Promscale](https://github.com/timescale/promscale), which has been already discontinued.

2024-03-13 08:37 UTC, svrnm requested changes

2024-03-13 11:30 UTC, adolsalamanca commented on data/ecosystem/adopters.yaml
> +  reference: blog/a-deep-dive-into-open-telemetry-metrics/
Thanks, just fixed it, but then a few other needs an update too.

2024-03-13 13:03 UTC, svrnm commented on data/ecosystem/adopters.yaml
> +  reference: blog/a-deep-dive-into-open-telemetry-metrics/
ebay, farfetch and uplight blogs are local at opentelemetry.io

2024-03-13 13:54 UTC, adolsalamanca commented on data/ecosystem/adopters.yaml
> +  reference: blog/a-deep-dive-into-open-telemetry-metrics/
Oh, I had no idea.
thanks

2024-03-13 15:17 UTC, svrnm commented on data/ecosystem/adopters.yaml
> +  reference: blog/a-deep-dive-into-open-telemetry-metrics/
> Please replace this with a blog post that shows how timescale uses OpenTelemetry themselves

this is still open.

2024-03-13 16:27 UTC, adolsalamanca commented on data/ecosystem/adopters.yaml
> +  reference: blog/a-deep-dive-into-open-telemetry-metrics/
Sorry, didn't read your  comment correctly.
I'm removing the post altogether as there's no such a blog post, we can add it later when the the time comes.

thanks

2024-03-13 16:31 UTC, svrnm commented on data/ecosystem/adopters.yaml
> +  reference: blog/a-deep-dive-into-open-telemetry-metrics/
@adolsalamanca to me it is still not clear how Timescale "adopts" OpenTelemetry, are you using it internally to monitor your own systems, or are you providing services to customers that make use of OpenTelemetry or can be used in combination with OpenTelemetry. The first instance is "adoption", the other 2 instances are either a "vendor" (if you ingest OpenTelemetry into your systems for your customers") or integration (if your services emit OpenTelemetry to observability backends)

2024-04-11 08:47 UTC, svrnm commented
@adolsalamanca any updates?

2024-05-25 15:04 UTC, cartermp commented
Closing old PR

2024-05-25 15:04 UTC, closed without merging