Add Ansible role for OpenTelemetry Collector to the registry
open-telemetry/opentelemetry.io pull request #4139
Opened 2024-03-12 10:23 UTC by ishanjainn

Related PR for docs https://github.com/open-telemetry/opentelemetry.io/pull/4135

2024-03-12 10:49 UTC, svrnm requested changes

2024-03-12 10:49 UTC, svrnm commented on data/registry/tools-ansible-grafana.yml
> +description: Ansible role to deploy and manage OpenTelemetry Collector across mutiple machines
```suggestion
description: Ansible role by Grafana to deploy and manage OpenTelemetry Collector across mutiple machines
```

2024-03-12 10:49 UTC, svrnm commented on data/registry/tools-ansible-grafana.yml
> +    email: ishan.jain0099@gamil.com
you can also add a github handle here instead of your email, might be better so your email does not get crawled

2024-03-12 10:49 UTC, svrnm commented on data/registry/tools-ansible-grafana.yml
> +  repo: https://github.com/grafana/grafana-ansible-collection/tree/main/roles/opentelemetry_collector
```suggestion
  repo: https://github.com/grafana/grafana-ansible-collection/tree/main/roles/opentelemetry_collector
  docs: https://galaxy.ansible.com/ui/repo/published/grafana/grafana/content/role/opentelemetry_collector
```

2024-03-13 09:54 UTC, svrnm approved these changes

2024-03-13 10:09 UTC, svrnm commented
/fix:all

2024-03-13 10:11 UTC, svrnm commented on data/registry/tools-ansible-grafana.yml
> +description: Ansible role by Grafana to deploy and manage OpenTelemetry Collector across mutiple machines
```suggestion
description: Ansible role by Grafana to deploy and manage OpenTelemetry Collector across multiple machines
```

2024-03-13 10:12 UTC, svrnm commented on data/registry/tools-ansible-grafana.yml
> +title: Ansible role for OpenTelemetry Collector
```suggestion
# cSpell:ignore ansible Ishan ishanjainn
title: Ansible role for OpenTelemetry Collector
```

2024-03-13 10:33 UTC, svrnm commented
/fix:all

2024-03-13 11:03 UTC, svrnm commented on data/registry/tools-ansible-grafana.yml
> +    url: www.github.com/ishanjainn
```suggestion
    url: https://www.github.com/ishanjainn
```

2024-03-13 11:06 UTC, svrnm commented
/fix:all

2024-03-13 11:20 UTC, merged

2024-05-09 21:50 UTC, chalin commented on data/registry/tools-ansible-grafana.yml
> +language: yaml
@svrnm - does it really make sense for the language to be YAML here?