Blog: Blog post for scaling OpenTelemetry Collectors using Ansible
open-telemetry/opentelemetry.io pull request #4140
Opened 2024-03-12 11:45 UTC by ishanjainn

**Preview**: https://deploy-preview-4140--opentelemetry.netlify.app/blog/2024/scaling-opentelemetry-collectors/

2024-03-12 23:10 UTC, chalin reviewed
Other than the step numbering, as noted by @tiffany76, the indentation is wrong:

> <img width="1054" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/790d98cf-20f2-4122-aebd-b8578242f590">

Any content of a numbered list item should be indented by as many spaces as the number of characters before the first word of the item. (In your current format, that's 3 spaces, but if/when you fix the formatting, that might change.)

2024-03-13 10:08 UTC, svrnm requested changes
Thanks, see my inline comments.

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +The [Grafana Agent role](https://github.com/grafana/grafana-ansible-collection/tree/main/roles/grafana_agent) is available in the Grafana Ansible collection as of the 1.1.0 release.
```suggestion
A [OpenTelemetry Collector role](https://github.com/grafana/grafana-ansible-collection/tree/main/roles/opentelemetry_collector) is provided through the [Grafana Ansible collection](https://docs.ansible.com/ansible/latest/collections/grafana/grafana/) as of the 1.1.0 release.
```

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +- Account permissions to install and configure the OpenTelemetry Collector on these hosts.
I guess the end user also needs to have ansible installed?

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +  143.244.174.246    # hostname = fedora-02
I would recommend to replace these IPs with non-public ones, so something like 10.x.x.x, etc.

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +  > **Note**: If you are copying the above file, remove the comments (#).
```suggestion
{{% alert title="Note" %}}

If you are copying the above file, remove the comments (#).


{{% /alert %}}
```

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +    traces_username: <tempo-username>                        # Example - 411478
```suggestion
```

Make this config independent of Grafana Cloud, we want to have this generally applicable.

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +              password: "{{ grafana_cloud_api_key }}"
```suggestion
```

Make this config independent of Grafana Cloud, we want to have this generally applicable.

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +              authenticator: basicauth/grafana_cloud_tempo
Replace this with jaeger, or use a debug exporter

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +              authenticator: basicauth/grafana_cloud_loki
replace this with a debug exporter

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +              authenticator: basicauth/grafana_cloud_prometheus
replace this with prometheus onprem

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +          extensions: [basicauth/grafana_cloud_tempo, basicauth/grafana_cloud_prometheus, basicauth/grafana_cloud_loki]
```suggestion
```

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +> **Note:** You'll need to adjust the configuration to match the specific telemetry you intend to collect and where you plan to forward it. This configuration snippet is a basic example designed for
```suggestion
{{% alert title="Note" %}}

You'll need to adjust the configuration to match the specific telemetry you intend to collect and where you plan to forward it. This configuration snippet is a basic example designed for traces, logs, and metrics collected using OTLP and forwarded to Jaeger and Prometheus. 

{{% /alert %}}
```

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +- Execute a query to confirm the reception of metrics, for example, `{instance="ubuntu-01"}` for a specific host's metrics.
```suggestion
```

see above, no vendor-specific details

2024-03-13 10:08 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +## Visualizing metrics and logs in Grafana
Make use of OSS Grafana for visualization or jaeger/prometheus standalone

2024-03-13 11:05 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +This guide simplifies the deployment of the OpenTelemetry Collector across multiple Linux hosts using Ansible and illustrates how to visualize collected telemetry in Grafana. Tailor the OpenTelemetry
this still reads like a marketing blob, I have no issues with promoting OSS grafana here, but ideally this is practical, so how to setup grafana swiftly to see some of the data.

2024-03-13 13:17 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +author: '[Ishan Jain](https://github.com/ishanjainn) (Grafana)'
add a cSpell:ignore: section for words unknown to cspell, check other blog posts for examples

2024-03-13 13:18 UTC, svrnm commented on content/en/blog/2024/scaling-opentelemetry-collectors.md
> +This guide simplifies the deployment of the OpenTelemetry Collector across multiple Linux hosts using Ansible and illustrates how to visualize collected telemetry in Grafana. Tailor the OpenTelemetry
yes, exactly.

2024-03-14 11:51 UTC, svrnm commented
> Hey @svrnm The REFCACHE workflow tell me to run `npm run test-and-fix` but that doesnt seem to do anything for me

do not worry too much about that, we fix the checks at the end before merging the PR, there are some nuances with links that sometimes break the pipeline, and while updating the content you may break it again and again

> also for the `canonical_url` This can be added later right as I would be publishing a similar blog (for Grafana Cloud usage as OSS is covered here) but on Grafana's Blog

So, here is my semi-professional SEO opinion: the content that comes first is the "canonical url", so the grafana blog should point to this blog as canoncial. If the grafana blog has a policy against that, we need to discuss that.

2024-03-15 16:33 UTC, svrnm commented
> > So, here is my semi-professional SEO opinion: the content that comes first is the "canonical url", so the grafana blog should point to this blog as canoncial. If the grafana blog has a policy against that, we need to discuss that.
> 
> Ahh, I don't think that is possible, Ill get that if possible too but would be nice to have it from here aswell, That is possible to update later or needs to be in this PR?

Do you think that it is not possible or do you know that it is not possible? Can you please check with the Grafana Blog Team first and then follow up with us?

Our current policy does not cover this use case, so we would need look into this (cc @open-telemetry/docs-approvers). 

Personally I still think it doesn't feel right to update an existing blog post to point to a blog post that came later and by that downgrading it from a SEO perspective: whoever takes the blog post first has the major work of copyediting and reviewing.

2024-03-19 07:36 UTC, closed without merging