Add OTel Operator status section
open-telemetry/opentelemetry.io pull request #4148
Opened 2024-03-13 02:27 UTC by cartermp

fixes https://github.com/open-telemetry/opentelemetry.io/issues/4131

@jaronoff97 Would love some help finding the right word to define the actual operator status. Is it stable/beta/alpha/etc?

2024-03-13 02:39 UTC, cartermp commented
/fix:format

2024-03-13 08:33 UTC, svrnm requested changes

2024-03-13 10:00 UTC, theletterf commented on content/en/status.md
> +The Operator itself is considered TODO LOL.
I kind of like `TODO LOL` as a maturity level.

2024-03-13 10:50 UTC, pavolloffay commented on content/en/status.md
> +The Operator itself is considered TODO LOL.
I think we should talk about statuses of the  CRDs managed by the operator (`OpenTelemetryCollector` and `Instrumentation`, `OpAMPBridge`).

2024-03-14 03:14 UTC, cartermp commented on content/en/status.md
> +The Operator itself is considered TODO LOL.
That's a good idea. What would the statuses be?

2024-04-11 08:49 UTC, svrnm commented on content/en/status.md
> +The Operator itself is considered TODO LOL.
@pavolloffay can you help @cartermp to update the TODO?

2024-04-11 13:06 UTC, pavolloffay commented on content/en/status.md
> +The Operator itself is considered TODO LOL.
The fields in the CRD exposed by the operator should not change https://github.com/open-telemetry/opentelemetry-operator/tree/main/apis. At the moment there are under v1alpha1 and v1beta1

2024-04-11 17:54 UTC, cartermp commented
/fix:format

2024-04-11 17:55 UTC, cartermp commented on content/en/status.md
> +The Operator itself is considered TODO LOL.
Thanks @pavolloffay, I updated with this info.

2024-04-11 17:55 UTC, cartermp commented
@svrnm please give this another look!

2024-04-15 09:37 UTC, svrnm approved these changes

2024-04-15 09:37 UTC, svrnm commented
@open-telemetry/operator-approvers PTAL!

2024-04-15 10:36 UTC, swiatekm-sumo approved these changes

2024-04-15 13:12 UTC, merged