Blog: Enhancing Acknowledgment of Community Contributions in OpenTelemetry Profiling
open-telemetry/opentelemetry.io pull request #4186
Opened 2024-03-20 10:38 UTC by Rperry2174

This PR introduces modifications to the blog post about OpenTelemetry's profiling support to better acknowledge the contributions of various community members and organizations. The key changes include:

Expanded Acknowledgements: We're enhancing the acknowledgements section to highlight the collaborative efforts within the Profiling SIG.

Inclusive Recognition: Specifically mentioning contributions from companies like Grafana Labs, Datadog, and Red Hat to recognize their significant input

Highlighting Community Contributions:

- Mentioning the proposals for the profiling data model (OTEPs 237 and 239)
- Acknowledging the broad-based discussion and alignment within the community on the profiling data format.

These changes aim to reflect the collective and diverse efforts that have been instrumental in advancing OpenTelemetry's profiling capabilities, ensuring that all key contributors are recognized

2024-03-20 11:01 UTC, austinlparker approved these changes

2024-03-20 11:47 UTC, cartermp approved these changes
Thanks! This is a good addition.

2024-03-20 12:24 UTC, cartermp commented
/fix:all

2024-03-20 12:28 UTC, austinlparker requested changes
temp hold on this

2024-03-20 12:40 UTC, cartermp commented
yee yee

2024-03-20 13:39 UTC, disfluxly commented
This is definitely needed. As a community member that has followed this pretty closely, I was very surprised not seeing Ryan and/or Grafana Labs anywhere in the original post.

2024-03-20 14:43 UTC, tedsuo commented
Sorry to fuss over a blog post, Is it possible to list the people, not the companies? In OTel we prefer to highlight individual contributions, it sometimes ruffle feathers when public communication from the project can be interpreted as an advertisement for certain companies. 

If it's a big donation it's one thing, but when we're talking about SIG contributions we try to focus on individuals.

2024-03-20 16:19 UTC, felixge approved these changes
Thanks Ryan 🙇

2024-03-20 16:19 UTC, felixge commented on content/en/blog/2024/opentelemetry-announced-support-for-profiling.md
> +This milestone for OpenTelemetry profiling feature reflects a collaborative
grammar nit

```suggestion
This milestone for the OpenTelemetry profiling signal reflects a collaborative
```

2024-03-20 16:26 UTC, felixge commented
> Sorry to fuss over a blog post, but is it possible to list the people, not the companies? In OTel we prefer to highlight individual contributions, it sometimes ruffle feathers when public communication from the project can be interpreted as an advertisement for certain companies.
> 
> If it's a big donation it's one thing, but when we're talking about SIG contributions we try to focus on individuals.

How about naming individuals with their company names in parens? Otherwise this approach raises questions about the value of SIG work vs code donations.

2024-03-21 07:55 UTC, theletterf approved these changes

2024-03-21 10:43 UTC, austinlparker approved these changes
lgtm

2024-03-21 10:45 UTC, merged

2024-03-21 11:00 UTC, tedsuo commented
@felixge thats totally fine, it's usually how we do it.

2024-03-21 13:03 UTC, jpkrohling approved these changes