Demo imageprovider docs
open-telemetry/opentelemetry.io pull request #4273
Opened 2024-04-09 13:03 UTC by klucsik

Docs for https://github.com/open-telemetry/opentelemetry-demo/pull/1462

2024-04-11 07:47 UTC, svrnm requested changes

2024-04-11 07:47 UTC, svrnm commented on content/en/docs/demo/services/imageprovider.md
> +This service provides the images whcih are used in the frontend. Thei mages are statically hosted on a nginx instance. The nginx server is insturemnted with [nginx-otel module](https://github.com/ngi
```suggestion
This service provides the images which are used in the frontend. The images are statically hosted on a nginx instance. The nginx server is instrumented with the [nginx-otel module](https://github.com/nginxinc/nginx-otel/tree/main).
```

2024-04-11 12:01 UTC, mviitane approved these changes

2024-04-11 12:14 UTC, svrnm requested changes

2024-04-11 12:14 UTC, svrnm commented on content/en/docs/demo/services/imageprovider.md
> +title: Imageprovider Service
```suggestion
title: Image Provider Service
```

2024-04-11 12:14 UTC, svrnm commented on content/en/docs/demo/services/imageprovider.md
> +linkTitle: Imageprovider
```suggestion
linkTitle: Image Provider
```

2024-04-11 12:14 UTC, svrnm commented on content/en/docs/demo/services/imageprovider.md
> +aliases: [imageprovider]
```suggestion
```

2024-04-11 12:14 UTC, svrnm commented on content/en/docs/demo/services/imageprovider.md
> +This service provides the images which are used in the frontend. The images are statically hosted on a nginx instance. The nginx server is instrumented with the [nginx-otel module](https://github.com
```suggestion
This service provides the images which are used in the frontend. The images are statically hosted on a NGINX instance. The NGINX server is instrumented with the [nginx-otel module](https://github.com/nginxinc/nginx-otel/tree/main).
```

2024-04-12 08:53 UTC, theletterf approved these changes

2024-04-15 09:13 UTC, svrnm approved these changes

2024-04-15 09:21 UTC, merged

2024-04-15 09:21 UTC, svrnm commented
thank you @klucsik

2024-05-04 02:14 UTC, abirfo commented
c83c48330022839de92f0b2a580379a50c0f43e6