Add missing FQN for common resource attributes
open-telemetry/opentelemetry.io pull request #4330
Opened 2024-04-20 15:09 UTC by cartermp

fixes https://github.com/open-telemetry/opentelemetry.io/issues/4328

2024-04-22 06:12 UTC, zeitlinger requested changes
this is now deprecated: https://github.com/open-telemetry/semantic-conventions-java/blob/9202fd6cdc1b21e05558d17b6f13608345a3f80b/semconv/src/main/java/io/opentelemetry/semconv/ServiceAttributes.java#L15

2024-04-22 07:51 UTC, theletterf commented
Should this be closed then?

2024-04-22 09:21 UTC, zeitlinger commented on content/en/docs/languages/java/exporters.md
> +    Resource resource = Resource.getDefault().toBuilder().put(ResourceAttributes.SERVICE_NAME, "dice-server").put(ResourceAttributes.SERVICE_VERSION, "0.1.0").build();
```suggestion
    Resource resource = Resource.getDefault().toBuilder().put(ServiceAttributes.SERVICE_NAME, "dice-server").put(ServiceAttributes.SERVICE_VERSION, "0.1.0").build();
```

2024-04-22 09:26 UTC, zeitlinger commented
> Should this be closed then?

I added a suggestion.
The import is still wrong though.

2024-04-29 07:03 UTC, zeitlinger commented
@theletterf I now have an alternative suggestion: 

we can move the example code to https://github.com/open-telemetry/opentelemetry-java-examples and then embed the example code using `code_excerpter`.

See https://github.com/open-telemetry/opentelemetry.io/issues/4276

I'm happy to help :smile:

2024-04-29 07:06 UTC, theletterf commented
Nice! Could you try that in a draft PR?

2024-06-10 13:58 UTC, zeitlinger commented
Superceded by https://github.com/open-telemetry/opentelemetry.io/pull/4642

2024-06-10 13:58 UTC, closed without merging