[demo docs] Add imageSlowLoad featureflag description
open-telemetry/opentelemetry.io pull request #4483
Opened 2024-05-14 09:43 UTC by klucsik

docs for https://github.com/open-telemetry/opentelemetry-demo/pull/1515

2024-05-14 10:19 UTC, svrnm requested changes

2024-05-14 10:19 UTC, svrnm commented on content/en/docs/demo/feature-flags.md
> +| `imageSlowLoad`                     | Frontend         | Utilizing envoy fault injection, produces a delay in laoding of product images in the frontend.           |
```suggestion
| `imageSlowLoad`                     | Frontend         | Utilizes envoy fault injection, produces a delay in loading of product images in the frontend.           |
```

2024-05-14 11:41 UTC, mviitane approved these changes

2024-05-15 07:44 UTC, svrnm commented
/fix:all

2024-05-15 07:55 UTC, svrnm approved these changes

2024-05-15 08:43 UTC, merged