Add new blog post for Humans of OTel recap
open-telemetry/opentelemetry.io pull request #4661
Opened 2024-06-11 19:52 UTC by avillela

Blog post recap for the Humans of OTel from KubeCon EU 2024

Related issue: #4660

2024-06-12 06:52 UTC, svrnm commented on content/en/blog/2024/humans-of-otel-eu-2024.md
> +  [OpenTelemetry blog](https://github.com/open-telemetry/opentelemetry.io/blob/954103a7444d691db3967121f0f1cb194af1dccb/README.md#submitting-a-blog-post)
```suggestion
  [OpenTelemetry blog](/docs/contributing/blog/)
```

2024-06-12 06:52 UTC, svrnm requested changes
Minor nit, but overall LGTM

2024-06-12 15:00 UTC, danielgblanco approved these changes

2024-06-13 08:14 UTC, theletterf approved these changes

2024-06-14 18:10 UTC, reese-lee approved these changes

2024-06-15 18:19 UTC, cartermp approved these changes

2024-06-15 18:26 UTC, cartermp commented on content/en/blog/2024/humans-of-otel-eu-2024.md
> +date: 2024-06-11
```suggestion
date: 2024-06-15
```

2024-06-15 18:34 UTC, merged