[ja] translate Semantic convention and Resource
open-telemetry/opentelemetry.io pull request #4741
Opened 2024-06-25 07:37 UTC by ymotongpoo

translate the following files into Japanese

- content/ja/docs/concepts/resources/index.md
- content/ja/docs/concepts/semantic-conventions.md

2024-06-26 13:42 UTC, katzchang approved these changes

2024-06-27 09:08 UTC, svrnm commented on content/ja/docs/concepts/resources/screenshot-jaeger-resources.png
Just tagging this (non blocking for the merge): it might become worth to investigate how we want to handle images in localized documentation. It's probably not trivial to solve, because sometimes the image needs to be localized as well, but somtimes we also might just want to use the existing English one (as we do here)

cc @chalin

2024-06-27 09:08 UTC, svrnm approved these changes

2024-06-27 20:36 UTC, chalin commented on content/ja/docs/concepts/resources/screenshot-jaeger-resources.png
Hugo is now setup to reuse the default language image -- the exact same file, no duplication (as was the case for static resources a few Hugo versions ago).

**Images should _not_ be duplicated.** I'd suggest using the default image except where there's too much English text in the image, of course.

2024-06-27 20:38 UTC, chalin requested changes

2024-06-27 20:38 UTC, chalin commented on content/ja/docs/concepts/resources/screenshot-jaeger-resources.png
Has this image been changed (it doesn't seem so), in which case it should not be included in this PR.

 I might have to do some tests to ensure that this works as expected. Putting this PR in draft mode until then.

2024-06-27 20:53 UTC, chalin commented on content/ja/docs/concepts/resources/screenshot-jaeger-resources.png
Thanks for this first PR that surfaces the problem with shared images @ymotongpoo. 
I'll need some time to investigate how to address this issue.

2024-06-28 00:39 UTC, ymotongpoo commented on content/ja/docs/concepts/resources/screenshot-jaeger-resources.png
ok, then I remove this file from this PR.

2024-07-01 07:23 UTC, ymotongpoo commented on content/ja/docs/concepts/resources/screenshot-jaeger-resources.png
I removed duplicated files from this PR.

2024-07-02 21:27 UTC, chalin approved these changes

2024-07-02 21:27 UTC, merged