[ja] translation of instrumentation scope and sampling
open-telemetry/opentelemetry.io pull request #4744
Opened 2024-06-25 11:58 UTC by ymotongpoo

## Docs PR Checklist

- [X] This PR is for a documentation page whose authoritative copy is in the
      opentelemetry.io repository.

2024-06-26 13:08 UTC, svrnm commented
@katzchang please take a look!

2024-06-26 14:05 UTC, katzchang requested changes
2点コメントしました。
画像の文字も翻訳したいところですが、優先度的には下げて、次回という感じでいいと思います。

2024-06-26 14:05 UTC, katzchang commented on content/ja/docs/concepts/instrumentation-scope/index.md
> +たとえば、どのユーザーがどのバージョンのライブラリーを使用していて、そのライブラリーのパフォーマンスはどうなのか、あるいは、アプリケーションの特定のモジュールに問題があるのかを特定するためです。
`ライブラリー` の末尾長音の表記揺れ。
`ライブラリ` でいいかなとは思います。

2024-06-26 14:05 UTC, katzchang commented on content/ja/docs/concepts/sampling/index.md
> +- [テイルサンプリングプロセッサー](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor)
サンプラーは固有名詞扱いで良いかと思います。

2024-06-26 14:47 UTC, ymotongpoo commented on content/ja/docs/concepts/sampling/index.md
> +- [テイルサンプリングプロセッサー](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor)
固有名詞扱いにするというのはそのまま英語表記にするということ？

2024-06-26 16:09 UTC, katzchang commented on content/ja/docs/concepts/sampling/index.md
> +- [テイルサンプリングプロセッサー](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor)
そう言いたかった。
どうですかねえ。

2024-06-27 03:53 UTC, ymotongpoo commented on content/ja/docs/concepts/instrumentation-scope/index.md
> +たとえば、どのユーザーがどのバージョンのライブラリーを使用していて、そのライブラリーのパフォーマンスはどうなのか、あるいは、アプリケーションの特定のモジュールに問題があるのかを特定するためです。
表記揺れサンクス。このあたりはtextlintで弾けるようにしようと思います。(ref: https://github.com/open-telemetry/opentelemetry.io/issues/4745)

2024-06-28 00:57 UTC, ymotongpoo commented
@chalin should I remove the duplicated images from this PR as well (ref: #4741)

2024-06-28 01:09 UTC, katzchang approved these changes

2024-07-02 01:22 UTC, ymotongpoo commented
@svrnm @chalin could you take another look and give your LGTM?

2024-07-02 21:07 UTC, chalin approved these changes
LGTM. FYI, I've created the following issue to track the feedback form issue:

- #4781

2024-07-02 21:19 UTC, merged