[ja] add Japanese translation of distribution and glossary
open-telemetry/opentelemetry.io pull request #4767
Opened 2024-07-01 04:09 UTC by ymotongpoo

## Docs PR Checklist

- [X] This PR is for a documentation page whose authoritative copy is in the
      opentelemetry.io repository.

2024-07-01 05:51 UTC, ymotongpoo commented
@chalin Hi Patrice, I got the following error on checking the link targets and found that the target doc is in the different repository. (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md)

```
ja/docs/concepts/glossary/index.html
  hash does not exist --- ja/docs/concepts/glossary/index.html --> /docs/specs/otel/overview#links-between-span
```

How do I tackle on this issue?

2024-07-01 22:35 UTC, chalin commented on content/ja/docs/concepts/glossary.md
> +詳細は[スパン間のリンク](/docs/specs/otel/overview#links-between-span)と[リンクの指定](/docs/specs/otel/trace/api#specifying-links)を参照してください。
The hash is missing an `s`:

```suggestion
詳細は[スパン間のリンク](/docs/specs/otel/overview#links-between-spans)と[リンクの指定](/docs/specs/otel/trace/api#specifying-links)を参照してください。
```

2024-07-02 01:18 UTC, ymotongpoo commented
@chalin thank you for catching the nit but hard to find mistake. now it's good to go.

2024-07-02 01:19 UTC, ymotongpoo commented
@katzchang could you review this PR? thanks!

2024-07-02 21:47 UTC, chalin approved these changes

2024-07-05 06:30 UTC, ymotongpoo commented
@katzchang yoroshiku onegaishimasu

2024-07-05 07:47 UTC, katzchang requested changes
いくつかコメントしました。

2024-07-05 07:47 UTC, katzchang commented on content/ja/docs/concepts/distributions.md
> +どの参照　実装も、ディストリビューションとしてカスタマイズできます。
参照「　」実装の間のスペース🪐

2024-07-05 07:47 UTC, katzchang commented on content/ja/docs/concepts/glossary.md
> +[有向非巡回グラフ][dag]のこと。
アクロニウムの理解をたすけるために `[有向非巡回グラフ（Directed Acyclic Graph）]` のように補足したい

2024-07-05 07:47 UTC, katzchang commented on content/ja/docs/concepts/glossary.md
> +[メトリクス](#metric)で特に使われる用語。[属性](#attribute)を参照してください。
`see` の表現を「参照のこと」か「参照してください」のどちらかに合わせたい。

2024-07-05 07:47 UTC, katzchang commented on content/ja/docs/concepts/glossary.md
> +重大度やトレース情報など、他のフィールドも`メタデータ`とみなされるかもしれません。
`メタデータ` -> `Metadata` のほうが適切かなと思います（が、原文でなぜマークアップされているのか、ちょっとよくわかりませんが。。。）

2024-07-05 07:47 UTC, katzchang commented on content/ja/docs/concepts/glossary.md
> +生測定値または事前定義された集計値のいずれかのデータポイントを、[メタデータ](#metadata)付きの時系列として記録します。
「生の測定値」のように助詞を足して補足したい

2024-07-05 07:47 UTC, katzchang commented on content/ja/docs/concepts/glossary.md
> +テレメトリーを生成するエンティティに関する情報を[属性](#attribute)として取得します。
「取得」 -> 「捕捉」のような、キャプチャ感のある語に（#4782 での議論と同様）

2024-07-08 02:06 UTC, ymotongpoo commented on content/ja/docs/concepts/distributions.md
> +どの参照　実装も、ディストリビューションとしてカスタマイズできます。
space🛰

2024-07-08 02:07 UTC, ymotongpoo commented on content/ja/docs/concepts/glossary.md
> +[メトリクス](#metric)で特に使われる用語。[属性](#attribute)を参照してください。
「参照のこと」でいきます。

2024-07-08 02:07 UTC, ymotongpoo commented on content/ja/docs/concepts/glossary.md
> +テレメトリーを生成するエンティティに関する情報を[属性](#attribute)として取得します。
捕捉に

2024-07-08 02:07 UTC, ymotongpoo commented on content/ja/docs/concepts/glossary.md
> +生測定値または事前定義された集計値のいずれかのデータポイントを、[メタデータ](#metadata)付きの時系列として記録します。
「の」足しました

2024-07-08 02:08 UTC, ymotongpoo commented on content/ja/docs/concepts/glossary.md
> +[有向非巡回グラフ][dag]のこと。
元の英単語足しました

2024-07-08 02:16 UTC, ymotongpoo commented on content/ja/docs/concepts/glossary.md
> +重大度やトレース情報など、他のフィールドも`メタデータ`とみなされるかもしれません。
俺も原文でなんでマークアップされてるかよくわからなくて、とりあえず強調したかっただけかなって思ったので日本語にしたんだけども、いったん英語にしときます

2024-07-08 02:26 UTC, ymotongpoo commented
@katzchang yorosiku onegaishimasu

2024-07-08 02:39 UTC, katzchang approved these changes
yosasou desu

2024-07-09 01:06 UTC, ymotongpoo commented
@open-telemetry/docs-approvers could you merge this PR? thank you!

2024-07-09 08:33 UTC, svrnm approved these changes

2024-07-09 08:33 UTC, svrnm commented
> @open-telemetry/docs-approvers could you merge this PR? thank you!

Thanks for the ping!

2024-07-10 00:06 UTC, merged