[ja] add: translation of contributing
open-telemetry/opentelemetry.io pull request #4780
Opened 2024-07-02 14:52 UTC by kaitoii11

translate `content/docs/contributing/_index.md` to Japanese.r

2024-07-03 04:26 UTC, ymotongpoo reviewed
Thank you for your contribution! I left some comments and I'd like to hear your thoughts on those.

2024-07-03 04:26 UTC, ymotongpoo commented on content/ja/docs/contributing/_index.md
> +OpenTelemetryドキュメントコントリビューターは以下を行ないます:
nit: please avoid using colons in Japanese; you could use normal period (句点) here.

2024-07-03 04:26 UTC, ymotongpoo commented on content/ja/docs/contributing/_index.md
> +コントリビュートライセンス規約(Contributor License Agreement)と行動規範(Code of Conduct)の詳細が記されています。
this is just a confirmation, but is it common to translate "Contributor" to "コントリビュート"? I see that consistency in your translation, I'm wondering which is better to translate "コントリビュート" or "コントリビューター" here, though the impressions of both translation give are mostly same.

2024-07-03 11:47 UTC, kaitoii11 commented on content/ja/docs/contributing/_index.md
> +コントリビュートライセンス規約(Contributor License Agreement)と行動規範(Code of Conduct)の詳細が記されています。
Typo for the コントリビュートライセンス規約. I fixed it to コントリビューターライセンス規約 to match the original text.

2024-07-04 00:06 UTC, ymotongpoo requested changes
the doc linked is named "OpenTelemetry Contributor Guide" so I fixed here. otherwise, all LGTM, so I'll approve this PR as soon as the suggestion is merged.

2024-07-04 00:06 UTC, ymotongpoo commented on content/ja/docs/contributing/_index.md
> +OpenTelemetryプロジェクトへの一般的なコントリビュートの手引には、[OpenTelemetryコントリビューティングガイド](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md)を参照ください。
```suggestion
OpenTelemetryプロジェクトへの一般的なコントリビュートの手引には、[OpenTelemetryコントリビューターガイド](https://github.com/open-telemetry/community/blob/main/CONTRIBUTING.md)を参照ください。
```

2024-07-04 01:54 UTC, ymotongpoo approved these changes
LGTM

2024-07-05 08:22 UTC, svrnm commented
Thank you @kaitoii11 !

2024-07-05 08:22 UTC, svrnm approved these changes

2024-07-05 08:25 UTC, merged