[pt-br] Localize otel-localized announcement page to Portuguese (Brazil)
open-telemetry/opentelemetry.io pull request #5035
Opened 2024-08-13 23:43 UTC by pedroespindula

Waiting for #4996 to be merged.

2024-08-14 18:34 UTC, lgfa29 reviewed
Ótimo trabalho @pedroespindula!

2024-08-14 18:34 UTC, lgfa29 commented on content/pt/blog/2024/docs-localized.md
> +experiência do usuário do OpenTelemetry.
```suggestion
Nós agradecemos todas as pessoas que contribuíram para tornar isso uma realidade, e
estamos ansiosos para ver como essas novas opções de idioma podem melhorar a
experiência de usuário do OpenTelemetry.
```

"make this possible" é tipo "tornar realidade", não necessariamente fazer o possível.

2024-08-15 11:39 UTC, edsoncelio commented on content/pt/blog/2024/docs-localized.md
> +Estamos felizes em anunciar que o site do OpenTelemetry está disponível em
+1 pra segunda sugestão!

2024-08-15 11:41 UTC, edsoncelio commented on content/pt/blog/2024/docs-localized.md
> +finais acesso a documentações em diversas linguagens, facilitando o aprendizado
Acho que não chegamos a um consenso pra "end user", ótima pergunta.

Nesse contexto acho que se refere mais a usuário final mesmo.

2024-08-15 11:42 UTC, edsoncelio commented on content/pt/blog/2024/docs-localized.md
> +Se você é fluente em uma linguagem que já é suportada, você pode ajudar criando
"idiomas suportados" também parece bom!

2024-08-15 11:44 UTC, edsoncelio commented on content/pt/blog/2024/docs-localized.md
> +[crie uma issue](<https://github.com/open-telemetry/opentelemetry.io/issues/new?title=Add+%3CYOUR%20LANGUAGE%3E+(%3CYOUR+CODE%3E)+version+of+website+pages&body=%3C!--+Provide+github+handles+of+at+lea
Também não temos tradução pra issue ainda.
Não tenho muito uma opinião sobre traduzir já que é um nome comum do ecossistema do GitHub.

2024-08-16 13:06 UTC, EzzioMoreira commented on content/pt/blog/2024/docs-localized.md
> +Estamos felizes em anunciar que o site do OpenTelemetry está disponível em
Voto pela primeira sugestão.

2024-08-16 23:48 UTC, EzzioMoreira commented on content/pt/blog/2024/docs-localized.md
> +finais acesso a documentações em diversas linguagens, facilitando o aprendizado
Foi traduzido literalmente: usuário final. 
https://github.com/open-telemetry/opentelemetry.io/pull/4997/files#diff-e25eb4d4a8d751fe6eba2e26ad39ea46656a4063f5f6e5f2e9de9d84afb74009R131

2024-08-20 08:36 UTC, theletterf commented
@pedroespindula The announcement should go live today ideally. Could you have a look at the feedback please?

2024-08-20 14:59 UTC, chalin requested changes
Hi. This PR will need to be **rebased**, have conflicts resolved, and then force-pushed.

2024-08-21 15:11 UTC, pedroespindula commented on content/pt/blog/2024/docs-localized.md
> +[crie uma issue](<https://github.com/open-telemetry/opentelemetry.io/issues/new?title=Add+%3CYOUR%20LANGUAGE%3E+(%3CYOUR+CODE%3E)+version+of+website+pages&body=%3C!--+Provide+github+handles+of+at+lea
Concordo com o @edsoncelio para esse caso, nesse sentido, irei optar por não traduzir o termo.

2024-08-21 15:17 UTC, pedroespindula commented
> @pedroespindula The announcement should go live today ideally. Could you have a look at the feedback please?

> Hi. This PR will need to be **rebased**, have conflicts resolved, and then force-pushed.

Hey, @theletterf and @chalin! 

Thanks for the heads up! I have updated the PR according to the feedbacks and *rebased* the PR. Also, I made the PR *Ready for Review*. 

Also, thanks for the review @lgfa29!

Cc: @edsoncelio

2024-08-21 15:23 UTC, edsoncelio reviewed
LGTM!!

2024-08-21 16:14 UTC, EzzioMoreira commented
LGTM 🆗 
Parabéns pela iniciativa @pedroespindula 👏

2024-08-22 08:05 UTC, theletterf approved these changes

2024-08-22 08:05 UTC, theletterf commented
/fix:format

2024-08-22 14:13 UTC, chalin commented
@open-telemetry/docs-pt-approvers - please (GH) approve

2024-08-22 14:15 UTC, chalin approved these changes
LGTM
Awaiting official approval from @open-telemetry/docs-pt-approvers before merging.

2024-08-22 14:16 UTC, edsoncelio commented
@emdneto 
![image](https://github.com/user-attachments/assets/5de26c4d-5624-4f16-ba7f-fc46a7dd3a5d)

2024-08-22 19:02 UTC, chalin commented
@open-telemetry/docs-maintainers - any idea why @open-telemetry/docs-pt-approvers / maintainers isn't a choice in the Reviewers request dropdown?

> <img width="296" alt="image" src="https://github.com/user-attachments/assets/35793ee4-a249-485f-bd66-4f8935ba6d53">

2024-08-22 23:13 UTC, emdneto approved these changes

2024-08-23 15:21 UTC, chalin commented
Merging on @emdneto's approval.

2024-08-23 15:22 UTC, merged