feature: demo structure - spanish translation
open-telemetry/opentelemetry.io pull request #5053
Opened 2024-08-17 21:27 UTC by krol3

Related the issue https://github.com/open-telemetry/opentelemetry.io/issues/4887

2024-08-22 17:30 UTC, krol3 commented
@ramrodo @theletterf @electrocucaracha, could you review please?

2024-08-22 23:31 UTC, ramrodo commented on content/es/docs/demo/_index.md
> +## Ejecución la Demo
```suggestion
## Ejecución de la Demo
```

2024-08-22 23:31 UTC, ramrodo commented on content/es/docs/demo/_index.md
> +cubre cómo instalar y ejecutar la demostración, y algunos escenarios que puede usar para ver
```suggestion
cubre cómo instalar y ejecutar la demostración, y algunos escenarios que puedes usar para ver
```

2024-08-22 23:32 UTC, ramrodo commented on content/es/docs/demo/_index.md
> +Puede encontrar información específica sobre cómo se implementa OpenTelemetry en cada servicio aquí:
```suggestion
Puedes encontrar información específica sobre cómo se implementa OpenTelemetry en cada servicio aquí:
```

2024-08-22 23:32 UTC, ramrodo commented on content/es/docs/demo/_index.md
> +¿Cómo se pueden resolver los problemas con OpenTelemetry? Estos escenarios le muestran
```suggestion
¿Cómo se pueden resolver los problemas con OpenTelemetry? Estos escenarios te muestran
```

2024-08-22 23:33 UTC, ramrodo commented on content/es/docs/demo/_index.md
> +- Descubra una fuga de memoria y diagnostíquela mediante métricas y seguimientos.
```suggestion
- Descubre una fuga de memoria y diagnostíquela mediante métricas y seguimientos.
```

2024-08-22 23:33 UTC, ramrodo reviewed
Some suggestions made.

2024-08-23 06:14 UTC, theletterf requested changes
Excellent work! Just some comments to better align.

2024-08-23 06:14 UTC, theletterf commented on content/es/docs/demo/_index.md
> +cubre cómo instalar y ejecutar la demostración, y algunos escenarios que puedes usar para ver
```suggestion
describe cómo instalar y ejecutar la demostración, además de algunos escenarios que puedes usar para ver
```

It's OK to depart lightly from the original text to convey the same meaning.

2024-08-23 06:14 UTC, theletterf commented on content/es/docs/demo/_index.md
> +## Ejecución de la Demo
```suggestion
## Ejecución de la demo
```

Title case is not a thing in Spanish, so all titles we found in EN that use title case should be converted to sentence case.

2024-08-23 06:14 UTC, theletterf commented on content/es/docs/demo/_index.md
> +## Referencia de Funciones del Lenguaje de Programación
```suggestion
## Referencia de funciones del lenguaje de programación
```

2024-08-23 06:14 UTC, theletterf commented on content/es/docs/demo/_index.md
> +| Lenguaje   | Instrumentación Automática                          | Bibliotecas de Instrumentación                                                                    | Instrumentación Manual
```suggestion
| Lenguaje   | Instrumentación automática                          | Bibliotecas de instrumentación                                                                    | Instrumentación manual                                                                       |
```

2024-08-23 06:14 UTC, theletterf commented on content/es/docs/demo/_index.md
> +## Documentación de los Servicios
```suggestion
## Documentación de los servicios
```

2024-08-23 06:14 UTC, theletterf commented on content/es/docs/demo/_index.md
> +con ID de producto: `OLJCESPC7Z` utilizando el servicio Feature Flag
```suggestion
con ID de producto: `OLJCESPC7Z` utilizando el servicio Feature Flag.
```

2024-08-23 06:14 UTC, theletterf commented on content/es/docs/demo/_index.md
> +- Descubre una fuga de memoria y diagnostíquela mediante métricas y seguimientos.
```suggestion
- Descubre una fuga de memoria y diagnostícala mediante métricas y seguimientos.
```

2024-08-26 13:26 UTC, theletterf commented
@krol3 PTAL, thanks!

2024-08-26 17:02 UTC, electrocucaracha commented on content/es/docs/demo/_index.md
> +- [Requisitos](./requirements/)
```suggestion
- [Requisitos](requirements/)
```

2024-08-27 07:21 UTC, theletterf commented on content/es/docs/demo/_index.md
> +¿Quieres entender cómo funciona la instrumentación de un lenguaje en particular? Comienza aquí.
https://www.rae.es/espanol-al-dia/tilde-en-que-cuales-quienes-como-cuan-cuantoaosas-cuando-donde-y-adonde

2024-08-28 08:29 UTC, theletterf approved these changes

2024-08-28 08:31 UTC, theletterf commented
/fix:format

2024-08-28 08:41 UTC, merged