[es] feature: contributing - spanish translation
open-telemetry/opentelemetry.io pull request #5058
Opened 2024-08-18 16:24 UTC by krol3

2024-08-22 17:31 UTC, krol3 commented
@ramrodo @theletterf @electrocucaracha, could you review please?

2024-08-22 23:36 UTC, ramrodo reviewed
LGTM

2024-08-23 06:00 UTC, theletterf requested changes
Nice! Some suggestions.

I'm adding the `default_lang_commit` to all other PRs. To learn what that is about, see https://opentelemetry.io/docs/contributing/localization/#adding-default_lang_commit-to-new-pages

2024-08-23 06:00 UTC, theletterf commented on content/es/docs/contributing/_index.md
> +Los colaboradores de la documentación de OpenTelemetry:
```suggestion
Quienes colaboran para documentar OpenTelemetry:
```

2024-08-23 06:00 UTC, theletterf commented on content/es/docs/contributing/_index.md
> +- Mejorar el código que construye el sitio.
```suggestion
- Mejoran el contenido existente.
- Crean contenido nuevo.
- Actualizan el Registro de OpenTelemetry.
- Mejoran el código que construye el sitio.
```

2024-08-23 06:00 UTC, theletterf commented on content/es/docs/contributing/_index.md
> +[Guía del Contribuyente de OpenTelemetry](https://github.com/open-telemetry/community/blob/main/guides/contributor/README.md), que proporciona detalles sobre el Acuerdo de Licencia del Contribuyente
```suggestion
Para obtener orientación sobre cómo contribuir al proyecto OpenTelemetry en general, consulta la 
[Guía del contribuyente de OpenTelemetry](https://github.com/open-telemetry/community/blob/main/guides/contributor/README.md), que proporciona detalles sobre el Acuerdo de Licencia del Contribuyente y el Código de Conducta. Cada implementación de lenguaje, el Collector y las convenciones en el [repositorio](https://github.com/open-telemetry/) tiene sus propias guías específicas para contribuir.
```

2024-08-26 13:26 UTC, theletterf commented
@krol3 PTAL

2024-08-26 18:47 UTC, theletterf commented on content/es/docs/contributing/_index.md
> +Las siguientes guías describen cómo contribuir a la documentación de OpenTelemetry.
Tilde is required in this case.

2024-08-27 07:24 UTC, theletterf commented
/fix:all

2024-08-27 07:27 UTC, theletterf approved these changes

2024-08-27 07:39 UTC, merged