Add clarification for otel-js apps written in CJS and ESM
open-telemetry/opentelemetry.io pull request #5072
Opened 2024-08-20 21:14 UTC by JamieDanielson

Node.js has two module systems: [CommonJS(CJS) and ECMAScript modules(ESM)](https://nodejs.org/api/packages.html#determining-module-system). As ESM becomes more common in usage, we need to better document the current assumptions and requirements.

This is a start with the bare minimum, which is to specify the assumption that the app is running as CJS... as well as document the loader hook currently required for ESM apps. It seemed useful to start here based on issues like #4812.

More details will follow as we [finalize reference docs](https://github.com/open-telemetry/opentelemetry-js/pull/4876) in the otel-js repo.

2024-08-21 00:25 UTC, trentm commented on content/en/docs/languages/js/getting-started/nodejs.md
> +
Having the h3 section header for this unintentionally puts the subsequent content ("Open http://localhost:8080/rolldice in your web browser ...") under this section.

I don't have a great alternative suggestion. Perhaps the section could be replaced with a much shorter:

> (Note: If your application is written in JavaScript as ECMAScript Modules (ESM), or compiled to ESM from TypeScript, then a loader hook is required to properly support instrumentation. Use `node --experimental-loader=@opentelemetry/instrumentation/hook.mjs --require ./instrumentation.js app.js`. See [the coming reference link in opentelemetry-js/docs/] for details on ESM support.)

2024-08-21 00:25 UTC, trentm commented on content/en/docs/languages/js/libraries.md
> +If the application runs as ESM, add the loader hook as specified in [Getting Started](/docs/languages/js/getting-started/nodejs/#instrumentation-for-ecmascript-modules).
Ah... in my suggestion above, I've removed this anchor. Perhaps the "see here for more info" could be the opentelemetry-js/doc/  document that is being added in https://github.com/open-telemetry/opentelemetry-js/pull/4876 instead?

2024-08-21 07:54 UTC, theletterf requested changes
Thanks! Some comments.

2024-08-21 07:54 UTC, theletterf commented on content/en/docs/languages/js/getting-started/nodejs.md
> +Much of OpenTelemetry JS documentation is written assuming the compiled application is run as CommonJS.
```suggestion
The OpenTelemetry documentation assumes that the compiled application is run as CommonJS.
```

Would it make sense to add a link to CommonJS? Are all Node developers familiar with it?

2024-08-21 07:54 UTC, theletterf commented on content/en/docs/languages/js/getting-started/nodejs.md
> +### Instrumentation for ECMAScript Modules
```suggestion
### Instrumentation for ECMAScript modules
```

2024-08-21 07:54 UTC, theletterf commented on content/en/docs/languages/js/getting-started/nodejs.md
> +This flag must be passed to the `node` binary, which is often done as a startup command and/or in the `NODE_OPTIONS` environment variable.
```suggestion
If your application is written in JavaScript as ESM, or compiled to ESM
from TypeScript, a loader hook is required to patch instrumentation.
The custom hook for ESM instrumentation is
`--experimental-loader=@opentelemetry/instrumentation/hook.mjs`.
This flag must be passed to the `node` binary, which is often done
as a startup command or through the `NODE_OPTIONS` environment variable.
```

2024-08-21 07:54 UTC, theletterf commented on content/en/docs/languages/js/libraries.md
> +Much of OpenTelemetry JS documentation is written assuming the compiled application is run as CommonJS.
```suggestion
The OpenTelemetry documentation assumes that the compiled application is run as CommonJS.
```

2024-08-21 07:54 UTC, theletterf commented on content/en/docs/languages/js/instrumentation.md
> +Much of OpenTelemetry JS documentation is written assuming the compiled application is run as CommonJS.
```suggestion
The OpenTelemetry documentation assumes that the compiled application is run as CommonJS.
```

2024-08-21 07:54 UTC, theletterf commented on content/en/docs/languages/js/propagation.md
> +Much of OpenTelemetry JS documentation is written assuming the compiled application is run as CommonJS.
```suggestion
The OpenTelemetry documentation assumes that the compiled application is run as CommonJS.
```

2024-08-21 07:54 UTC, theletterf commented on content/en/docs/languages/js/resources.md
> +Much of OpenTelemetry JS documentation is written assuming the compiled application is run as CommonJS.
```suggestion
The OpenTelemetry documentation assumes that the compiled application is run as CommonJS.
```

2024-08-21 22:59 UTC, JamieDanielson commented
I've moved this back to draft for now! It will be easier when we can link to another doc.

2024-11-11 20:16 UTC, cartermp commented
@JamieDanielson should this move back to review now that upstream is merged?

2024-11-19 20:25 UTC, JamieDanielson commented
> @JamieDanielson should this move back to review now that upstream is merged?

This completely fell off my radar, will double check for necessary changes and re-open for review!

2025-05-09 07:33 UTC, svrnm commented
is this PR still needed/something to work on?

2025-05-23 14:25 UTC, JamieDanielson commented
Sorry all let's close this for now 😅

2025-05-23 14:25 UTC, closed without merging

2025-12-17 21:46 UTC, JamieDanielson commented
Hey I'm back! Opened a new PR to replace this #8666 as I wasn't sure what would be easiest to review. I incorporated the PR feedback and added the doc that now exists in the repo.

2025-12-17 21:46 UTC, JamieDanielson commented on content/en/docs/languages/js/getting-started/nodejs.md
> +Much of OpenTelemetry JS documentation is written assuming the compiled application is run as CommonJS.
Updated the text in the new PR and included a link to CommonJS.

2025-12-17 21:47 UTC, JamieDanielson commented on content/en/docs/languages/js/getting-started/nodejs.md
> +### Instrumentation for ECMAScript Modules
This section header was replaced with a note block, as Trent pointed out it visually broke the page up in a weird way.