[ja] add Japanese translation of "install the collector"
open-telemetry/opentelemetry.io pull request #5109
Opened 2024-08-27 00:45 UTC by ymotongpoo

Translate this page into Japanese: https://opentelemetry.io/docs/collector/installation/

2024-09-04 09:45 UTC, theletterf commented
@open-telemetry/docs-ja-approvers Please have a look.

2024-09-04 11:14 UTC, katzchang requested changes

2024-09-04 11:14 UTC, katzchang commented on content/ja/docs/collector/installation.md
> +title: コレクターのインストール
原文が "Install the Collector" で、大文字始まりのCollectorなので、英語表記のまま「Collectorのインストール」にしたい。
以下の文章中も、大文字始まりCollectorの箇所は英語表記のままにしたい。

2024-09-04 11:14 UTC, katzchang commented on content/ja/docs/collector/installation.md
> +次のコマンドは、エージェントをデーモンセットと単一のゲートウェイインスタンスとしてデプロイします。
「デーモンセットとしてエージェントと、単一のゲートウェイインスタンスをデプロイします」

2024-10-05 16:20 UTC, theletterf commented
@ymotongpoo Could you check the suggestions? Thanks!

2024-11-05 12:32 UTC, svrnm commented
@ymotongpoo any updates?

2024-11-06 22:37 UTC, ymotongpoo commented
It turned out that I need to recreate the PR with new company email address so that EasyCLA process properly understand the requester.

2024-11-07 08:56 UTC, svrnm commented
> @svrnm @theletterf sorry for the delay. I've been in the process of changing jobs and have had no time for this. I'm trying to make time.

No worries, we check in from time to time with PRs pending, but we all understand that live changes and priorties shift. Glad to hear that you found a new place to work for and still want to find time to work on this.

> It turned out that I need to recreate the PR with new company email address so that EasyCLA process properly understand the requester.

Yes, that might be a thing, if you need to close this PR and raise a new one don't hesitate to do that

2024-11-07 09:23 UTC, ymotongpoo commented
Thank you, @svrnm for checking in and suggestion! Closing this PR for now and I'll reopen with new email address marked.

2024-11-07 09:23 UTC, closed without merging