Removing repeated words
open-telemetry/opentelemetry.io pull request #5164
Opened 2024-09-07 15:52 UTC by puneet-ekline

### Description
Updating the docs to remove repeated words.

More details [here](https://ekline.atlassian.net/wiki/external/MDJmNWI3MjBkMzE4NGQyMzhlYjkxNjUwNDVhYjBlOGQ)

2024-09-08 13:50 UTC, theletterf approved these changes
Thanks!

2024-09-08 13:51 UTC, theletterf commented
/fix:format

2024-09-08 13:55 UTC, theletterf commented
/fix:format

2024-09-08 14:25 UTC, tsloughter approved these changes

2024-09-08 14:36 UTC, theletterf commented
@puneet-ekline Please run `npm run fix:format` from your CLI.

2024-09-08 14:57 UTC, austinlparker requested changes
see https://github.com/open-telemetry/opentelemetry.io/pull/5160#issuecomment-2336716134

2024-09-08 15:03 UTC, cijothomas approved these changes
LGTM

2024-09-10 20:24 UTC, ferd approved these changes

2024-09-10 21:25 UTC, breedx-splk commented on content/en/docs/collector/building/receiver.md
> +your `NewFactory()` function in your `factory.go` file as follow:
```suggestion
your `NewFactory()` function in your `factory.go` file as follows:
```

2024-09-11 13:10 UTC, theletterf commented
@svrnm Shall we merge this one?

2024-09-11 13:23 UTC, svrnm commented
> @svrnm Shall we merge this one?

Same here, let's finish the discussion first, see the other PR

2024-09-13 08:05 UTC, svrnm commented
Please see https://github.com/open-telemetry/opentelemetry.io/pull/5160#issuecomment-2348281987

2024-09-13 08:06 UTC, svrnm requested changes
contentwise lgtm, I will block it with `request changes` to allow everyone to review the comment on our position on mixing a sales pitch / growth hacking with a contribution to our project.

2024-09-30 08:20 UTC, svrnm commented on content/en/docs/collector/building/receiver.md
> +your `NewFactory()` function in your `factory.go` file as follow:
@puneet-ekline please address this

2024-10-02 12:27 UTC, svrnm approved these changes

2024-10-02 12:31 UTC, austinlparker approved these changes

2024-10-02 15:47 UTC, merged