Update Documentation for Internal Metric Naming Conventions  #4933
open-telemetry/opentelemetry.io pull request #5178
Opened 2024-09-10 19:51 UTC by Tharanishwaran

This PR updates the documentation to clarify the internal metric naming conventions for the OpenTelemetry Collector.

Changes:
              Added a note to explain:
              1.Starting from v0.106.1: Metrics from Collector components are prefixed with otelcol_, while metrics from 
                  instrumentation  libraries are not prefixed.
              
               2.Versions before v0.106.1: All internal metrics, regardless of their source, had the otelcol_ prefix.

This update ensures that users understand the changes in metric naming conventions across different versions of the Collector.

2024-09-10 21:05 UTC, tiffany76 requested changes
Great job! I added short code formatting for the call-out to match others on the page.

I also think this note would be better placed further down where the list of metrics occurs. Right about [line 189](https://github.com/open-telemetry/opentelemetry.io/blob/473fe06d36d72eaa9e4196ff9bcf5b0499d05ddb/content/en/docs/collector/internal-telemetry.md?plain=1#L189) should do it.

2024-09-10 21:05 UTC, tiffany76 commented on content/en/docs/collector/internal-telemetry.md
> +> For Collector versions prior to v0.106.1, all internal metrics, regardless of their origin, were prefixed with `otelcol_`. This includes metrics from both Collector components and instrumentation l
```suggestion
{{% alert title="Note" color="info" %}}
As of Collector v0.106.1, internal metric names are handled differently based on their source:
- Metrics generated from Collector components are prefixed with `otelcol_`.
- Metrics generated from instrumentation libraries do not use the `otelcol_` prefix.

For Collector versions prior to v0.106.1, all internal metrics, regardless of their origin, are prefixed with `otelcol_`. This includes metrics from both Collector components and instrumentation libraries.
{{% /alert %}}
```

2024-09-10 21:05 UTC, tiffany76 commented on content/en/docs/collector/internal-telemetry.md
> +
We'll need these back ticks to close the yaml code block. Could you add them again?

2024-09-11 03:54 UTC, Tharanishwaran commented
Hi @tiffany76,
I have realized that some unintended commits were included in this pull request. I apologize for the oversight and any inconvenience this may have caused. I will address this issue promptly by removing the extraneous commits and ensuring that only the intended changes remain.

2024-09-11 21:33 UTC, tiffany76 approved these changes

2024-09-11 21:34 UTC, tiffany76 commented
LGTM, @Tharanishwaran! Thanks for your contribution.

@open-telemetry/collector-approvers, PTAL.

2024-09-11 22:48 UTC, codeboten reviewed
Thanks @Tharanishwaran! Added a note, the prefix was not applied to internal metrics emitted via OTLP

2024-09-11 22:48 UTC, codeboten commented on content/en/docs/collector/internal-telemetry.md
> +For Collector versions prior to v0.106.1, all internal metrics, regardless of
```suggestion
For Collector versions prior to v0.106.1, all internal metrics emitted via the Prometheus exporter, regardless of
```

2024-09-12 02:58 UTC, Tharanishwaran commented
Thanks @tiffany76 and @codeboten for the reviews and feedback! The checks have passed and the changes have been approved. Could someone please merge the PR when possible

2024-09-12 03:03 UTC, Tharanishwaran commented
Many thanks to @tiffany76, @codeboten  for your useful comments and taking the time to review the changes. I am glad that the checks passed and the PR finally got approval. If possible, one of the maintainers kindly goes ahead and merges the PR. Truly I appreciate the time and your support

2024-09-12 13:26 UTC, songy23 commented
Thank you @Tharanishwaran  for calling it out, we have run into the same issue in 0.106 & 0.107

2024-09-12 17:39 UTC, Tharanishwaran commented
Thank you @songy23 for your  comment I’ve implemented the suggested change regarding the otelcol_ prefix

2024-09-12 18:30 UTC, songy23 approved these changes

2024-09-12 20:39 UTC, tiffany76 reviewed
One tiny change.

2024-09-12 20:39 UTC, tiffany76 commented on content/en/docs/collector/internal-telemetry.md
> +For Collector versions prior to v0.106.1, all internal metrics emitted via the Prometheus exporter, regardless of
```suggestion
For Collector versions prior to v0.106.1, all internal metrics emitted using the Prometheus exporter, regardless of
```

2024-09-12 20:43 UTC, tiffany76 commented
/fix:format

2024-09-13 04:01 UTC, Tharanishwaran commented
/fix:all

2024-09-13 08:25 UTC, merged