Update observability-driven testing commands in documentation
open-telemetry/opentelemetry.io pull request #5215
Opened 2024-09-18 07:35 UTC by johnnydacosta

Replaced the `make start-odd` and related Docker command in the "Enable API observability-driven testing" section with updated commands (`make run-tracetestings` and `docker compose -f docker-compose-tests.yml run traceBasedTests`) to reflect current available commands. The previous `make start-odd` command no longer exists.

2024-09-18 07:44 UTC, svrnm approved these changes

2024-09-18 11:44 UTC, julianocosta89 requested changes
Hello @johnnydacosta thx for fixing it.
Would you mind applying my suggestions?
The make command is actually named: `run-tracetesting`.

2024-09-18 11:44 UTC, julianocosta89 commented on content/en/docs/demo/docker-deployment.md
> +make run-tracetestings
```suggestion
make run-tracetesting
```
https://github.com/open-telemetry/opentelemetry-demo/blob/main/Makefile#L107

2024-09-18 11:44 UTC, julianocosta89 commented on content/en/docs/demo/docker-deployment.md
> +- Tracetest UI: <http://localhost:11633/>, only when using `make run-tracetestings`
```suggestion
- Tracetest UI: <http://localhost:11633/>, only when using `make run-tracetesting`
```

2024-09-18 12:37 UTC, johnnydacosta commented
Hi @julianocosta89, I just applied the fix now :)

2024-09-18 12:41 UTC, julianocosta89 approved these changes
Thank you!
LGTM

2024-09-19 13:03 UTC, theletterf commented
/fix:format

2024-09-19 13:07 UTC, merged