firstParty flag for Ruby
open-telemetry/opentelemetry.io pull request #5235
Opened 2024-09-23 21:48 UTC by haidong

To address #4795, this is part of a series of PRs that add isFirstParty or isNative flags to instrumentation registries that lack them.

This batch touches Ruby instrumentation registries.

2024-09-24 09:19 UTC, svrnm requested changes

2024-09-24 09:19 UTC, svrnm commented on data/registry/instrumentation-ruby-elasticsearch.yml
> +isFirstParty: true
```suggestion
isNative: true
```

2024-09-24 20:19 UTC, haidong commented
/fix:all

2024-09-26 07:21 UTC, svrnm approved these changes

2024-09-27 12:02 UTC, theletterf commented
@svrnm How can we fix those registry errors?

2024-09-30 08:15 UTC, svrnm commented
> @svrnm How can we fix those registry errors?

there is a real error in one of the files:

[07:22:09] YAMLException: duplicated mapping key (24:1)

2024-09-30 08:16 UTC, svrnm commented on data/registry/instrumentation-ruby-elasticsearch.yml
> +isNative: true
```suggestion
```

there is an `isNative` already in line 19

2024-10-02 08:09 UTC, merged