feat: [es] Create docs/kubernetes/collector/_index.md
open-telemetry/opentelemetry.io pull request #5250
Opened 2024-09-25 06:20 UTC by mlpaucara

Related issue https://github.com/open-telemetry/opentelemetry.io/issues/5227

2024-09-25 06:40 UTC, theletterf requested changes

2024-09-25 06:40 UTC, theletterf commented on content/es/docs/kubernetes/collector/_index.md
> +title: Colector OpenTelemetry y Kubernetes
De momento, estamos manteniendo "OpenTelemetry Collector" porque es un nombre propio de producto, pero podemos usar "colector" en minúsculas para referirnos a un colector en un entorno. 

+CC @krol3

2024-09-25 06:40 UTC, theletterf commented on content/es/docs/kubernetes/collector/_index.md
> +linkTitle: Colector
```suggestion
linkTitle: Colector
```

Aquí lo podemos mantener.

2024-09-25 06:40 UTC, theletterf commented on content/es/docs/kubernetes/collector/_index.md
> +configuracion y solución de problemas, vea [Colector](/docs/collector/).
```suggestion
El [OpenTelemetry Collector](/docs/collector/) es una forma de recibir, procesar
y exportar datos de telemetría sin importar el proveedor. Si bien el colector
puede ser usado en muchos lugares, esta documentación se enfoca en
cómo utilizar el colector para supervisar Kubernetes y los servicios que se
ejecutan en Kubernetes. Para documentación más general del colector, como
configuracion y solución de problemas, consulta [Colector](/docs/collector/).
```

Preferiría tutear al usario. @krol3 ¿Qué opinas?

2024-09-25 11:09 UTC, krol3 commented on content/es/docs/kubernetes/collector/_index.md
> +configuracion y solución de problemas, vea [Colector](/docs/collector/).
Si me gustaron tus recomendaciones. El uso de lenguaje coloquial y de preferencia usando el tiempo presente.

2024-09-25 15:22 UTC, mlpaucara commented on content/es/docs/kubernetes/collector/_index.md
> +title: Colector OpenTelemetry y Kubernetes
¿Entonces el título cambia? Porque veo que en la descripción propuesta más adelante se hace referencia a "OpenTelemetry Collector"

2024-09-26 05:40 UTC, theletterf commented on content/es/docs/kubernetes/collector/_index.md
> +title: Colector OpenTelemetry y Kubernetes
Debería cambiar, sí

2024-09-27 11:57 UTC, theletterf approved these changes

2024-09-27 12:02 UTC, theletterf commented
/fix:format

2024-09-27 12:05 UTC, theletterf commented
/fix:all

2024-09-27 12:12 UTC, merged