feat: [es] Create /docs/contributing/new-content.md
open-telemetry/opentelemetry.io pull request #5270
Opened 2024-09-30 06:40 UTC by TineoC

**Description**
This pull request adds the Spanish localization of the /docs/contributing/new-content page on the OpenTelemetry website. The translation includes all sections from the original English document, maintaining the format and structure to ensure consistency with other localized sections.

**Changes made:**
* Created the new-content.md file in the docs/es/contributing/ directory.
* Translated the original content, preserving technical semantics and reference links.
* Minor adjustments were made to the Markdown content for improved display.

**References**
This work is related to issue [#5205](https://github.com/open-telemetry/opentelemetry.io/issues/5205), which tracks the Spanish localization of the contributing documentation folder.

2024-09-30 06:51 UTC, TineoC commented
@krol3 @theletterf

2024-09-30 08:03 UTC, theletterf requested changes
Good work! First review round.

2024-09-30 08:03 UTC, theletterf commented on content/es/docs/contributing/new-content.md
> +errores automáticamente.
```suggestion
Para enumerar los scripts NPM disponibles, ejecuta `npm run`. Consulta
los [Pre-requisitos de PR](/docs/contributing/pr-checks) para obtener más
información sobre las verificaciones de los Pull Request y cómo solucionar
errores automáticamente.
```

2024-09-30 08:03 UTC, theletterf commented on content/es/docs/contributing/new-content.md
> +Para crear y servir el sitio localmente con Hugo, ejecute el siguiente comando:
```suggestion
Para crear y servir el sitio localmente con Hugo, ejecuta el siguiente comando:
```

2024-09-30 08:03 UTC, theletterf commented on content/es/docs/contributing/new-content.md
> +`Ctrl+C`, o cierre la ventana de la terminal.
```suggestion
Navega a `http://localhost:1313` en su navegador web para ver la vista previa
local. Hugo observa los cambios y reconstruye el sitio según sea necesario.

Para detener la instancia local de Hugo, vuelve a la terminal y escriba
`Ctrl+C`, o cierre la ventana de la terminal.
```

2024-09-30 08:03 UTC, theletterf commented on content/es/docs/contributing/new-content.md
> +
```suggestion
Si envías una PR, Netlify crea una [Vista Previa de Implementación][] para que puedas
revisar sus cambios. Una vez que se fusiona su PR, Netlify implementa el sitio actualizado
en el servidor de producción.

> **Nota**: Las vistas previas de PR incluyen _páginas de borrador_, pero las
> compilaciones de producción no.

Para ver los registros de implementación y más, visita el [Panel de Control][]
del proyecto. Se requiere inicio de sesión en Netlify.

```

2024-09-30 08:03 UTC, theletterf commented on content/es/docs/contributing/new-content.md
> +lo más sencillo posible, le pedimos que respete lo siguiente:
```suggestion
Antes de fusionar un PR, a veces se requieren algunas iteraciones de revisión y
edición. Para ayudarnos a nosotros y a ti mismo a hacer que este proceso sea
lo más sencillo posible, te pedimos que respetes lo siguiente:
```

2024-09-30 08:03 UTC, theletterf commented on content/es/docs/contributing/new-content.md
> +  (https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
```suggestion
- Si su PR no es una solución rápida, entonces **trabaja desde una copia**: 
  selecciona el botón
  [Fork](https://github.com/open-telemetry/opentelemetry.io/fork) en la parte
  superior del repositorio y clone el repositorio localmente. Cuando esté listo,
  genere un PR al repositorio original.
- **No trabajes desde la rama `main`** de su fork: crea una rama
  específica para el PR.
- Asegúrate de que los mantenedores tengan permiso para aplicar cambios a tu
  solicitud de incorporación de cambios
  (https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
```

2024-09-30 08:03 UTC, theletterf commented on content/es/docs/contributing/new-content.md
> +cualquier otro cambio, actualiza tu rama.
```suggestion
A veces, los revisores suben cambios en tu pull request. Antes de realizar
cualquier otro cambio, actualiza tu rama.
```

2024-09-30 08:03 UTC, theletterf commented on content/es/docs/contributing/new-content.md
> +puede crear un merge. Es tu responsabilidad resolver todos los conflictos en tu
```suggestion
puedes crear un merge. Es tu responsabilidad resolver todos los conflictos en tu
```

2024-09-30 08:03 UTC, theletterf commented on content/es/docs/contributing/new-content.md
> +Para obtener más información, consulte
```suggestion
Para obtener más información, consulta
```

2024-09-30 08:03 UTC, theletterf commented on content/es/docs/contributing/new-content.md
> +   que el rebase está completo.
```suggestion
1. Agrega los archivos al conjunto de cambios:

   ```shell
   git add <filename>
   ```

1. Continúa con el rebase:

   ```shell
   git rebase --continue
   ```

1. Repite los pasos 2 a 5 según sea necesario.

   Después de aplicar todas las confirmaciones, el comando `git status` muestra
   que el rebase está completo.
```

2024-09-30 12:58 UTC, theletterf approved these changes

2024-09-30 13:01 UTC, theletterf requested changes
@TineoC Please check the spell checker warnings -- fix or add an exception when required. Thanks!

2024-09-30 13:01 UTC, theletterf commented on content/es/docs/contributing/new-content.md
> +1.Selecciona en **Crear pull request**.
```suggestion
1. Selecciona **Proponer cambios**.

1. Selecciona **Crear pull request**.

1. Cuando la pantalla de **Abrir un pull request** aparezca. Agrega una
   descripción para que los supervisores puedan comprender tus cambios.

1.Selecciona **Crear pull request**.
```

2024-09-30 14:08 UTC, chalin commented on content/en/docs/contributing/pull-requests.md
@open-telemetry/docs-approvers - do we want to establish the convention that (generally speaking), changes to `en` pages should _not_ be done in non-`en` PRs?

2024-09-30 14:08 UTC, chalin commented on content/es/docs/contributing/new-content.md
I guess that you now know that the page path has changed. Do you want to use the new name as of now?

2024-09-30 14:31 UTC, theletterf commented on content/en/docs/contributing/pull-requests.md
That's probably the most sensible thing to do, yes.

@TineoC Could you please revert the changes on the `en` page? We can fix it in a separate PR. You can change the ES diagram anyway if you want.

2024-09-30 14:32 UTC, theletterf commented on content/es/docs/contributing/new-content.md
Hmm, was it changes recently? Otherwise, we should use an existing name.

2024-09-30 15:32 UTC, TineoC commented on content/en/docs/contributing/pull-requests.md
Done @theletterf

2024-09-30 15:37 UTC, TineoC commented on content/es/docs/contributing/new-content.md
I see is now called pull-requests.md @theletterf

2024-10-01 05:56 UTC, theletterf commented
/fix:all

2024-10-01 10:04 UTC, theletterf commented
@chalin Not sure how to fix these — the error message doesn't ring a bell:

```
> check:markdown
> scripts/check-markdown-wrapper.sh

WARNING: required symlink target does not exist, creating it: content-modules/opentelemetry-go/example
+ mkdir -p content-modules/opentelemetry-go/example
WARNING: required symlink target does not exist, creating it: content-modules/opentelemetry-java-examples/doc-snippets
+ mkdir -p content-modules/opentelemetry-java-examples/doc-snippets
+ exec npm run _check:markdown
```

2024-10-01 11:23 UTC, chalin reviewed
This review contains fixes for the errors reported in:

- https://github.com/open-telemetry/opentelemetry.io/actions/runs/11119487777/job/30894746956

Also see https://github.com/open-telemetry/opentelemetry.io/actions/runs/11119531305/job/30894983276?pr=5270, which reports a missing hash (i.e., heading ID).

2024-10-01 11:23 UTC, chalin commented on content/es/docs/contributing/pull-requests.md
> +  (https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
The markdown syntax is invalid. Do something like this to fix it.

```suggestion
- Asegúrate de que los mantenedores tengan permiso para [aplicar cambios a tu
  solicitud de incorporación de cambios](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
```

2024-10-01 11:23 UTC, chalin commented on content/es/docs/contributing/pull-requests.md
> +   ```
~~~suggestion
   ```shell
   git add <filename>
   ```
~~~

2024-10-01 11:25 UTC, chalin commented
> @chalin Not sure how to fix these — the error message doesn't ring a bell:
> 
> ```
> > check:markdown
> > scripts/check-markdown-wrapper.sh
> 
> WARNING: required symlink target does not exist, creating it: content-modules/opentelemetry-go/example
> + mkdir -p content-modules/opentelemetry-go/example
> WARNING: required symlink target does not exist, creating it: content-modules/opentelemetry-java-examples/doc-snippets
> + mkdir -p content-modules/opentelemetry-java-examples/doc-snippets
> + exec npm run _check:markdown
> ```

I'm not seeing those warnings in https://github.com/open-telemetry/opentelemetry.io/actions/runs/11119487777/job/30894746956. What I see is:

> > _check:markdown
> > npx gulp lint-md
> 
> [05:57:27] Using gulpfile ~/work/opentelemetry.io/opentelemetry.io/gulpfile.js
> [05:57:27] Starting 'lint-md'...
> /home/runner/work/opentelemetry.io/opentelemetry.io/content/es/docs/contributing/pull-requests.md:415: MD034/no-bare-urls Bare URL used [Context: "https://docs.github.com/es/pul..."]
> /home/runner/work/opentelemetry.io/opentelemetry.io/content/es/docs/contributing/pull-requests.md:482: trim-code-block-and-unindent Code block: avoid leading/trailing empty lines and excess indentation [Trim empty lines and/or unindent] [Context: "   ```shell"]
> [05:57:33] 'lint-md' errored after 5.61 s
> [05:57:33] Error: Processed 588 files, 1 had issues.

I've resolved these issues through the suggestions of the review I just submitted.

2024-10-01 11:27 UTC, chalin commented
@TineoC @theletterf et al.: this PR should be rebased and conflicts resolved, after the suggestions that I made have been accepted.

> <img width="319" alt="image" src="https://github.com/user-attachments/assets/f6aee66b-8917-46d9-b423-f30e8143a105">

2024-10-01 11:38 UTC, theletterf approved these changes

2024-10-01 11:39 UTC, theletterf commented
/fix:format

2024-10-01 11:39 UTC, TineoC commented
/fix:all

2024-10-01 11:41 UTC, TineoC commented
/fix:all

2024-10-01 11:59 UTC, theletterf commented
/fix:refcache

2024-10-01 12:05 UTC, theletterf commented
/fix:all

2024-10-01 14:02 UTC, chalin requested changes
This PR has changes that it isn't supposed to:

> <img width="859" alt="image" src="https://github.com/user-attachments/assets/3a23a5c5-525f-4681-899c-ac93e364ace3">

As I mentioned earlier, this PR needs to be updated via a **rebase** to fix the out-of-sync with HEAD issue.

2024-10-01 14:03 UTC, theletterf commented
@TineoC Could you please rebase from upstream?

2024-10-02 05:57 UTC, theletterf commented
@TineoC It might be simpler to close this PR and open a new one bringing your changes over.

2024-10-02 12:28 UTC, chalin commented
@TineoC - you seem to still be using merge rather than rebase.

> <img width="493" alt="image" src="https://github.com/user-attachments/assets/803a5167-3b46-4fb9-9da4-55efcc3c4b80">

Note that you first need to fetch the latest upstream `main`, and then rebase from it. If you aren't sure how to rebase, feel free to ask for help. @theletterf's suggestion of creating a new PR is a good idea too. It's your call.

2024-10-30 08:22 UTC, theletterf commented
@TineoC Could you try rebasing, as suggested by @chalin ?

2024-10-30 13:37 UTC, closed without merging