"feat: [es] Create observability-primer.md "
open-telemetry/opentelemetry.io pull request #5302
Opened 2024-10-03 22:10 UTC by mlunadia

feat: [es] Create observability-primer.md
Related to https://github.com/open-telemetry/opentelemetry.io/issues/5206

2024-10-03 22:31 UTC, mlunadia commented
@krol3 I see spelling checks are failing for Spanish words, perhaps we need to update the tests to include Spanish or how can we add words to the vocabulary?

2024-10-04 07:37 UTC, theletterf requested changes
Excelente trabajo, @mlunadia, tan solo una sugerencias de estilo (que estoy consolidando en un documento).

Sobre los errores de spelling, el diccionario no es del todo completo. Sugiero añadir las excepciones en el frontmatter usandp `cSpell:ignore:` o bien a https://github.com/open-telemetry/opentelemetry.io/blob/main/.cspell/es-palabras.txt

2024-10-04 07:37 UTC, theletterf commented on content/es/docs/concepts/observability-primer.md
> +## ¿Qué es la Observabilidad?
```suggestion
## ¿Qué es la observabilidad?
```

2024-10-04 07:37 UTC, theletterf commented on content/es/docs/concepts/observability-primer.md
> +zapatos negros, entonces el sistema podría ser **no** confiable.
```suggestion
tiempo, pero si, cuando un usuario hace clic en "Agregar al carrito" para añadir
un par de zapatos negros a su carrito, el sistema no siempre agrega los
zapatos negros, entonces el sistema podría ser **no** confiable.
```

2024-10-04 07:37 UTC, theletterf commented on content/es/docs/concepts/observability-primer.md
> +sobre tu infraestructura o aplicación. Ejemplos incluyen: tasa de error del
```suggestion
sobre tu infraestructura o aplicación. Por ejemplo: tasa de error del
```

2024-10-04 07:37 UTC, theletterf commented on content/es/docs/concepts/observability-primer.md
> +[otros metadatos (es decir, Atributos)](/docs/concepts/signals/traces/#attributes)
```suggestion
[otros metadatos (es decir, atributos)](/docs/concepts/signals/traces/#attributes)
```

2024-10-04 11:32 UTC, mlunadia commented
Gracias @theletterf por las sugerencias!

2024-10-04 15:41 UTC, theletterf commented
@mlunadia The spelling errors are still there, please check them out.

2024-10-04 15:46 UTC, mlunadia commented
@theletterf ah, got it. added them to the txt file, pending [PR](https://github.com/open-telemetry/opentelemetry.io/pull/5320) approval.

2024-10-05 16:18 UTC, theletterf approved these changes

2024-10-05 16:22 UTC, theletterf commented
/fix:format

2024-10-05 16:35 UTC, merged