[pt-br] Pagina das linguagens - JS (Brazil)
open-telemetry/opentelemetry.io pull request #5324
Opened 2024-10-04 21:01 UTC by leandrocarpenter

## Docs PR Checklist
Tradução das Seguintes páginas:

* content/pt/docs/languages/js/getting-started/_index.md
* content/pt/docs/languages/js/getting-started/browser.md
* content/pt/docs/languages/js/_index.md

2024-10-10 13:16 UTC, maryliag commented
Faltou associar com uma issue também, caso a issue ainda não exista, por favor criá-la. Lembrando de fazer uma issue por PR e por arquivo (quando são arquivos pequenos, tudo bem ser mais de um relacionado por PR)

2024-10-12 01:00 UTC, emdneto requested changes
Ajustar de acordo com os comentários. Movendo pra draft pra evitar merge errado

2024-10-21 13:32 UTC, edsoncelio commented
@leandrocarpenter esse PR é uma versão antiga desse aqui https://github.com/open-telemetry/opentelemetry.io/pull/5415, correto?
Se sim, pode fechar esse, por favor?

2024-10-21 18:03 UTC, leandrocarpenter commented
@edsoncelio sim sim.
Vou encerrar esse e vamos tratar no #5415 https://github.com/open-telemetry/opentelemetry.io/pull/5415

2024-10-21 18:03 UTC, closed without merging