feat: [es] Create docs/languages/js/_index.md
open-telemetry/opentelemetry.io pull request #5327
Opened 2024-10-05 06:38 UTC by oayras

Related issue https://github.com/open-telemetry/opentelemetry.io/issues/5229

2024-10-05 16:12 UTC, theletterf reviewed
¡Gracias! Un par de comentarios tan solo.

2024-10-05 16:12 UTC, theletterf commented on content/es/docs/languages/js/_index.md
> +  JavaScript (for Node.js & the browser).
Podemos traducir esta descripción.

2024-10-05 16:12 UTC, theletterf commented on content/es/docs/languages/js/_index.md
> +{{% docs/languages/index-intro js /%}}
¿Está traducida esta nota?

2024-10-05 16:39 UTC, oayras commented on content/es/docs/languages/js/_index.md
> +{{% docs/languages/index-intro js /%}}
De acuerdo @theletterf, las actualizare.

2024-10-08 05:30 UTC, theletterf commented
+CC @krol3

2024-10-08 10:31 UTC, xrmx approved these changes

2024-10-08 23:49 UTC, ferd approved these changes

2024-10-09 00:05 UTC, kaylareopelle approved these changes

2024-10-30 08:21 UTC, theletterf commented
@oayras Could you check the comments? Thanks!

2024-10-31 03:14 UTC, oayras commented
> @oayras Could you check the comments? Thanks!

@theletterf, in the following commits, I’ve corrected the observations you made previously: I translated the description and the shortcode. Could you let me know if you have any further feedback, please?

2024-11-02 18:31 UTC, theletterf approved these changes

2024-11-03 04:52 UTC, oayras commented
Issues in I18N check fixed and conflict from merge was resolved!

2024-11-04 07:09 UTC, theletterf commented
/fix:all

2024-11-06 03:09 UTC, oayras commented
default_lang_commit value was fixed

2024-11-13 11:11 UTC, chalin requested changes

2024-11-13 11:11 UTC, chalin commented on layouts/shortcodes/docs/languages/index-intro.md
Thanks for the code here. Let me see if there's a better way to address this without having to add an extra parameter.

2024-11-13 11:11 UTC, chalin commented on layouts/shortcodes/docs/languages/index-intro.md
Let me investigate if we can achieve the same result without introducing an extra parameter.

2024-11-13 11:28 UTC, chalin commented on layouts/shortcodes/docs/languages/index-intro.md
> +{{ $translation := .Get 1 -}}
Please accept the following change, and then revert all of the "en" argument additions to the `en` pages:

```suggestion
{{ $translation := .Get 1 | default "en" -}}
```

2024-11-13 11:32 UTC, chalin commented
> This PR needs to be **rebased**. /cc @theletterf

Done.

2024-11-13 11:38 UTC, chalin commented
@theletterf et all: in general, please tag me on localization PRs that have such a "broad" (cross-localization) impact and/or changes to shared layouts so that we can together assess and discuss design alternatives.

Hugo has built-in support for i18n, in the way that you've implemented it here. So we don't need to re-implement our own localization tag support.

I need to think about this a bit more before I can make some concrete suggestions. Stay tuned!

2024-11-13 13:38 UTC, chalin requested changes
After thinking about this more, for the moment, I'd rather that each locale create it's own version of the shortcode, like this: [layouts/shortcodes/pt/docs/languages/index-intro.md](https://github.com/open-telemetry/opentelemetry.io/blob/main/layouts/shortcodes/pt/docs/languages/index-intro.md).

There are pros and cons to this approach, vs. the i18n-tag approach you've suggested here (which, if we were to adopt, I'd suggest rewriting so that we use Hugo's native support). For now, I'm voting for the per-locale shortcode approach, but I'm open to discussing this more with @open-telemetry/docs-es-approvers if they feel strongly about the alternative.

@open-telemetry/docs-approvers - please also share your opinion.

2024-12-09 18:43 UTC, krol3 requested changes

2024-12-09 18:43 UTC, krol3 commented on layouts/shortcodes/docs/languages/index-intro.md
> +{{ $traces := $content.introPage.releases.traces }}
```suggestion
{{ $traces := $content.introPage.releases.traces }}
```
@oayras gracias por tu contribucion, seria un abordage mas simples, traduzir el texto, sin necesitad de agregar nuevos archivos en `data/languages/en.yaml`.  Por favor intentar este abordage, y podemos hacer un zoom. Por favor escribeme en el slack

2024-12-10 14:39 UTC, emdneto approved these changes

2025-01-10 08:19 UTC, theletterf commented
Closing as issues weren't addressed.

2025-01-10 08:19 UTC, closed without merging