[outreachy] Registry: Put items into sections
open-telemetry/opentelemetry.io pull request #5348
Opened 2024-10-08 13:32 UTC by Beccamak

@svrnm I have created sections for the major categories on the registry page. 
For view all links, I had to use the search functionality that was already implemented. Initially, I thought that on the backend, there was an identifier or tag for entries that easily identifies them as plugins, libraries, or instrumentations. The plan was to have all these categories filtered out and then on clicking "view all" they are populated. 

However, after some interactions with the codebase, I didn't see that there. I noticed that if I had to get a category out (for example, the libraries), it had to be through a search (the fuzzy search the system is using), and I couldn't find a way of passing the filtered results back to the template,  which I think explains why the whole entries were initially inserted on the registry page. The keys were compared to filter out the keys (entries) that didn't match the keys (entries) in the returned search results on the DOM. 

Kindly let me know your thoughts on this.

2024-10-09 08:58 UTC, svrnm requested changes
This is a really good start, thank you.

A few inline comments. Most of them are related to changes you have applied to files that shouldn't be there. You might be able to revert all of them by running `npm run fix:format` locally.

A few more comments:
* I understand why you did it that way (we say "libraries, plugins, integrations"), but by applying a search on those items you get a selection of items that not always fits the description. This is OK for now, but we need to think about addressing that differently. I will think about that
* The links at the bottom of an item are off, can you take a look that they are in line with the rest of the element?
* If I make the screen size smaller the elements become very thin, I think it should switch to 1 item per row with an earlier width-selector

2024-10-09 08:58 UTC, svrnm commented on content/en/ecosystem/registry/_index.md
this change is unrelated, please undo it

2024-10-09 08:58 UTC, svrnm commented on layouts/partials/ecosystem/registry/entry.html
> +        $remoteRegistries := dict
revert this unrelated change

2024-10-09 08:58 UTC, svrnm commented on layouts/shortcodes/ecosystem/registry/search-form.html
> +
remove

2024-10-09 08:58 UTC, svrnm commented on layouts/shortcodes/ecosystem/registry/search-form.html
> +
remove

2024-10-09 09:26 UTC, Beccamak commented on content/en/ecosystem/registry/_index.md
@svrnm Thank you for taking the time to review and for your feedback. 

- Just to be sure I understand you well, you said, "...but by applying a search on those items you get a selection of items that not always fits the description. This is OK for now, but we need to think about addressing that differently...", were you referring to the already existing search functionality?
- For the links, I'll take a look at them and make fixes as soon as possible.
- Sincere apologies for the responsiveness, I only checked on Desktop and mobile. I'll work on that too.
- Also, for [content/en/ecosystem/registry/_index.md](https://github.com/open-telemetry/opentelemetry.io/pull/5348/files/997d3c550e9c79dadcfda2f9a6a2c74c821d9522#diff-a6511056b88cb6dd90f17707ea99f2de5886b5088aff728c3cc0c6c23849f52f) you said, "this change is unrelated, please undo it", do you mean I should delete this "{{< ecosystem/registry/categories>}}?

2024-10-09 10:00 UTC, svrnm commented on content/en/ecosystem/registry/_index.md
>     * Just to be sure I understand you well, you said, "...but by applying a search on those items you get a selection of items that not always fits the description. This is OK for now, but we need to think about addressing that differently...", were you referring to the already existing search functionality?

What I tried to express is the following: you are currently applying searches for "plugin", "library", etc to generate the catagories. Which is great because it matches the description above. But the underlying data is not matching that, so we need to address that, otherwise the lists per category are not matching what end users might expect. I'll think about that and come back with a suggestion

>     * Sincere apologies for the responsiveness, I only checked on Desktop and mobile. I'll work on that too.

No need to apologize, this is a normal review, where another person is calling out places to improve/requirements that should be met. This is great progress!

>     * Also, for [content/en/ecosystem/registry/_index.md](https://github.com/open-telemetry/opentelemetry.io/pull/5348/files/997d3c550e9c79dadcfda2f9a6a2c74c821d9522#diff-a6511056b88cb6dd90f17707ea99f2de5886b5088aff728c3cc0c6c23849f52f) you said, "this change is unrelated, please undo it", do you mean I should delete this "{{< ecosystem/registry/categories>}}?

Oh no, I marked too much, remove the additional empty lines (should be fixed via the fix:format)

2024-10-09 10:27 UTC, Beccamak commented on content/en/ecosystem/registry/_index.md
@svrnm Thank you, this is well understood. I'll be looking forward to your feedback.

2024-10-11 16:31 UTC, Beccamak commented
@svrnm I trust you're doing fine. Happy weekend.

I have made the changes you requested. I noticed some of those cards weren't displaying the quick install code so I worked on it. Also, would you advise that all the cards being displayed have a "quick install" to ensure all components are aligned together? 

This is also a gentle reminder for the suggestion regarding the "search that returns items that do not always fit the description".

2024-10-14 13:28 UTC, svrnm commented
Thank you @beccamak! This looks really good, I consider this as done! 

The changes required for making this work with the current solution is out of scope for your work. When the application phase for outreachy is over, we can revisit this and talk about making this work, if you want to, but since we do not merge PRs until the end of the application phase, let's keep it as is.

2024-10-14 13:36 UTC, Beccamak commented
@svrnm  Thank you so much. This is well noted and understood. I've learned a lot by just trying to implement some of those things. I'll move on to selecting an optional task now. 
Thank you so much for your time.

2024-11-22 10:59 UTC, svrnm commented
While I still like the idea of this PR, I am yet unsure how to incorporate it. The categories "Libraries, Plugins, Integrations" do not work, since they do not match any of the categories we have as of today, but we could do "Instrumentation Libraries, "Collector Components", "Application Integrations" and a few other ones more fitting. This would also allow us to add some words and explaining them better.

cc @open-telemetry/docs-approvers WDYT?

2024-11-26 10:48 UTC, Beccamak commented
@svrnm Yes, I'm still interested in helping out.

2024-12-04 15:54 UTC, svrnm commented
A few thoughts on that:
1. we should feature Instrumentation Library, Collector Components and maybe Utilities. Each one of them should also have a small top paragraph letting the end user know what will get from them, what they are etc (I can help with that)
2. the items for section should be minimal, such that it is visible to a user that there are multiple sections. maybe only the name, the description and a "more" link that can expand the details?

2024-12-10 13:22 UTC, Beccamak commented
@svrnm Looking at the first suggestion, we want to have a small top paragraph for Instrumentation Library, Collector Components and Utilities letting the end user know what they will get from them, what they are etc... right?

So that would come before the search bar?

2025-01-20 10:42 UTC, svrnm commented
@Beccamak any thoughts on my previous comment?

2025-03-17 09:26 UTC, closed without merging