feat: localized apis and sdks languages for pt-br
open-telemetry/opentelemetry.io pull request #5393
Opened 2024-10-11 22:27 UTC by samyev

Localized [Language APIs & SDKs](https://opentelemetry.io/docs/languages/) session for the Portuguese language.

close #5366

2024-10-12 00:03 UTC, emdneto approved these changes

2024-10-12 00:06 UTC, emdneto commented
/fix:all

2024-10-12 00:15 UTC, emdneto requested changes
Obrigado pelo PR. Deixei alguns comentários. Acho que só corrigir os erros ali da CI :v:

2024-10-12 00:15 UTC, emdneto commented on content/pt/docs/languages/_index.md
> +Sem considerar o status de um API/SDK, se a sua instrumentação depende de [convenções
Talvez substituir o Sem considerar por Independente?

2024-10-12 00:15 UTC, emdneto commented on content/pt/docs/languages/_index.md
> +e do SDK do OpenTelemetry em diferentes linguagens, também disponibilizam referências
Acho que tá faltando uma conexão aqui com o "também"

2024-10-12 01:07 UTC, emdneto commented on content/pt/docs/languages/_index.md
> +na tabela de [Status e Lançamentos](#status-e-lançamentos) abaixo. Implementações não
```suggestion
na tabela de [Estado e Lançamentos](#status-e-lançamentos) abaixo. Implementações não 
```

2024-10-12 03:16 UTC, maryliag reviewed
Obrigada pela contribuição! Deixei alguns comentários

2024-10-12 03:16 UTC, maryliag commented on content/pt/docs/languages/_index.md
> +A instrumentação de código do OpenTelemetry é suportada para as linguagens listadas
Está faltando o link aqui para `instrumentação`, como tem no original

2024-10-12 03:16 UTC, maryliag commented on content/pt/docs/languages/_index.md
> +Você pode encontrá-las no [registry](/ecosystem/registry/).
```suggestion
Você pode encontrá-las no [registro](/ecosystem/registry/).
```

2024-10-12 03:16 UTC, maryliag commented on content/pt/docs/languages/_index.md
> +Sem considerar o status de um API/SDK, se a sua instrumentação depende de [convenções
```suggestion
Independente do estado de um API/SDK, se a sua instrumentação depende de [convenções
```

+1

2024-10-12 03:16 UTC, maryliag commented on content/pt/docs/languages/_index.md
> +semânticas], seu fluxo de dados pode estar sujeito a **quebra de compatibilidade**
```suggestion
semânticas], seu fluxo de dados pode estar sujeito à **quebra de compatibilidade**.
```

2024-10-12 03:16 UTC, maryliag commented on content/pt/docs/languages/_index.md
> +Os Grupos de Interesse Especial (SIGs), são os responsáveis pela implementação da API
```suggestion
Os Grupos de Interesse Especial (SIGs) que implementam a API 
```

2024-10-12 03:16 UTC, maryliag commented on content/pt/docs/languages/_index.md
> +e do SDK do OpenTelemetry em diferentes linguagens, também disponibilizam referências
```suggestion
e o SDK do OpenTelemetry em diferentes linguagens, também disponibilizam referências 
```

2024-10-12 03:16 UTC, maryliag commented on content/pt/docs/languages/_index.md
> +e do SDK do OpenTelemetry em diferentes linguagens, também disponibilizam referências
SDK  = Software Development Kit = Kit de Desenvolvimento de Software, então é masculino mesmo

2024-10-12 12:35 UTC, emdneto commented on content/pt/docs/languages/_index.md
> +e do SDK do OpenTelemetry em diferentes linguagens, também disponibilizam referências
Vdd, eu sempre falo a API e a SDK, mas deve ser "o" e "do" mesmo. :v:

2024-10-13 13:21 UTC, samyev commented
@maryliag @emdneto Bom dia! Muito obrigada pelas correções, já realizei as alterações, e deixei comentários no [glossário](https://docs.google.com/document/d/1kyu6HgdsM3-iDyf3OuRmfw4SwNJy9BVui6nn5JsKb5I/edit?tab=t.0) sobre a localização da palavra `Registry` ser alterada para `Registro`, e sobre a inserção da palavra `Status` para ser localizada para `Estado` pois foram dúvidas que tive e acabei me baseando por lá ^^

2024-10-15 23:19 UTC, maryliag approved these changes
Obrigada por atualizar o glossário também!

2024-10-15 23:21 UTC, maryliag requested changes
Tem alguns tests falhando, você precisa rodar o linter pra arrumar estes erros

2024-10-16 00:58 UTC, samyev commented
> Tem alguns tests falhando, você precisa rodar o linter pra arrumar estes erros

Obrigada, ajustado! Você poderia revisar novamente?

2024-10-16 01:39 UTC, maryliag approved these changes

2024-10-16 05:53 UTC, svrnm requested changes

2024-10-16 05:53 UTC, svrnm commented on content/pt/docs/languages/_index.md
> +listadas na tabela de [Estado e Lançamentos](#estado-e-lançamentos) abaixo.
Do not translate heading anchors, see https://opentelemetry.io/docs/contributing/localization/#heading-anchors

2024-10-16 05:53 UTC, svrnm commented on content/pt/docs/languages/_index.md
> +## Estado e Lançamentos
```suggestion
## Estado e Lançamentos {#original-english-id}
```
See above and https://opentelemetry.io/docs/contributing/localization/#heading-anchors

2024-10-23 01:23 UTC, samyev commented
Olá @maryliag @emdneto, tudo bem? O que ainda está faltando neste pr para ele ser aprovado? Vocês poderiam me ajudar? ><

2024-10-23 14:12 UTC, svrnm approved these changes

2024-10-23 14:12 UTC, svrnm commented
@emdneto your review is still on "changes requested", can you take a look and unblock the PR? Happy to merge it

2024-10-23 14:43 UTC, emdneto approved these changes

2024-10-23 14:47 UTC, svrnm commented
One more thing, the link checker is reporting the following:

```
  hash does not exist --- pt/docs/languages/index.html --> #status-and-releases
```

2024-10-24 01:24 UTC, samyev commented
> One more thing, the link checker is reporting the following:
> 
> ```
>   hash does not exist --- pt/docs/languages/index.html --> #status-and-releases
> ```

Thanks! Could you approve the workflow execution to check if it's fixed?

2024-10-24 08:59 UTC, svrnm commented
geat work, thank you @samyev !

2024-10-24 09:03 UTC, merged