updates: fixed mobile ui/ux issues in registry page
open-telemetry/opentelemetry.io pull request #5403
Opened 2024-10-14 16:21 UTC by kemsguy7

This pr resolves issue: #5318  where i resolved some ux issues on the mobile view of the registry page. 

### **Key changes** 

- ***
- Changed display of filters and search input fields to flex column display for better visual alignment
- Fixed overflowing pill by taking it to a new line and reducing the font size

### **Demo**

https://github.com/user-attachments/assets/5ec7bff9-2fbf-4425-a38a-fff13bb63de0

2024-10-14 16:23 UTC, kemsguy7 commented
@svrnm , please kindly review

2024-10-15 06:49 UTC, svrnm requested changes
looks good overall, thank you. One additional thing: If there are multiple links at the bottom of an element, the links are not in line (see screenshot below)

<img width="365" alt="Screenshot 2024-10-15 at 08 46 21" src="https://github.com/user-attachments/assets/ec422a79-8f28-4cfc-acff-69c26f01b196">

2024-10-15 06:49 UTC, svrnm commented on assets/scss/_registry.scss
> +      background-color: $color;
```suggestion
      background-color: $color;
```

2024-10-15 16:03 UTC, kemsguy7 commented
@svrnm , i've applied a fix to this issue, kindly find attached a screenshot
<img width="359" alt="Screenshot 2024-10-15 at 17 03 03" src="https://github.com/user-attachments/assets/18acf820-8936-4bb0-9a7f-80f5e6e85a36">


> looks good overall, thank you. One additional thing: If there are multiple links at the bottom of an element, the links are not in line (see screenshot below)
> 
> <img alt="Screenshot 2024-10-15 at 08 46 21" width="365" src="https://private-user-images.githubusercontent.com/1519757/376489248-ec422a79-8f28-4cfc-acff-69c26f01b196.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMDg0MTUsIm5iZiI6MTcyOTAwODExNSwicGF0aCI6Ii8xNTE5NzU3LzM3NjQ4OTI0OC1lYzQyMmE3OS04ZjI4LTRjZmMtYWNmZi02OWMyNmYwMWIxOTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTVUMTYwMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTkxMjQzZWUwN2VhZDFlYjZiMmRlMzM0ZjE2NDNhMGY2MmI1MTU4M2E5OWVmYmRmZTk2MmZmN2FjNTgzN2MyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PPaVhaPCyDhrG9xfZkUyYwMIaptHk23myRCBNi9sG4U">

2024-10-16 06:18 UTC, svrnm commented
Minor issue, but beyond that this looks good!

When you have applied that minor change, I consider this as done! After the outreachy application phase we will take another look and see if we can merge this PR.

2024-10-16 07:21 UTC, kemsguy7 commented on layouts/partials/ecosystem/registry/entry.html
> +{{ end -}}
@svrnm  please what fix exactly do you need here?   the linting?

2024-10-16 07:44 UTC, svrnm commented on layouts/partials/ecosystem/registry/entry.html
> +{{ end -}}
Add an empty line at the bottom of the file

2024-10-16 07:44 UTC, svrnm commented on layouts/partials/ecosystem/registry/entry.html
> +{{ end -}}
Note that you might be able to auto fix that by running `npm run:format` locally

2024-10-16 08:39 UTC, kemsguy7 commented on layouts/partials/ecosystem/registry/entry.html
> +{{ end -}}
oh! @svrnm , thanks for this. I'm on it.

2024-10-16 08:43 UTC, kemsguy7 commented on layouts/partials/ecosystem/registry/entry.html
> +{{ end -}}
@svrnm fixed, please review

2024-10-16 08:44 UTC, kemsguy7 commented on assets/scss/_registry.scss
> +      background-color: $color;
@svrnm do i add a space here too?

2024-10-16 09:46 UTC, svrnm commented on layouts/partials/ecosystem/registry/entry.html
> +{{ end -}}
```suggestion
  {{ end -}}
```

2024-12-11 13:45 UTC, svrnm commented
@kemsguy7 following up on this. Are you interested in continuing with this? If so, I would like to focus on "Changed display of filters and search input fields to flex column display for better visual alignment" and keep the other optimization out for now. Can you update this PR or create a new PR to address that? 

Thanks

2025-01-20 10:45 UTC, closed without merging

2025-01-20 10:45 UTC, svrnm commented
@kemsguy7 I am closing this PR now, if you want to continue working on this, please open a new PR or reopen this one. Thanks