Blog post for KubeCon NA 2024
open-telemetry/opentelemetry.io pull request #5404
Opened 2024-10-15 08:20 UTC by svrnm

fixes #5278

@open-telemetry/sig-end-user-approvers please take a look for the section around the observatory. This years EU blog post had some more details on schedule, surveys, humans of OTel, so let me know which of these I can include

2024-10-24 15:15 UTC, svrnm commented
/fix:all

2024-10-28 02:33 UTC, reese-lee requested changes
Added a few comment/suggestions. Thank you, Severin!

2024-10-30 18:27 UTC, reese-lee commented on content/en/blog/2024/kubecon-na.md
> +
The schedule is coming together! Can you please add the following info about these 2 new session types we're hosting:

> New for this year! 
> * **SIG Office Hours**: Come meet the people behind the project, learn about their work, ask questions, share feedback, or find out how to contribute. 
> * **Special Topic Discussions**: Come learn about two of the _hottest_ OTEPs right now, Events and Entities!

2024-11-04 15:16 UTC, svrnm commented on content/en/blog/2024/kubecon-na.md
> +discussions led by OpenTelemetry community members and maintainers.
I added a note

2024-11-04 15:16 UTC, svrnm commented on content/en/blog/2024/kubecon-na.md
> +to indicate your interest.
done

2024-11-04 15:16 UTC, svrnm commented on content/en/blog/2024/kubecon-na.md
> +discussions led by OpenTelemetry community members and maintainers.
done

2024-11-04 15:58 UTC, chalin approved these changes
Thanks @svrnm.
Let's get this out ASAP.

2024-11-04 16:00 UTC, chalin commented
@reese-lee - can you give this a final review & approval?

2024-11-04 21:07 UTC, reese-lee approved these changes
Looks great to me, thank you Severin and Patrice!

2024-11-04 21:18 UTC, avillela requested changes
A couple of minor fixes. Othwerwise, looks good!

2024-11-04 21:18 UTC, avillela commented on content/en/blog/2024/kubecon-na.md
> +[#otel-user-research][] in CNCF's Slack instance for results and action item
```suggestion
[#otel-sig-end-user][] in CNCF's Slack instance for results and action item
```

2024-11-04 21:18 UTC, avillela commented on content/en/blog/2024/kubecon-na.md
> +[#otel-user-research]: https://cloud-native.slack.com/archives/C01RT3MSWGZ
```suggestion
[#otel-sig-end-user]: https://cloud-native.slack.com/archives/C01RT3MSWGZ
```

2024-11-04 21:19 UTC, avillela approved these changes

2024-11-05 07:09 UTC, merged