Tradução JS - Getting Started
open-telemetry/opentelemetry.io pull request #5415
Opened 2024-10-16 00:03 UTC by leandrocarpenter

## Docs PR Checklist

* Tradução inicial do Getting Started.
* Paginas:
 * _index.md
 * browser.md
 * nodejs.md

- [ ] This PR is for a documentation page whose authoritative copy is in the
      opentelemetry.io repository.

2024-11-02 19:42 UTC, edsoncelio commented
Hey @leandrocarpenter, um detalhe antes de conseguirmos revisar seu PR:
* precisa adicionar o campo `default_lang_commit` nos arquivos que traduziu, pode ver detalhes de como fazer isso no [nosso guia de contribuição](https://edsoncelio.github.io/otel-localization-ptbr-guide/)

Pode nos avisar por aqui (ou slack) quando isso tiver sido feito, por favor? Obrigado!

2024-11-02 19:44 UTC, edsoncelio requested changes

2024-11-02 19:44 UTC, edsoncelio commented on content/pt/docs/languages/js/getting-started/browser.md
> +e abra o sevidor de desenvolvimento web (e.g. at `http://localhost:1234`) para ver o se código funciona.
```suggestion
e abra o servidor de desenvolvimento web (e.g. at `http://localhost:1234`) para ver o se código funciona.
```

2024-11-02 19:44 UTC, edsoncelio commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +JavaScript com outras estruturas da web também, como Koa e Nest.JS. Para uma lista completa de blibliotecas para frameworks suportados, veja o
```suggestion
JavaScript com outras estruturas da web também, como Koa e Nest.JS. Para uma lista completa de bibliotecas para frameworks suportados, veja o
```

2024-11-02 19:44 UTC, edsoncelio commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +O `auto-instrumentação-node` pacote instala as bibliotecas de instrumentação que irão criar automaticamente Trechos correspondentes ao código chamado em bibliotecas. Neste caso, ele fornece instrumen
```suggestion
O `auto-instrumentação-node` pacote instala as bibliotecas de instrumentação que irão criar automaticamente Trechos correspondentes ao código chamado em bibliotecas. Neste caso, ele fornece instrumentação para o Express, permitindo que o aplicativo de exemplo crie automaticamente intervalos para cada solicitação recebida.
```

2024-11-05 23:47 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +    -->
```suggestion
    <!--
      https://www.w3.org/TR/trace-context/
      Defina o `traceparent` no código do template HTML do servidor. 
      Ele deve ser gerado dinamicamente no lado do servidor para conter o 
      trace Id da requisição do servidor, um span Id de pai que foi definido 
      no span de requisição do servidor, e as flags de rastreamento para 
      indicar a decisão de amostragem do servidor (01 = amostrado, 00 = não amostrado).
      '{version}-{traceId}-{spanId}-{sampleDecision}'
    -->

```

2024-11-05 23:51 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +Crie um arquivo de código vazio chamado `document-load` com um `.ts` ou `.js` extensão,
```suggestion
Crie um arquivo de código vazio chamado `document-load` com a extensão `.ts` ou `.js`,
```

Acha que assim fica melhor?

2024-11-05 23:53 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +/* document-load.ts|js file - the code snippet is the same for both the languages */
```suggestion
/* document-load.ts|js arquivo - o trecho de código é o mesmo para ambas as linguagens */
```

2024-11-06 00:00 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +  // Changing default contextManager to use ZoneContextManager - supports asynchronous operations - optional
```suggestion
  // Alterando o contextManager padrão para usar ZoneContextManager - oferece suporte para operações assíncronas - opcional
```

2024-11-06 00:01 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +// Registering instrumentations
```suggestion
// Registrando instrumentações
```

2024-11-06 00:01 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +e abra o servidor de desenvolvimento web (e.g. at `http://localhost:1234`) para ver se o seu código funciona.
```suggestion
E abra o servidor de desenvolvimento web (e.g. at `http://localhost:1234`) para ver se o seu código funciona.
```
Esse `e` deveria ser maiúsculo ou minusculo?

2024-11-06 00:03 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +spans no console.
```suggestion
trechos no console.
```

2024-11-06 00:04 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +Você também pode querer usar o `BatchSpanProcessor` para exportar trechos em lotes para usar os recursos de forma mais eficiente..
```suggestion
Você também pode querer usar o `BatchSpanProcessor` para exportar trechos em lotes para usar os recursos de forma mais eficiente.
```

2024-11-06 00:06 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +/* document-load.ts|js file - the code is the same for both the languages */
```suggestion
/* document-load.ts|js arquivo - o código é o mesmo para ambas as linguagens */
```

2024-11-06 00:07 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +  // Changing default contextManager to use ZoneContextManager - supports asynchronous operations - optional
```suggestion
  // Alterando o contextManager padrão para usar ZoneContextManager - oferece suporte para operações assíncronas - opcional
```

2024-11-06 00:07 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +// Registering instrumentations
```suggestion
// Registrando instrumentações
```

2024-11-06 00:10 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +registrar instrumentações adicionais para eles:
```suggestion
Caso deseje instrumentar solicitações Ajax, interações do usuário e outros, é possível registrar instrumentações adicionais para esses elementos:
```
Acha que assim fica melhor?

2024-11-06 00:11 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +Você aprenderá como instrumentar [traços][] e [métricas][] e registrá-los
```suggestion
Você aprenderá como instrumentar [rastros][] e [métricas][] e registrá-los
```
Acho que aqui deveria ser rastros.

2024-11-06 00:12 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +{{% alert title="Note" color="info" %}} A biblioteca de registro para OpenTelemetry
Parei a revisão aqui, contiuarei em outro momento.

2024-11-20 20:18 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +Certifique-se de ter o seguinte instalado localmente:
```suggestion
Certifique-se de ter os seguinte itens instalados localmente:
```
Talvez fique melhor assim.

2024-11-20 20:20 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +[registry](/ecosystem/registry/?component=instrumentation&language=js).
```suggestion
[registro](/ecosystem/registry/?component=instrumentation&language=js).
```
Você traduziu registry anteriormente.

2024-11-20 20:22 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +aplicação. Se você não estiver usando o Express, está OK — você pode usar OpenTelemetry
```suggestion
O exemplo a seguir utiliza uma aplicação básica com [Express](https://expressjs.com/). 
Se você não estiver usando o Express, está OK — você pode usar OpenTelemetry
```

2024-11-20 20:24 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +Para começar, configure um em branco `package.json` em um novo diretório:
```suggestion
Para começar, configure um arquivo vazio `package.json` em um novo diretório:
```

2024-11-20 20:26 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +Crie um arquivo chamado `app.ts` (ou `app.js` se você não estiver usando TypeScript) e adicione o seguinte código a ele:
```suggestion
Crie um arquivo chamado `app.ts` (ou `app.js` se você não estiver usando TypeScript) e adicione o seguinte código:
```
Acho que o pronome não é necessário aqui.

2024-11-20 20:28 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +Execute o aplicativo com o seguinte comando e abra
```suggestion
Execute o aplicativo com o seguinte comando e acesse
```
Não sei se acesse fica melhor que abra.

2024-11-20 20:31 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +código de aplicação. Uma ferramenta frequentemente utilizada para essa tarefa é a
```suggestion
A configuração e preparação da instrumentação devem ser executadas _antes_ do
código da sua aplicação. Uma ferramenta frequentemente utilizada para essa tarefa é a
```

2024-11-20 20:35 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +Abra <http://localhost:8080/rolldice> no seu navegador e recarregue a página
```suggestion
Acesse <http://localhost:8080/rolldice> no seu navegador e recarregue a página
```
Mesmo caso do comentário anterior.

2024-11-20 20:36 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +Envie mais algumas solicitações para o endpoint. Depois de um momento, você verá métricas na saída do console, como o seguinte:
```suggestion
Envie mais algumas solicitações para o endpoint. Depois de um tempo, você verá métricas na saída do console, como o seguinte:
```
Talvez tempo faça mais sentido.

2024-11-20 20:38 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +[Demonstração OpenTelemetry ](/docs/demo/), que inclui o JavaScript baseado
```suggestion
[Demonstração OpenTelemetry](/docs/demo/), que inclui o JavaScript baseado
```

2024-11-20 20:39 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +Algo deu errado ? Você pode habilitar o registro de diagnóstico para validar que o
```suggestion
Algo deu errado? Você pode habilitar o registro de diagnóstico para validar que o
```

2024-11-20 20:39 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +// For troubleshooting, set the log level to DiagLogLevel.DEBUG
```suggestion
// Para solução de problemas, defina o nível de log como DiagLogLevel.DEBUG
```

2024-11-20 20:40 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +// Require dependencies
```suggestion
// Requer dependências
```

2024-11-20 20:40 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +// For troubleshooting, set the log level to DiagLogLevel.DEBUG
```suggestion
// Para solução de problemas, defina o nível de log como DiagLogLevel.DEBUG
```

2024-11-20 20:41 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +[Metricas]: /docs/concepts/signals/metrics/
```suggestion
[Métricas]: /docs/concepts/signals/metrics/
```

2024-11-20 20:42 UTC, EzzioMoreira commented
@leandrocarpenter deixei meu comentário.

2024-11-20 20:44 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +## Pré-requisitos
```suggestion
## Pré-requisitos {#prerequisites}
```
Adiciona ancora

2024-11-20 20:45 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +## Exemplo de Aplicação
```suggestion
## Exemplo de Aplicação {#example-application}
```

2024-11-20 20:47 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +### Instalação
```suggestion
### Instalação {$installation}
```

2024-11-20 20:47 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +### Inicialização e Configuração
```suggestion
### Inicialização e Configuração {#initialization-and-configuration}
```

2024-11-20 20:48 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +### Criando um Provedor de Rastros
```suggestion
### Criando um Provedor de Rastros {#creating-a-tracer-provider}
```

2024-11-20 20:48 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +### Criando um Exportador
```suggestion
### Criando um Exportador {#creating-an-exporter}
```

2024-11-20 20:48 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +### Adicionar Instrumentações
```suggestion
### Adicionar Instrumentações {#add-instrumentations}
```

2024-11-20 20:49 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/browser.md
> +## Meta Pacotes para Web
```suggestion
## Meta Pacotes para Web {#meta-packages-for-web}
```

2024-11-20 20:50 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +## Pré-requisitos
```suggestion
## Pré-requisitos {#prerequisites}
```

2024-11-20 20:51 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +### Crie e inicie um servidor HTTP
```suggestion
### Crie e inicie um servidor HTTP {#create-and-launch-an-http-server}
```

2024-11-20 20:51 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +## Instrumentação
```suggestion
## Instrumentação {#instrumentation}
```

2024-11-20 20:52 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +### Mais dependências
```suggestion
### Mais dependências {#more-dependencies}
```

2024-11-20 20:52 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +### Configurar
```suggestion
### Configurar {#setup}
```

2024-11-20 20:53 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +## Execute o aplicativo instrumentado
```suggestion
## Execute o aplicativo instrumentado {#run-the-instrumented-app}
```

2024-11-20 20:54 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +## Próximos passos
```suggestion
## Próximos passos {#next-steps}
```

2024-11-20 20:54 UTC, EzzioMoreira commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +## Soluções de Problemas
```suggestion
## Soluções de Problemas {#troubleshooting}
```

2024-11-21 19:00 UTC, maryliag commented on content/pt/docs/languages/js/getting-started/nodejs.md
> +[Metricas]: /docs/concepts/signals/metrics/
```suggestion
[métricas]: /docs/concepts/signals/metrics/
```

2024-12-18 09:45 UTC, svrnm commented
@leandrocarpenter can you take a look at the feedback provided? Thanks

2025-01-12 16:55 UTC, edsoncelio commented
Closing this PR due to the lack of an answer. 
Feel free to reopen it or send a message in our slack channel (`#glossary-localization-portuguese`).

2025-01-12 16:55 UTC, closed without merging