Resizing of cards
open-telemetry/opentelemetry.io pull request #5421
Opened 2024-10-16 21:23 UTC by DIANAAJAMBO

This task resolves issue #5335 and below are the changes that i made to this effect.

**Card Layout**

- Resized cards to fit better within the available space.
- Replaced text next to icons with tooltips for a cleaner look.
- Adjusted font size to match the new card dimensions.

**Link Styling**

- Removed underlines from the links for a cleaner design.
- Applied different colors to titles and authors for clear visual differentiation.

**Card Interactivity**

- Added hover effects to make the cards interactive and engaging for users.

**Responsive Design**

- Made the layout mobile-friendly by ensuring the cards are responsive on various devices, including tablets, computers, and phones.

**Card Identification**

- Kept the original border colors to maintain card identification but introduced unique hover effects for each card for better user experience.

**Testing**

- Verified responsiveness and functionality across multiple devices to ensure the layout works well on all screen sizes.

**Tools**

- Used Bootstrap classes such as those for griding, typography, tooltips and also custom css.

![Screenshot 2024-10-17 001654](https://github.com/user-attachments/assets/288caa74-abe8-4974-ad65-43fea9428017)
![Screenshot 2024-10-17 001748](https://github.com/user-attachments/assets/0b413080-97c3-4558-9b4c-85114102bed4)

2024-10-17 15:21 UTC, svrnm requested changes
this looks really good, thank you, please take a look into my comments, especially the one about formatting, otherwise I have a hard time to see what you have changed and what was there previously

2024-10-17 15:21 UTC, svrnm commented on assets/scss/_registry.scss
>  }
make sure that these CSS properties are only valid for the registry.

2024-10-17 15:21 UTC, svrnm commented on layouts/partials/ecosystem/registry/entry.html
you have a lot of unrelated changes to the format, that you need to revert, otherwise it is hard for me to identify what is new. If you run `npm run fix:format` locally they will hopefully be reverted, otherwise you may need to take a look manually

2024-10-18 08:17 UTC, DIANAAJAMBO commented on layouts/partials/ecosystem/registry/entry.html
I have run the command and it made changes to the registry file specifically. It had to do with the spacing between the classes and the curly brackets. Hopefully it was resolved.

2024-10-21 08:59 UTC, svrnm commented
@DIANAAJAMBO I like how the elements look now. An issue I am facing right now is, that the search does not work anymore. So if I type a term into the searchbar and search for it, no updated results are shown. Can you take a look and investigate?

2024-10-22 11:02 UTC, svrnm commented
Thank you @DIANAAJAMBO  ! This looks really good, I consider this as done! After the outreachy application phase we will take another look and see if we can merge this PR.

2024-10-25 18:03 UTC, closed without merging