Adding utility for Apache Druid ingestion of OTLP
open-telemetry/opentelemetry.io pull request #5427
Opened 2024-10-17 13:25 UTC by arusevm

A little extension for Apache Druid that allows it to ingest OTLP data.

2024-10-17 14:52 UTC, svrnm requested changes
thanks! a few comments inline

2024-10-17 14:52 UTC, svrnm commented on data/registry/tools-java-druid-extension-otlp.yaml
> +  analytics apps.
```suggestion
```

2024-10-17 14:52 UTC, svrnm commented on data/registry/tools-java-druid-extension-otlp.yaml
> +isFirstParty: true
```suggestion
isFirstParty: false
```

It would be first party if it would be provided by druid directly.

2024-10-19 06:59 UTC, arusevm commented
> thanks! a few comments inline

Thanks for the comments! :)

Suggested fixes are done, also build checks pass... I think it should be okay now? (Haven't done something like this before, sorry :(

2024-10-21 09:29 UTC, svrnm approved these changes

2024-10-21 09:34 UTC, merged