Redesign labels to be distinguishable from actual buttons
open-telemetry/opentelemetry.io pull request #5432
Opened 2024-10-18 07:43 UTC by Comfyydev

## Details
This PR implements a redesign of the labels used in the registry components to ensure that labels and buttons are easily identifiable, preventing any confusion between interactive and non-interactive elements.

## Before
![Screenshot from 2024-10-18 08-36-23](https://github.com/user-attachments/assets/d5000ea6-b90a-41f0-9386-0cdfa31c5723)

## After
![Screenshot from 2024-10-18 08-20-35](https://github.com/user-attachments/assets/1b4ab77b-da1a-4917-95ee-5ae6f7fa8feb)

Fixes #5306

2024-10-18 07:50 UTC, Comfyydev commented
@svrnm Could you please review my PR? Thanks.

2024-10-18 07:57 UTC, svrnm requested changes

2024-10-18 07:57 UTC, svrnm commented on assets/scss/_registry.scss
> +  }
can you make sure that this is only applied to the labels on the registry entries, such that if we plan to use labels somewhere else as well we do not run into isssues.

2024-10-18 07:57 UTC, svrnm commented on assets/scss/_registry.scss
> +  }
the dark theme looks different to the light theme to me, still more like a button due to the shadow/inlay effects

2024-10-18 12:59 UTC, Comfyydev commented
@svrnm I've updated the PR and implemented the requested changes.
Could you please review it?
Thanks.

2024-10-21 08:49 UTC, svrnm commented
@Comfyydev overall this looks good to me now, can you run `npm run fix:all` locally to make sure that all the CI checks pass, afterwards I am happy to accept this task as done.

2024-11-22 11:00 UTC, closed without merging

2024-11-22 11:00 UTC, svrnm commented
@Comfyydev thanks for working on this once again. Since we are currently turning those badges into working links, this PR is conflicting with the change, so I will close it.