Rework OpAMP visualization #5357
open-telemetry/opentelemetry.io pull request #5459
Opened 2024-10-22 19:10 UTC by taylorhelene

Diagram for Rework OpAMP visualization #5357. The link is found here: https://github.com/open-telemetry/opentelemetry.io/issues/5357

2024-10-23 07:37 UTC, svrnm requested changes

2024-10-23 07:37 UTC, svrnm commented on content/en/docs/collector/img/opamp.svg
the visualizations are distinctly different and the meaning is changed. Can you make sure that all the visual elements of the old visualization are contained in the new one, and no additional elements are added?

2024-10-23 13:43 UTC, svrnm commented on content/en/docs/collector/img/opamp.svg
this looks much better, thanks! It seems that there are multiple fonts used across the image, can you harmonize that? ideally with fonts used in existing visualizations? I also think that the it would be enough to have one row with receivers, exporters and processors

2024-10-23 13:48 UTC, taylorhelene commented on content/en/docs/collector/img/opamp.svg
Okay, I have redone the diagram.

2024-10-24 06:33 UTC, taylorhelene commented on content/en/docs/collector/img/opamp.svg
Done. Please review the changes.

2024-10-24 08:55 UTC, svrnm approved these changes
lgtm, thanks!

2024-10-25 07:05 UTC, svrnm commented
@open-telemetry/collector-approvers PTAL!

2024-10-25 07:47 UTC, mx-psi approved these changes

2024-10-25 13:49 UTC, codeboten requested changes
There's a typo in receive

2024-10-25 13:50 UTC, svrnm commented
> There's a typo in receive

oh, good catch! Then I am glad that the merge queue didn't merge it. @taylorhelene can you fix that typo please? thx

2024-10-28 17:48 UTC, taylorhelene commented
I made the change a while ago. Sorry for the typo😅

2024-11-02 23:07 UTC, cartermp approved these changes

2024-11-03 03:37 UTC, codeboten approved these changes

2024-11-04 00:29 UTC, chalin requested changes
Overall, nice improvement!

2024-11-04 00:29 UTC, chalin commented on content/en/docs/collector/img/opamp.svg
Don't round the corners of the images, since it looks strange in dark mode, e.g.:

> <img width="56" alt="image" src="https://github.com/user-attachments/assets/7cc55473-4c4f-45e7-b3f4-83dee30161c2">

2024-11-04 00:29 UTC, chalin commented on content/en/docs/collector/img/opamp.svg
Since we're updating this, let's make the following improvement. Drop the middle element and replace it by three dots. Then make the image narrower, something like this:

![image](https://github.com/user-attachments/assets/39b1860b-b6cc-4231-b259-5c8ba94c5826)

2024-11-04 08:50 UTC, svrnm commented
@taylorhelene there is something not working with merging your PR and the EasyCLA check. Can you address the open comments by @chalin and then close this PR and raise a new one? This was at least the solution for another PR where we had a similar issue

2024-11-04 08:52 UTC, taylorhelene commented on content/en/docs/collector/img/opamp.svg
I have made the changes, please review them

2024-11-04 08:59 UTC, taylorhelene commented on content/en/docs/collector/img/opamp.svg
[svrnm](https://github.com/svrnm) The branch was out of date with main but I  resolved the issue just now.

2024-11-04 15:07 UTC, chalin approved these changes
LGTM, thx!

2024-11-04 15:07 UTC, chalin commented
> @taylorhelene there is something not working with merging your PR and the EasyCLA check. Can you address the open comments by @chalin and then close this PR and raise a new one? This was at least the solution for another PR where we had a similar issue

All checks are green. Moving this into the merge queue.

2024-11-05 12:37 UTC, svrnm commented
@taylorhelene can you close this PR and open a new one?

2024-11-05 13:43 UTC, taylorhelene commented
Okay.

2024-11-05 13:43 UTC, closed without merging