feat: no search entries found page (#5372)
open-telemetry/opentelemetry.io pull request #5462
Opened 2024-10-23 01:56 UTC by JennySimen

Closes #5372 

This PR creates a new and better search result page when the is no seach found.

**Steps to view work**

1. Go to the registry page _/ecosystem/registry_
2. Enter a word in the search bar which does not exist (e.g juice)
3. View the new designed user interface

![Screenshot 2024-10-23 025055](https://github.com/user-attachments/assets/5eb2a243-6c16-48d1-8486-a15a39ce05e8)

2024-10-23 07:28 UTC, svrnm requested changes
this looks very good, thank you! One comment around the image, otherwise 👍

2024-10-23 07:28 UTC, svrnm commented on assets/icons/search-not-found.png
have you created that visualization yourself or is it from a 3rd party? Both is fine, but in the case that this is from a 3rd party, can you share a source, so we can verify that the license fits our project

2024-10-23 10:46 UTC, JennySimen commented
@svrnm Thank you very much for the feedback.

2024-10-23 10:47 UTC, JennySimen commented on assets/icons/search-not-found.png
I used a 3rd party- icons 8 illustration. Here is their [licence page](https://ethos-pei9368.slack.com/archives/D06PNKKNSSF/p1729676210656749). 

If it's not possible to use this illustration, I can gladly do the changes with another illustration that fits the project.

2024-10-23 13:36 UTC, svrnm commented on assets/icons/search-not-found.png
that link leads me to a slack space I am not in, can you send me a link that doesn't need authentication?

2024-10-23 13:43 UTC, JennySimen commented on assets/icons/search-not-found.png
Oh sorry about that, this is the [link](https://icons8.com/license)

2024-10-23 13:55 UTC, svrnm commented on assets/icons/search-not-found.png
that license is not compatible with our project, we would need something that's licensed with a creative common or proper open source license.

Let's do the following:
* from the perspective of what I asked you to do for the outreachy application phase, this is what I was looking for, so I will mark this as "done" for you.
* from the perspective of **merging** this PR and making it an official part of the website, we need something different. My preferred solution is something created specifically for our project. If you have the skills for that and create such a visualization, that would be awesome. Otherwise we can look for something we can use under such a compatible license.

2024-10-25 10:03 UTC, JennySimen commented on assets/icons/search-not-found.png
@svrnm I have made the requested change. I have changed the illustration to one which is licensed under [MIT license](https://iconduck.com/sets/pixeltrue-illustrations)

2024-11-26 10:42 UTC, svrnm commented
@JennySimen we are currently discussion https://github.com/open-telemetry/opentelemetry.io/issues/5681 to enable the import of the 3rd party image, after this being resolved we should be able to merge your PR

2024-11-26 11:05 UTC, JennySimen01 commented
Thank you, looking forward to having the pr merged.

2024-11-26 11:07 UTC, JennySimen commented
Thank you, looking forward to having the pr merged.

2024-12-05 09:56 UTC, svrnm commented
@JennySimen apologies for the delay and for going back and forth. I agree with @chalin's point in this comment (https://github.com/open-telemetry/opentelemetry.io/issues/5681#issuecomment-2518432557) that we should avoid adding the overhead of an image that needs attribution and a license reference in our code. It's much easier in docs/blog text since we simply can put a copy right notice below the image.

I copy the relevant part of the discussion:

> > Stepping back a bit regarding the original PR: have we considered using just a Font Awesome icon instead, or a completely-free-and-no-license-hassle stock image source?

the font awesome icons might be too small/minimalistic, I like the idea of the image, of course someone with a telescope not finding what they are looking for would be my preferred image. We could also use a variant of

https://opentelemetry.io/homepage-hero-as-background_hu13043826424429285166.jpg

WDYT?

2025-01-20 10:42 UTC, svrnm commented
@JennySimen any thoughts on my previous comment?

2025-01-20 11:02 UTC, JennySimen commented
Hi @svrnm, I think it's a great idea to use the above image instead.

2025-01-27 07:56 UTC, svrnm commented
> Hi @svrnm, I think it's a great idea to use the above image instead.

I saw that you requested my review, but nothing has changed, can you update the image as discussed? Thanks

2025-01-27 09:05 UTC, JennySimen commented
Hi @svrnm I have updated the image

2025-01-27 12:55 UTC, chalin requested changes
This is what it looks like now. The base OTel background image maybe a good choice, but we shouldn't be using a Hugo-modified version of it (in particular this one is too dark).

You should do a resources.Get on the original image (or something like that -- I'll need to investigate further).

> <img width="939" alt="image" src="https://github.com/user-attachments/assets/8d79ae71-6a23-4303-97f3-c2a24424ec18" />

2025-01-27 12:55 UTC, chalin commented on assets/js/registrySearch.js
> +
This new code logic isn't correct. It breaks the responsiviness to form dropdown selection once a "no results" page has been viewed.

2025-01-27 12:55 UTC, chalin commented on layouts/shortcodes/ecosystem/registry/search-form.html
> +          <p style="color: #4f62ad; font-size: 28px; margin-bottom: 0;">Oops no results found</p>
Nit: we shouldn't be hardcoding `styles` here.

2025-01-27 14:38 UTC, svrnm commented
> Hi @svrnm I have updated the image

I couldn't see that when I checked earlier today, now I do. See @chalin's feedback. It would also be great if the image is not black but aligns with the dark/light mode background, so you might need to edit that image, or we need to see if we can find a version with a light background

2025-02-17 00:14 UTC, JennySimen01 commented
Hi @svrnm, as per the feedback from @chalin concerning the image, it will be great if I could please get a version of the image with a lighter background to use since trying to edit it dosesn't seem to work.

2025-02-17 00:15 UTC, JennySimen commented
Hi @svrnm, as per the feedback from @chalin concerning the image, it will be great if I could please get a version of the image with a lighter background to use since trying to edit it dosesn't seem to work.

2025-02-25 15:16 UTC, chalin commented
> Hi @svrnm, as per the feedback from @chalin concerning the image, it will be great if I could please get a version of the image with a lighter background to use since I have not been able to edit it.

@tedsuo - can you help here. I think that you're the one who created the original artwork.

2025-03-02 23:12 UTC, JennySimen commented
> > Hi @svrnm, as per the feedback from @chalin concerning the image, it will be great if I could please get a version of the image with a lighter background to use since I have not been able to edit it.
> 
> @tedsuo - can you help here. I think that you're the one who created the original artwork.

Hi @tedsuo, is there anything from my side needed to have the lighter backgorund artwork?

2025-03-03 13:05 UTC, JennySimen commented
> @JennySimen - there are a few GitHub actions that are failing, such as: https://github.com/JennySimen/opentelemetry.io/actions/runs/13519263866
> 
> Could you refresh your fork, and disable those workflows? I keep getting failed workflow notifications from your fork. Thanks. /cc @trask

Hi @chalin I have disabled the workflows as requested

2025-03-03 18:15 UTC, chalin commented
> Hi @tedsuo, is there anything from my side needed to have the lighter backgorund artwork?

Let me ping @tedsuo @austinlparker et all on Slack to see if we can get response.

2025-03-03 18:21 UTC, austinlparker commented
The hero artwork was commissioned years ago, I forget by whom (or even if they have the originals any more -- IIRC I don't think I got a psd for it, just PNGs?)

Looking at this thread, why not just use a FOSS icon library then scale up the icon? They are vector images after all.

2025-03-03 21:12 UTC, chalin commented
Actually found a way using CSS `filter: brightness(3.6)`:

> <img width="1913" alt="image" src="https://github.com/user-attachments/assets/c5f80969-56d8-4b64-8397-d2fead6c1b31" />

It would be great to not have to duplicate the image, and just use the CSS, but for starters, set it up with the image above.

2025-05-09 07:50 UTC, svrnm commented
apologies for the huge delay once again, I was out of office for an extended period and I am just picking up some work I left behind. @JennySimen are you still open to push this forward? 

Currently the PR is blocked by not building properly, so maybe you want to look into the errors, there seems to be a dependency issue with `themes/docsy`, you can try to bring your PR up in sync with main and then locally run `npm run fix:submodule` to see if you can get it working. If not ping me and I can run this for you

2025-05-12 10:41 UTC, JennySimen commented
Thank you for the feedback. I'll try to fix the issue

2025-06-23 06:59 UTC, svrnm commented
@JennySimen any updates?

2025-06-24 01:31 UTC, JennySimen commented
@svrnm doing some changes to the code and having some issue with git but will update the PR soon.

2025-07-01 07:58 UTC, svrnm commented
@JennySimen it might be easier for you to close this PR and start with a new one since the repo has changed a lot since you started working on that. 

Let me know if you need any assistance with git/github, ideally ask on slack

2025-07-18 11:31 UTC, svrnm commented
@JennySimen I will close this PR for now, you can either reopen it or raise a new one to continue. Thanks

2025-07-18 11:31 UTC, closed without merging