Updated summary and table of internal telemetry
open-telemetry/opentelemetry.io pull request #5567
Opened 2024-11-08 17:53 UTC by jade-guiton-dd

I rewrote the "Values observable with internal metrics" section of the "Collector > Internal telemetry" page to accurately summarize existing telemetry instead of being partly wishful thinking. This should resolve #5483.

While doing that, I noticed that the table below was also inaccurate to the telemetry currently implemented in the Collector, so I updated it. (This involved replacing the `processor_accepted/dropped_*` metrics by `processor_incoming/outgoing_items`, and putting the `processor_batch` metrics under the correct level.)

I also added a note below the table which may be helpful in understanding it. It may be enough to resolve #5468. I will remove it if it is deemed unnecessary.

2024-11-10 16:33 UTC, theletterf requested changes

2024-11-10 16:33 UTC, theletterf commented on content/en/docs/collector/internal-telemetry.md
> +A more detailed list is available below.
```suggestion
A more detailed list is available in the following sections.
```

2024-11-10 16:33 UTC, theletterf commented on content/en/docs/collector/internal-telemetry.md
> +The `otelcol_processor_batch_` metrics are unique to the `batchprocessor`.
Add `batchprocessor` to the cSpell exceptions in the frontmatter.

2024-11-19 15:26 UTC, evan-bradley approved these changes

2024-11-20 07:14 UTC, svrnm commented
@theletterf please re-review

2024-11-20 07:17 UTC, theletterf approved these changes

2024-11-20 07:23 UTC, merged