docs: pt location on shortcode snippets /languages/exporters
open-telemetry/opentelemetry.io pull request #5593
Opened 2024-11-12 13:32 UTC by vitorvasc

* Add new translations:
   - layouts/shortcodes/pt/docs/languages/exporters/intro.md
   - layouts/shortcodes/pt/docs/languages/exporters/jaeger.md
   - layouts/shortcodes/pt/docs/languages/exporters/outro.md
   - layouts/shortcodes/pt/docs/languages/exporters/prometheus-setup.md
   - layouts/shortcodes/pt/docs/languages/exporters/zipkin-setup.md
* Fixes translations for snippets on:
   - content/pt/docs/concepts/components.md (https://opentelemetry.io/pt/docs/concepts/components/#exporters)
   - content/pt/docs/languages/go/exporters.md (https://opentelemetry.io/pt/docs/languages/go/exporters/)

Fixes #5592

2024-11-20 21:06 UTC, EzzioMoreira approved these changes
LGTM!!!
Parabéns @vitorvasc 🤘

2024-11-21 16:29 UTC, maryliag reviewed
Parabéns pelo trabalho, adicionei algumas recomendações 😄

2024-11-21 16:29 UTC, maryliag commented on layouts/shortcodes/pt/docs/languages/exporters/intro.md
> +{{/* cSpell:ignore cond */ -}} Envie dados de telemetria para o [OpenTelemetry Collector](/docs/collector/) para garantir que estes dados serão exportados corretamente. A utilização de um Collector e
```suggestion
{{/* cSpell:ignore cond */ -}} Envie dados de telemetria para o [OpenTelemetry Collector](/docs/collector/) para garantir que estes dados sejam exportados corretamente. A utilização de um Collector em ambientes de produção é a melhor prática. Para visualizar os dados de telemetria que foram gerados, exporte-os para um _backend_ como [Jaeger](https://jaegertracing.io/), [Zipkin](https://zipkin.io/),
```

2024-11-21 16:29 UTC, maryliag commented on layouts/shortcodes/pt/docs/languages/exporters/intro.md
> +O registro oferece uma [lista de exportadores específicos para a linguagem][reg].
```suggestion
O registro oferece uma [lista de exportadores específicos de linguagem][reg].
```

2024-11-21 16:29 UTC, maryliag commented on layouts/shortcodes/pt/docs/languages/exporters/intro.md
> + below list needs to grow until all languages are updated to a consistent structure.
```suggestion
 a lista a seguir precisa crescer até que todas as línguas sejam atualizadas para uma estrutura consistente.
```

2024-11-21 16:29 UTC, maryliag commented on layouts/shortcodes/pt/docs/languages/exporters/intro.md
> +[Prometheus](https://prometheus.io/), ou um backend
```suggestion
[Prometheus](https://prometheus.io/), ou um _backend_ 
```

2024-11-21 16:29 UTC, maryliag commented on layouts/shortcodes/pt/docs/languages/exporters/prometheus-setup.md
> +Caso já possua o Prometheus ou um backend compatível com Prometheus configurado, poderá pular esta seção e configurar as dependências do exportador [Prometheus](#prometheus-dependencies) ou [OTLP](#o
```suggestion
Caso já possua o Prometheus ou um _backend_ compatível com Prometheus configurado, poderá pular esta seção e configurar as dependências do exportador [Prometheus](#prometheus-dependencies) ou [OTLP](#otlp-dependencies) para a sua aplicação.
```

2024-11-21 16:29 UTC, maryliag commented on layouts/shortcodes/pt/docs/languages/exporters/zipkin-setup.md
> +Caso já possua o Zipkin ou um backend compatível com Zipkin configurado, poderá pular esta seção e configurar as [dependências do exportador Zipkin](#zipkin-dependencies) para a sua aplicação.
```suggestion
Caso já possua o Zipkin ou um _backend_ compatível com Zipkin configurado, poderá pular esta seção e configurar as [dependências do exportador Zipkin](#zipkin-dependencies) para a sua aplicação.
```

2024-11-21 16:29 UTC, maryliag commented on layouts/shortcodes/pt/docs/languages/exporters/intro.md
> +Em alguns instantes, o Collector estará disponível para receber dados de telemetria via OTLP. Mais tarde, você também poderá querer [configurar o Collector](/docs/collector/configuration) para enviar
```suggestion
Este Collector agora é capaz receber dados de telemetria via OTLP. Mais tarde, você também poderá [configurar o Collector](/docs/collector/configuration) para enviar os seus dados de telemetria para o seu _backend_ de observabilidade.
```

2024-11-21 16:29 UTC, maryliag commented on layouts/shortcodes/pt/docs/languages/exporters/outro.md
> +O SDK do OpenTelemetry fornece um conjunto de processadores de Trechos e Registros de Log padrão, que permitem emitir Trechos um-a-um ("simples") ou em lotes. O uso de agrupamentos é recomendado, mas
```suggestion
O SDK do OpenTelemetry fornece um conjunto de processadores padrão de trechos e registros de log, que permitem emitir trechos um-a-um ("simples") ou em lotes. O uso de agrupamentos é recomendado, mas caso não deseje agrupar seus trechos ou registros de log, é possível utilizar um processador simples da seguinte forma:
```

2024-11-21 16:29 UTC, maryliag commented on layouts/shortcodes/pt/docs/languages/exporters/outro.md
> +## Agrupamento de Trechos e Registros de Log {#batching-span-and-log-records}
```suggestion
## Agrupamento de trechos e registros de log {#batching-span-and-log-records}
```

2024-11-21 16:29 UTC, maryliag commented on layouts/shortcodes/pt/docs/languages/exporters/prometheus-setup.md
> +Para enviar dados de métricas para o [Prometheus](https://prometheus.io/), é possível
```suggestion
Para enviar dados de métricas para o [Prometheus](https://prometheus.io/), você pode
```

2024-11-21 16:29 UTC, maryliag commented on layouts/shortcodes/pt/docs/languages/exporters/prometheus-setup.md
> +e utilizar o [exportador OTLP](#otlp) ou utilizar o exportador do Prometheus, um `MetricReader` que inicia um servidor HTTP e coleta métricas, serializando para o formato de texto do Prometheus sob d
```suggestion
e utilizar o [exportador OTLP](#otlp) ou você pode utilizar o exportador do Prometheus, um `MetricReader` que inicia um servidor HTTP e coleta métricas, serializando para o formato de texto do Prometheus sob demanda.
```

2024-11-23 11:58 UTC, chalin requested changes
Thanks for this. Please:

- Wait for #5676 to be approved and merge
- Then rebase this PR from `main` and fix any formatting issues

2024-11-27 14:24 UTC, vitorvasc commented
Thank you @chalin! Will keep an eye on it.

2024-11-28 12:58 UTC, vitorvasc commented
> Thanks for this. Please:
> 
> * Wait for [[CI] Prettify es and pt shortcodes too #5676](https://github.com/open-telemetry/opentelemetry.io/pull/5676) to be approved and merge
> * Then rebase this PR from `main` and fix any formatting issues

@chalin Done!

2024-11-28 15:02 UTC, vitorvasc commented
/fix:format

2024-12-04 08:45 UTC, svrnm commented
@chalin PTAL!

2024-12-04 15:07 UTC, maryliag approved these changes

2024-12-04 19:22 UTC, chalin approved these changes
LGTM, TY ✨

2024-12-04 19:23 UTC, merged