Translate en-es Ref [es] Spanish folder localization docs/kubernetes #5227
open-telemetry/opentelemetry.io pull request #5607
Opened 2024-11-14 01:11 UTC by Victorsesan

2024-11-14 01:21 UTC, Victorsesan commented
👋@theletterf new PR up for review.

2024-11-14 09:53 UTC, theletterf commented on content/es/docs/kubernetes/getting-started.md
> +## Overview
No está traducido

2024-11-14 09:54 UTC, theletterf commented on content/es/docs/kubernetes/getting-started.md
> +## Preparation
@Victorsesan Los headings se pueden traducir. Si quieres mantener los anchors, usa esto: https://opentelemetry.io/docs/contributing/localization/#heading-anchors

2024-11-14 09:55 UTC, theletterf commented on content/es/docs/kubernetes/getting-started.md
> +Suponiendo que ya tiene [Helm instalado](https://helm.sh/docs/intro/install/),
Mejor hablar siempre de tú. Revisa que se hable de tú al usuario en todos los documentos.

2024-11-14 09:55 UTC, theletterf commented on content/es/docs/kubernetes/getting-started.md
> +Esta instancia del recopilador utilizará los siguientes componentes:
Mejor usar siempre "Collector" en lugar de una traducción.

2024-11-14 09:55 UTC, theletterf commented on content/es/docs/kubernetes/getting-started.md
> +Vamos a descomponerlos.
```suggestion
Vamos a ver sus partes.
```

2024-11-15 01:44 UTC, Victorsesan commented
Genial! Trabajaré más en lo demás y corregiré los errores, opening another PR with a fix👍

2024-11-19 19:22 UTC, chalin requested changes
As documented in https://opentelemetry.io/docs/contributing/pull-requests/#pr-guidelines:

> - **Do not work from the `main`** branch of your fork, but create a PR-specific
  branch.

2024-11-20 08:38 UTC, theletterf commented
@Victorsesan Could you please reopen the PR from a branch? Branching out your main into a branch and opening a new PR should be quick enough.

2024-11-20 08:38 UTC, closed without merging