Disable code-excerpting from Go getting-started
open-telemetry/opentelemetry.io pull request #5630
Opened 2024-11-18 23:01 UTC by chalin

- Fixes #5629
- No change to the generated site files, even after running `npm run code-excerpts`. (This will help make @jack-berg and the Java SIG's lives easier :)).

2024-11-18 23:11 UTC, jack-berg approved these changes

2024-11-19 02:13 UTC, tiffany76 approved these changes
RSLGTM.

2024-11-19 06:06 UTC, svrnm requested changes
https://github.com/open-telemetry/opentelemetry-go-contrib/pull/6300 is ongoing, so we could fix it that way, but I am fine with temporarily disabling it and re-enabling it when this work is done -- @open-telemetry/go-approvers: are you OK with this?

2024-11-19 07:39 UTC, pellared commented
> I am fine with temporarily disabling it and re-enabling it when this work is done -- @open-telemetry/go-approvers: are you OK with this?

LGTM

2024-11-19 07:39 UTC, pellared approved these changes

2024-11-19 08:30 UTC, dmathieu approved these changes

2024-11-19 08:44 UTC, svrnm approved these changes

2024-11-19 08:52 UTC, merged