Adding additional PHP no code example
open-telemetry/opentelemetry.io pull request #5747
Opened 2024-12-09 15:51 UTC by bobstrecansky

Adding an additional PHP no code example with reference.
Resolves: https://github.com/open-telemetry/opentelemetry-php/issues/1437

2024-12-18 09:48 UTC, svrnm commented
@bobstrecansky is this draft PR still needed or do we want to raise an issue instead until the PR is ready?

2024-12-25 19:39 UTC, bobstrecansky commented
Either way works for me

2025-01-16 15:55 UTC, chalin requested changes
Noting, for the record, that we (@bobstrecansky and SIG-comms) discussed this not to long ago and agreed that the code would be put elsewhere (not in this repo).

2025-05-09 07:33 UTC, svrnm commented
is this PR still needed/something to work on?

2025-07-21 06:41 UTC, svrnm commented
@bobstrecansky closing this PR for now

2025-07-21 06:41 UTC, closed without merging