[demo] Add Cart service exemplars doc
open-telemetry/opentelemetry.io pull request #5788
Opened 2024-12-13 12:48 UTC by julianocosta89

This PR adds documentation to the Exemplars added to the Cart service in the Demo.

It depends on the following issues to be merged: 
- https://github.com/open-telemetry/opentelemetry-demo/pull/1830
- https://github.com/open-telemetry/opentelemetry-demo/pull/1836

2024-12-13 12:58 UTC, julianocosta89 commented
`npm run fix:htmltest-config` is not changing anything 🤔

2024-12-13 22:35 UTC, puckpuck commented on content/en/docs/demo/services/cart.md
> +First it is created a `CartActivitySource`, `Meter` and two `Histograms`. The
Grammar

```suggestion
First it creates a `CartActivitySource`, `Meter` and two `Histograms`. The
```

2024-12-13 22:35 UTC, puckpuck approved these changes
One grammar nitpick, but this looks great otherwise.

2024-12-14 07:48 UTC, julianocosta89 commented
I need to update the screenshot based on @puckpuck's change in the Dashboard

2024-12-14 13:43 UTC, chalin requested changes
Since the image is specific to the cart service, I suggest the following:

- Create `content/en/docs/demo/services/cart/`
- Move and rename `content/en/docs/demo/services/cart.md` to `content/en/docs/demo/services/cart/index.md`
- Move and rename `content/en/docs/demo/screenshots/cart-service-exemplars.png` to `content/en/docs/demo/services/cart/exemplars.png`
- Adjust the in-page link to the image: `![Cart Service Exemplars](exemplars.png)`

/cc @svrnm

2024-12-16 10:45 UTC, svrnm approved these changes

2024-12-16 13:21 UTC, chalin commented
/fix:refcache

2024-12-16 13:27 UTC, chalin commented on content/en/docs/demo/services/cart/index.md
> +[Exemplars](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#exemplars)
```suggestion
[Exemplars](/docs/specs/otel/metrics/data-model/#exemplars)
```

2024-12-16 13:30 UTC, chalin commented
/fix:all

2024-12-16 15:39 UTC, chalin approved these changes
I won't have time to do a detailed review of the prose, but overall LGTM, as does the PR structure.

2024-12-16 15:40 UTC, chalin commented
We have all necessary approvals. Merging.

2024-12-16 15:40 UTC, merged